### ISSUE TITLE
DB Migration when not using Kickstart

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1419]
```
adam@tang ~/D/w/C/R/counterparty-lib (develop=) > counterparty-server --indexd-connect localhost --indexd-port 50001 --backend-user rpc --backend-password rpc start
[2024-02-18 14:27:30][INFO] Running v1.1.5 of counterparty-server.
[2024-02-18 14:27:30][INFO] Running v9.61.1 of counterparty-lib.
[2024-02-18 14:27:30][INFO] Acquiring lock.
[2024-02-18 14:27:30][INFO] Connecting to database (SQLite 3.44.2.0).
[2024-02-18 14:27:30][INFO] Connecting to address indexer.
[2024-02-18 14:27:30][INFO] Starting API Server.
 * Serving Flask app 'counterpartylib.lib.api'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:4000
Press CTRL+C to quit
[2024-02-18 14:27:45][ERROR] SQLITE_LOG: statement aborts at 3: [CREATE TABLE IF NOT EXISTS orders(
                            tx_index INTEGER,
                            tx_hash TEXT,
                            block_index INTEGER,
              (17) SQLITE_SCHEMA
[2024-02-18 14:27:56][ERROR] SQLITE_LOG: abort at 79 in [DROP TABLE old_orders]: FOREIGN KEY constraint failed (787) SQLITE_CONSTRAINT_FOREIGNKEY
[2024-02-18 14:27:56][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-cli/counterpartycli/server.py", line 179, in main
    server.start_all(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/server.py", line 492, in start_all
    blocks.follow(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/blocks.py", line 613, in follow
    initialise(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/blocks.py", line 397, in initialise
    order.initialise(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/messages/order.py", line 69, in initialise
    database.copy_old_table(cursor, 'orders', create_orders_query)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/database.py", line 204, in copy_old_table
    cursor.execute(f'''DROP TABLE old_{table_name}''')
  File "src/cursor.c", line 169, in resetcursor
apsw.ConstraintError: ConstraintError: FOREIGN KEY constraint failed
adam@tang ~/D/w/C/R/counterparty-lib (develop=) > 
```

**Comment by adamkrellenstein** [comment]
@ouziel-slama Was this done?

**Comment by ouziel-slama** [comment]
yep!
