### ISSUE TITLE
Failed Sanity Check

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1475]
```
[2024-03-07 12:03:47][INFO] Block: 833560 (1.60s, hashes: L:8c80e / TX:f8848 / M:7eee7)
[2024-03-07 12:03:49][INFO] Dispenser: bc1qmq0fdmjxh0e6pgfedj6q5dahxpar9f2ywvl77s opened a dispenser for asset A149878388735780115 with 7 balance, giving 1 A149878388735780115 for each 0.00100000 BTC
[2024-03-07 12:03:49][INFO] Dispenser: bc1q877pm6sfp4hctktgz4ljlj2kynmqzpsxp7zgdc opened a dispenser for asset A1334094899031611479 with 1 balance, giving 1 A1334094899031611479 for each 0.10000000 BTC
[2024-03-07 12:03:49][INFO] Dispenser: 1KwAo2wxghiGqNDd1BXw3XdaARcEyXSi1q opened a dispenser for asset PEPEGUN with 1.00000000 balance, giving 1.00000000 PEPEGUN for each 0.19000000 BTC
[2024-03-07 12:03:49][INFO] Dispenser: bc1qw83yf79vygjcvuwx58uznrpml4u9wz3vqscq0k opened a dispenser for asset A540671328907923291 with 1 balance, giving 1 A540671328907923291 for each 0.10000000 BTC
[2024-03-07 12:03:49][INFO] Block: 833561 (2.08s, hashes: L:ecc83 / TX:e2ae2 / M:7f88c)
[2024-03-07 12:03:51][INFO] Dispenser: 1GpqKK7nfTDfoQ3gWrRJY84zn5TDFrSnDa opened a dispenser for asset BITCOINPEPE with 1 balance, giving 1 BITCOINPEPE for each 0.04500000 BTC
[2024-03-07 12:03:51][INFO] Broadcast: bc1qgk47ah4jvvwf7s6auw4keylevh3sflx8hafj3c at 2024-03-07T11:06:32+00:00 with a fee of 0.0%% (46d902dbd36de76ec51aa93736515946b8635905d72ae0e82b588cb7fed84fcc) [valid]
[2024-03-07 12:03:51][INFO] Send: SJCXCARD from 14PxDTVUMCjLoAcGPZGQf6cEtn7yLzdHp1 to 19RfaWiQnoqkmbUSDosKymg4mALrNbN13p (7fd3bd2123547a97f4b7df568c4b2e0b73ab513644a7b7f1a623cfaa048703dd) [valid]
[2024-03-07 12:03:51][INFO] Broadcast: bc1qpvmcqcx99cemaj5f9gls70q7tn29gr72qaf0zz at 2024-03-07T10:46:00+00:00 with a fee of 0.0%% (9e805f2d0aaea2e25b676bcc439c16ff41897d8883db474b359a679038d95ef0) [valid]
[2024-03-07 12:03:51][INFO] Broadcast: bc1qpvmcqcx99cemaj5f9gls70q7tn29gr72qaf0zz at 2024-03-07T10:49:00+00:00 with a fee of 0.0%% (ff0cc1b02d50c427df9f70bea813b09b2d5ab69afc80c47fd0b1588d1208446d) [valid]
[2024-03-07 12:03:51][INFO] Broadcast: bc1qpvmcqcx99cemaj5f9gls70q7tn29gr72qaf0zz at 2024-03-07T10:53:00+00:00 with a fee of 0.0%% (a3b7d68a84af1509e54aeab9d61142a31b5ca5b7d2683a498f6a3d81d5dfd2fa) [valid]
[2024-03-07 12:03:51][INFO] Block: 833562 (1.82s, hashes: L:ea12f / TX:d0023 / M:6c3ac)
[2024-03-07 12:03:53][INFO] Broadcast: bc1qpvmcqcx99cemaj5f9gls70q7tn29gr72qaf0zz at 2024-03-07T10:45:00+00:00 with a fee of 0.0%% (d0d7d658e0511fe9f0212d39cdd01b4eade5659cef9d795e3da73b3d447acefb) [invalid: feed timestamps not monotonically increasing]
[2024-03-07 12:03:53][INFO] Broadcast: bc1qpvmcqcx99cemaj5f9gls70q7tn29gr72qaf0zz at 2024-03-07T10:48:00+00:00 with a fee of 0.0%% (baa4d0c296bc177952ce755a3b5f21e690b0980d21e6971dd81199e3a8a38bab) [invalid: feed timestamps not monotonically increasing]
[2024-03-07 12:03:53][INFO] Broadcast: bc1qpvmcqcx99cemaj5f9gls70q7tn29gr72qaf0zz at 2024-03-07T10:50:00+00:00 with a fee of 0.0%% (67f088d2a6f9ce350dc607cc58c27ea30621ed80763ee9f4467b5dab1f2c3233) [invalid: feed timestamps not monotonically increasing]
[2024-03-07 12:03:53][INFO] Subasset Issuance: 1E6tyJ2zCyX74XgEK8t9iNMjxjNVLCGR1u created 50 of indivisible subasset PEPEALBUM.Norma_Pepe as numeric asset A16726363240412617971 (89a733c7996751029ef1fb79b89e1c04fd31296746c9d42e42a4d4447f24df79) [valid]
[2024-03-07 12:03:53][INFO] Issuance: 1GrgWZdXEMrcq9BUfrx7kakeBZ4xQgKCag created 69 of indivisible asset A2121000000050000333 (0b66e4c39b2c2ff3ac36c6dce3edbd34965fe83cb769730b850efb20910485bd) [valid]
[2024-03-07 12:03:53][INFO] Issuance: 1GrgWZdXEMrcq9BUfrx7kakeBZ4xQgKCag locked asset A2121000000050000333 (0b66e4c39b2c2ff3ac36c6dce3edbd34965fe83cb769730b850efb20910485bd) [valid]
[2024-03-07 12:03:53][INFO] Block: 833563 (1.65s, hashes: L:b16f7 / TX:58bd1 / M:b30b5)
[2024-03-07 12:03:54][INFO] Block: 833564 (1.39s, hashes: L:66dec / TX:e1ea5 / M:d6be2)
[2024-03-07 12:03:55][INFO] Send: NECROPEPE from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPEDRYAD from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPEJOANARC from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPEJORN from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPENAPOLEON from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPESAKURA from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: PROPHECYPEPE from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (80ea4f8ae8fae0aee5b6ec7c09c038a9b477755b119758eaeee215a5137713b2) [valid]
[2024-03-07 12:03:55][INFO] Send: FEELSPEPE from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (480ec97a54753d773d4dae56a78e3b949082548c270e3df309245dc9cbd0a147) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPERAMBO from 12TVPcQeLaBuTAehLCgLxAFZYcQDoAQKBi to 12oNiffphgxrY3SYzpLNwJ7AsTGGQGr3iJ (480ec97a54753d773d4dae56a78e3b949082548c270e3df309245dc9cbd0a147) [valid]
[2024-03-07 12:03:55][INFO] Send: BEETLEPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: BOYZIIPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: DELOREANPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: FAKEWARHOL from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: FRYPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: GORDONKEKO from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPEFATHER from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPEHOLOGRAM from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPEROGAN from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPETHEFROG from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: PEPETRON from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: ROGANPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: SNOWDENPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: TESTPEPE from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Send: WACKNAKAMOTO from 1AE4vfkDX4S49kxsuCve7zJDS5s5RtHYNs to 1CjM4dsAMsZBpCWVrhj4NSDJrKTujKjpGe (361816267f431d79509828dd1b3392cc8de2d003ec2c460ca2438812ac16c836) [valid]
[2024-03-07 12:03:55][INFO] Dispenser: bc1qzwh54g86ady5au4xju3ur5jff4uy6up7eac75n opened a dispenser for asset BLOCPEPE with 69 balance, giving 1 BLOCPEPE for each 0.00029799 BTC
[2024-03-07 12:05:47][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 181, in main
    server.start_all(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 514, in start_all
    blocks.follow(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 815, in follow
    check.asset_conservation(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/check.py", line 276, in asset_conservation
    raise SanityError('{} {} issued ≠ {} {} held'.format(ledger.value_out(db, asset_issued, asset), asset, ledger.value_out(db, asset_held, asset), asset))
counterpartylib.lib.check.SanityError: 111 HOMERMKBOSHI issued ≠ 112 HOMERMKBOSHI held
adam@api3:~$ 
```

**Comment by ouziel-slama** [comment]
Fixed
