### ISSUE TITLE
Make Health Check Endpoint Heavier

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1481]
We want it to check that Counterparty is *fully* up and running. What @jdogresorg has been using for Pingdom is a `create_send` call. We can have the `/healthz` endpoint do a `create_send` and verify that it was successful before returning `200 Healthy`.

```
{
    "method" : "create_send",
    "params" : {
		"source": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev",
		"destination": "1FwkKA9cqpNRFTpVaokdRjT9Xamvebrwcu",
		"asset": "XCP",
		"quantity": 100000000,
		"allow_unconfirmed_inputs": true,
		"fee": 1000
    },
    "jsonrpc" : "2.0",
    "id" : 0
}
```

**Comment by adamkrellenstein** [comment]
Getting this problem intermittently, also:

```
7|counterparty-server start  | WARNING:root:Error composing send transaction via API: Insufficient BTC at address 1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev. (Need approximately 0.00036274 BTC.) T
o spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)                                                                      
7|counterparty-server start  | WARNING:root:Traceback (most recent call last):                                                                                                              
7|counterparty-server start  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/api.py", line 636, in create_method                                                
7|counterparty-server start  |     return compose_transaction(self.db, name=tx, params=transaction_args, **common_args)                                                                     
7|counterparty-server start  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/api.py", line 480, in compose_transaction                                          
7|counterparty-server start  |     return transaction.construct(db, tx_info, encoding=encoding,                                                                                             
7|counterparty-server start  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/transaction.py", line 488, in construct                                            
7|counterparty-server start  |     inputs, change_quantity, n_btc_in, n_final_fee = construct_coin_selection(                                                                               
7|counterparty-server start  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/transaction.py", line 231, in construct_coin_selection                             
7|counterparty-server start  |     raise exceptions.BalanceError(f'Insufficient {config.BTC} at address {source}. (Need approximately {total_btc_out / config.UNIT} {config.BTC}.) To spend 
unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)')                                                                            
7|counterparty-server start  | counterpartylib.lib.exceptions.BalanceError: Insufficient BTC at address 1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev. (Need approximately 0.00036274 BTC.) To spend un
confirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)                                                                                
7|counterparty-server start  | WARNING:root:Error composing send transaction via API: Insufficient BTC at address 1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev. (Need approximately 0.00036274 BTC.) T
o spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)
```

I feel like we should use the 1CounterpartyXXXXXXXX address for this purpose. :)

**Comment by mattmarcello** [comment]
Currently addrindexrs is not returning unspent txouts reliably, making it difficult to implement the `create_send` probe.  #1288  

This is addressed by this PR: CounterPartyXCP/addrindexrs#23

In the interim, are there any other transactions we could compose that touch all parts of the system but do not rely on correct unspent values from addrindexrs?

**Comment by ouziel-slama** [comment]
yep! we could make a quick release of `v0.4.5`!

**Comment by ouziel-slama** [comment]
https://github.com/CounterpartyXCP/addrindexrs/releases/tag/v0.4.5 (docker image published)

**Comment by mattmarcello** [comment]
@ouziel-slama @adamkrellenstein think this can be closed, pending your :+1:
