### ISSUE TITLE
`Connection reset by peer` causes crash

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1482]
I think we just want some retry logic here.

```
[2024-03-08 00:57:45][INFO] Block: 822398 (0.57, hashes: L:bc376 / TX:efcda / M:c62ce)
[2024-03-08 00:57:47][INFO] Order: 1NfJnJdAdmm2rJCFW54NsAKqqTTMexCNJ3 ordered SARUTOBIISL for XCP in 8064 blocks, with a provided fee of 0.00001800 BTC and a required fee of 0.00000000 BTC (68734aa14aaab82cd5820df3c0c35b089eeff50b9a6aa1372a0466efe24c15be) [expired]
[2024-03-08 00:57:47][INFO] Expired order: 68734aa14aaab82cd5820df3c0c35b089eeff50b9a6aa1372a0466efe24c15be
[2024-03-08 00:57:48][INFO] Send: A5010972084951553000 from bc1q5ufecc7kvmugnfnpv45t5gc2yv8xh98nlypunl to bc1qlsf0c6z2z06de4semzcethx884dj7zz4rdnnff (cdf010eb5dc42a0a412b8094fae686b8a1df3b03a910610bd8a568ffbf14da08) [valid]
[2024-03-08 00:57:48][INFO] Send: A8347096695242810000 from bc1qdl45myhp64vvyhnljkrjdx0ememkrcxj5x30m4 to bc1qmmexkdyv47rj808q92xykd7q0vyqwfmqnu2ekd (a4d21c8f3211e6c98f8fd49224bf4a64b6fd393b6ffbbc3c525a7832d16e410e) [valid]
[2024-03-08 00:57:48][INFO] Broadcast: bc1qppzsxqsxy88gjkqg4rksu8pgsnlezwlunkd62y at 2023-12-22T14:26:00+01:00 with a fee of 0.0%% (236cb0746c6ad675c0ee0d047e9cde7edbe21943776839168c41dc15dee06d13) [valid]
[2024-03-08 00:57:48][INFO] Dispenser: bc1q9xmm2kxrq09ryfpx3dzv8mxrvjmhyh478uqw3h opened a dispenser for asset A1953211903256190000 with 1 balance, giving 1 A1953211903256190000 for each 0.14500000 BTC
[2024-03-08 00:57:53][INFO] Dispenser: bc1q09uwsck5d2q9a3ar24rcll6n8x38h7tkp6mg8w opened a dispenser for asset A5477856533625565000 with 1 balance, giving 1 A5477856533625565000 for each 0.00022000 BTC
[2024-03-08 00:57:53][INFO] Block: 822399 (8.26, hashes: L:86b04 / TX:635fa / M:8c6ba)
[2024-03-08 00:57:54][INFO] Dispenser: 1BgofvFLoJmrMh2y47dACbxzVnX2BzgYEc closed a dispenser for asset A8661839341114679000
[2024-03-08 00:57:54][INFO] Broadcast: bc1q2d607c477wf7eul3kpzdddar0w3ey4rqkgpnsy at 2023-12-22T15:01:00+01:00 with a fee of 0.0%% (63144accbfaae25dd977cfdc1783c60a8daa392f28a516f163181051ebae37a3) [valid]
[2024-03-08 00:57:54][INFO] Block: 822400 (1.36, hashes: L:7b0c3 / TX:1cf41 / M:0af2b)
[2024-03-08 00:57:55][INFO] Issuance: 1JBEzg8ZcQQiLwJtDgp6Q4ssNxexoYQx8N created 1 of indivisible asset FLOCKING (82569b856b310500b92349e0d3672dfe9d02bdeb062e819a6f85ed0802efbb49) [valid]
[2024-03-08 00:57:55][INFO] Broadcast: 13kQEf3fiHHs48ULeBTj3nUs7SgMXFXtyp at 2023-12-22T14:53:00+01:00 with a fee of 0.0%% (c6daec097341878ad1806dd0cabeb9357787f6998f0ac1ea4c2db51032b2873e) [valid]
[2024-03-08 00:57:55][INFO] Dispenser: bc1q59p0p95xrqfqy0ypuxds0aes7xjfm3pn70l927 closed a dispenser for asset A8177403988575295000
[2024-03-08 00:57:55][INFO] Dispense: A8177403988575295000 from bc1q59p0p95xrqfqy0ypuxds0aes7xjfm3pn70l927 to 1CnGR3gqUYLHrx897ddxSKd1VVHtXAiqtv (72360baab9bfaee9a1ce013918917062b5add6ec54cb57e9ec94db7676f4d8e6)
[2024-03-08 00:57:55][INFO] Dispenser: bc1qjmgj3jeuhykr2x9te6gvcgavzupnpdpnzmq83w closed a dispenser for asset A533808838726115800
[2024-03-08 00:57:55][INFO] Dispense: A533808838726115800 from bc1qjmgj3jeuhykr2x9te6gvcgavzupnpdpnzmq83w to bc1q9ffnuxq9rt6a5nd5kdpuqsv0smdyxc77vav5ft (24cb3ac0479ea29d161ceb91f3468d5ca9e40969894e5309abcee32773e3ceb5)
[2024-03-08 00:57:55][INFO] Dispenser: 1CVPrpDYZ28yjiVH3cEKqHGG5MYoZVgdEf opened a dispenser for asset A12325408577745627978 with 25 balance, giving 1 A12325408577745627978 for each 0.00100000 BTC
[2024-03-08 00:57:55][INFO] Dispense: A12325408577745627978 from 1CVPrpDYZ28yjiVH3cEKqHGG5MYoZVgdEf to 3BbokbBfHoEbAMp2o2VRmCGg13Zzyhbv5g (fd193130e3a5d5cf41524240b390c4358f66b28f61097d1135efdb7deeaa0d9a)
[2024-03-08 00:57:55][INFO] Block: 822401 (0.52, hashes: L:16433 / TX:4bd22 / M:a49ce)
[2024-03-08 00:58:02][INFO] Dispenser: bc1q08z6xhrlnmmt6kjlv3agcv52u2v7mr7er6e55y opened a dispenser for asset A241301191507000001 with 50 balance, giving 1 A241301191507000001 for each 0.00054000 BTC
[2024-03-08 00:58:02][WARNING] ParseTransactionError for tx 9bd7da4693903226ae1a322dc8095e19c821184b6740c86d07d39d8c8edd7b30: [Errno 54] Connection reset by peer
[2024-03-08 00:58:02][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 140, in parse_tx
    dispenser.parse(db, tx, message)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 325, in parse
    asset_id, problems = validate(db, tx['source'], asset, give_quantity, escrow_quantity, mainchainrate, dispenser_status, action_address if dispenser_status in [STATUS_OPEN_EMPTY_ADDRESS, STATUS_CLOSED] else None, tx['block_index'], oracle_address)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 240, in validate
    address_oldest_transaction = backend.get_oldest_tx(query_address)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 215, in get_oldest_tx
    return backend().get_oldest_tx(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 628, in get_oldest_tx
    return ADDRINDEXRS_CLIENT.get_oldest_tx(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 619, in get_oldest_tx
    return self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 605, in send
    return self._send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 583, in _send
    data = self.sock.recv(READ_BUF_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/server.py", line 180, in main
    server.start_all(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/server.py", line 515, in start_all
    blocks.follow(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 810, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 198, in parse_block
    raise e
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 194, in parse_block
    parse_tx(db, tx)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 159, in parse_tx
    raise exceptions.ParseTransactionError(f"{e}")
counterpartylib.lib.exceptions.ParseTransactionError: [Errno 54] Connection reset by peer
adam@tang ~ >
```

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-core/pull/1500
