### ISSUE TITLE
Missing Config Option Blocks Help

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1495]
```
adam@tang ~ > counterparty-server --help
Running v9.61.1 of Counterparty Core.
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/server.py", line 140, in main
    server.initialise_config(**init_args)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/server.py", line 230, in initialise_config
    raise ConfigurationError("Please specific a valid password backend-password configuration parameter")
counterpartylib.server.ConfigurationError: Please specific a valid password backend-password configuration parameter
adam@tang ~ > 
```

**Comment by ouziel-slama** [comment]
Fixed here https://github.com/CounterpartyXCP/counterparty-core/commit/f123a0a2087b6647b5f92edf33e31ca8edd50bb9
