### ISSUE TITLE
Connection Reset by Peer

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1498]
I'm getting this all the time, even though nothing is obv. wrong with `addrindexrs`. I think the retry logic just needs to be improved.

```
[2024-03-11 14:02:32][INFO] Dispenser: bc1q08z6xhrlnmmt6kjlv3agcv52u2v7mr7er6e55y opened a dispenser for asset A241301191507000001 with 50 balance, giving 1 A241301191507000001 for each 0.00054000 BTC
[2024-03-11 14:02:32][WARNING] ParseTransactionError for tx 9bd7da4693903226ae1a322dc8095e19c821184b6740c86d07d39d8c8edd7b30: [Errno 54] Connection reset by peer
[2024-03-11 14:02:32][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 142, in parse_tx
    dispenser.parse(db, tx, message)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 326, in parse
    asset_id, problems = validate(db, tx['source'], asset, give_quantity, escrow_quantity, mainchainrate, dispenser_status, action_address if dispenser_status in [STATUS_OPEN_EMPTY_ADDRESS, STATUS_CLOSED] else None, tx['block_index'], oracle_address)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 241, in validate
    address_oldest_transaction = backend.get_oldest_tx(query_address)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 216, in get_oldest_tx
    return backend().get_oldest_tx(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 629, in get_oldest_tx
    return ADDRINDEXRS_CLIENT.get_oldest_tx(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 620, in get_oldest_tx
    return self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 606, in send
    return self._send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 584, in _send
    data = self.sock.recv(READ_BUF_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/server.py", line 181, in main
    server.start_all(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/server.py", line 496, in start_all
    blocks.follow(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 816, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 200, in parse_block
    raise e
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 196, in parse_block
    parse_tx(db, tx)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 161, in parse_tx
    raise exceptions.ParseTransactionError(f"{e}")
counterpartylib.lib.exceptions.ParseTransactionError: [Errno 54] Connection reset by peer
Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 142, in parse_tx
    dispenser.parse(db, tx, message)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 326, in parse
    asset_id, problems = validate(db, tx['source'], asset, give_quantity, escrow_quantity, mainchainrate, dispenser_status, action_address if dispenser_status in [STATUS_OPEN_EMPTY_ADDRESS, STATUS_CLOSED] else None, tx['block_index'], oracle_address)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 241, in validate
    address_oldest_transaction = backend.get_oldest_tx(query_address)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 216, in get_oldest_tx
    return backend().get_oldest_tx(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 629, in get_oldest_tx
    return ADDRINDEXRS_CLIENT.get_oldest_tx(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 620, in get_oldest_tx
    return self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 606, in send
    return self._send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 584, in _send
    data = self.sock.recv(READ_BUF_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-cli/counterpartycli/server.py", line 181, in main
    server.start_all(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/server.py", line 496, in start_all
    blocks.follow(db)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 816, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 200, in parse_block
    raise e
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 196, in parse_block
    parse_tx(db, tx)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 161, in parse_tx
    raise exceptions.ParseTransactionError(f"{e}")
counterpartylib.lib.exceptions.ParseTransactionError: [Errno 54] Connection reset by peer
adam@tang ~/D/w/C/R/counterparty-core (develop=) > 
```

**Comment by adamkrellenstein** [comment]
Fixed: c4efea24a1b0f3115f4d0b6c14233ba3321f5a6a
