### ISSUE TITLE
Bad failure when `bitcoind` isn't running

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1502]
```
adam@api3:~/counterparty-core$ counterparty-server start
Running v10.0.0-alpha of Counterparty Core.
[2024-03-12 12:43:09][INFO] Running v10.0.0-alpha of counterparty-server.
Writing log to file: `/home/adam/.cache/counterparty/log/server.log`
Writing API accesses log to file: `/home/adam/.cache/counterparty/log/server.access.log`
------------------------------ start ------------------------------

[2024-03-12 12:43:09][INFO] Connecting to address indexer.
[2024-03-12 12:44:10][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 182, in main
    server.start_all(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 483, in start_all
    connect_to_backend()
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 463, in connect_to_backend
    backend.getblockcount()
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 54, in getblockcount
    return backend().getblockcount()
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 159, in getblockcount
    return rpc('getblockcount', [])
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 100, in rpc
    return rpc_call(payload)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 72, in rpc_call
    response_json = response.json()
AttributeError: 'NoneType' object has no attribute 'json'
Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 20, in server_main
    server.main()
  File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 182, in main
    server.start_all(db)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 483, in start_all
    connect_to_backend()
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 463, in connect_to_backend
    backend.getblockcount()
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 54, in getblockcount
    return backend().getblockcount()
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 159, in getblockcount
    return rpc('getblockcount', [])
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 100, in rpc
    return rpc_call(payload)
  File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 72, in rpc_call
    response_json = response.json()
AttributeError: 'NoneType' object has no attribute 'json'
adam@api3:~/counterparty-core$ 
```

**Comment by ouziel-slama** [comment]
hum.. he already tries 12 times before this error occurs.. should we continue indefinitely or stop the server with a clean message ?

**Comment by adamkrellenstein** [comment]
I think continue indefinitely. It can take a while for it to start up.

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1518
