### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#1569]
**Describe the Problem**
Using `v10.0.0-beta.1` retrieving asset info `counterparty-client` raises a recursion error and the asset info is not returned.

**Steps To Reproduce**
1. run `counterparty-client --counterparty-rpc-user rpc --counterparty-rpc-password rpc asset $ASSET`

**Screenshots and Logfiles**
```
counterparty-client --counterparty-rpc-user rpc --counterparty-rpc-pa
ssword rpc asset XCP

Unhandled Exception
Traceback (most recent call last):
  File "/home//.local/bin/counterparty-client", line 8, in <module>
    sys.exit(client_main())
             ^^^^^^^^^^^^^
  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 16, in client_main
    client.main()
  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/client.py", line 272, in main
    view = console.get_view(args.action, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/console.py", line 10, in get_view
    return wallet.asset(args.asset)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/wallet/__init__.py", line 162, in asset
    for bunch in get_btc_balances():
  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/wallet/__init__.py", line 33, in get_btc_balances
    for address, btc_balance in wallet().get_btc_balances():

[...]

  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/wallet/__init__.py", line 110, in wallet
    for bunch in get_btc_balances():
  File "/home//counterparty/counterparty-core/counterparty-cli/counterpartycli/wallet/__init__.py", line 33, in get_btc_balances
    for address, btc_balance in wallet().get_btc_balances():
                                ^^^^^^^^
RecursionError: maximum recursion depth exceeded```

**Comment by adamkrellenstein** [comment]
hm yeah we haven't really tested `counerparty-client` at all... it may be badly broken! 😬

**Comment by ouziel-slama** [comment]
Bug fixed here:  https://github.com/CounterpartyXCP/counterparty-core/commit/233a4a90a68a3a99fbff1c2494d1fef40a63b8b0
but now you probably will get this error:
```
counterpartycli.util.RPCError: {'code': -18, 'message': 'No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)'}
```

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-core/issues/1581
