### ISSUE TITLE
counterpartylib.lib.exceptions.ParseTransactionError: index out of range

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1619]
```
10|counterparty  | ------------------------------ start ------------------------------
10|counterparty  | [2024-04-10 02:48:04][INFO] Connecting to address indexer.
10|counterparty  | [2024-04-10 02:48:04][INFO] Acquiring lock.
10|counterparty  | [2024-04-10 02:48:04][INFO] Connecting to database (SQLite 3.45.1.0).
10|counterparty  | ERROR:root:SQLITE_LOG: recovered 626 frames from WAL file /home/adam/.local/share/counterparty/counterparty.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
10|counterparty  | [2024-04-10 02:48:04][INFO] Starting API Server.
10|counterparty  | [2024-04-10 02:48:05][INFO] Resuming parsing.
10|counterparty  | [2024-04-10 02:48:05][INFO] New block inserted 838540
10|counterparty  | [2024-04-10 02:48:06][INFO] New transaction inserted 255930ade36ea75bb1c9373417fe627bc8e9f484da1489e8535ae9fb59adfa86
10|counterparty  | [2024-04-10 02:48:06][WARNING] ParseTransactionError for tx 255930ade36ea75bb1c9373417fe627bc8e9f484da1489e8535ae9fb59adfa86: index out of range
10|counterparty  | [2024-04-10 02:48:06][ERROR] Unhandled Exception
10|counterparty  | Traceback (most recent call last):
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 142, in parse_tx
10|counterparty  |     dispenser.parse(db, tx, message)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 314, in parse
10|counterparty  |     action_address = address.unpack(message[LENGTH:LENGTH+21])
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/address.py", line 56, in unpack
10|counterparty  |     if enabled('segwit_support') and short_address_bytes[0] >= 0x80 and short_address_bytes[0] <= 0x8F:
10|counterparty  | IndexError: index out of range
10|counterparty  | During handling of the above exception, another exception occurred:
10|counterparty  | Traceback (most recent call last):
10|counterparty  |   File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
10|counterparty  |     sys.exit(server_main())
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 20, in server_main
10|counterparty  |     server.main()
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 230, in main
10|counterparty  |     server.start_all(catch_up=args.catch_up)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 543, in start_all
10|counterparty  |     blocks.follow(db)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 823, in follow
10|counterparty  |     new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 200, in parse_block
10|counterparty  |     raise e
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 196, in parse_block
10|counterparty  |     parse_tx(db, tx)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 161, in parse_tx
10|counterparty  |     raise exceptions.ParseTransactionError(f"{e}")
10|counterparty  | counterpartylib.lib.exceptions.ParseTransactionError: index out of range
10|counterparty  | Traceback (most recent call last):
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 142, in parse_tx
10|counterparty  |     dispenser.parse(db, tx, message)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 314, in parse
10|counterparty  |     action_address = address.unpack(message[LENGTH:LENGTH+21])
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/address.py", line 56, in unpack
10|counterparty  |     if enabled('segwit_support') and short_address_bytes[0] >= 0x80 and short_address_bytes[0] <= 0x8F:
10|counterparty  | IndexError: index out of range
10|counterparty  | During handling of the above exception, another exception occurred:
10|counterparty  | Traceback (most recent call last):
10|counterparty  |   File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
10|counterparty  |     sys.exit(server_main())
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/__init__.py", line 20, in server_main
10|counterparty  |     server.main()
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-cli/counterpartycli/server.py", line 230, in main
10|counterparty  |     server.start_all(catch_up=args.catch_up)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 543, in start_all
10|counterparty  |     blocks.follow(db)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 823, in follow
10|counterparty  |     new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 200, in parse_block
10|counterparty  |     raise e
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 196, in parse_block
10|counterparty  |     parse_tx(db, tx)
10|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 161, in parse_tx
10|counterparty  |     raise exceptions.ParseTransactionError(f"{e}")
10|counterparty  | counterpartylib.lib.exceptions.ParseTransactionError: index out of range
10|counterparty  | Unhandled Exception
```

**Comment by adamkrellenstein** [comment]
Ugh this is a problem also with v9.61.1:
```
[2024-04-10 02:49:41][INFO] Running v1.1.5 of counterparty-server.
[2024-04-10 02:49:41][INFO] Running v9.61.1 of counterparty-lib.
[2024-04-10 02:49:41][INFO] Acquiring lock.
[2024-04-10 02:49:41][INFO] Connecting to database (SQLite 3.24.0-r1).
[2024-04-10 02:49:41][INFO] Connecting to backend.
[2024-04-10 02:49:41][INFO] AddrIndexRs connecting...
[2024-04-10 02:49:41][INFO] Connected to AddrIndexRs!
[2024-04-10 02:49:41][INFO] Starting API Server.
[2024-04-10 02:49:51][INFO] Resuming parsing.
[2024-04-10 02:49:57][WARNING] ParseTransactionError for tx 255930ade36ea75bb1c9373417fe627bc8e9f484da1489e8535ae9fb59adfa86: index out of range
[2024-04-10 02:49:57][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 129, in parse_tx
    dispenser.parse(db, tx, message)
  File "/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 262, in parse
    action_address = address.unpack(message[LENGTH:LENGTH+21])
  File "/counterparty-lib/counterpartylib/lib/address.py", line 54, in unpack
    if enabled('segwit_support') and short_address_bytes[0] >= 0x80 and short_address_bytes[0] <= 0x8F:
IndexError: index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 172, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 494, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1483, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 211, in parse_block
    raise e
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 205, in parse_block
    parse_tx(db, tx)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 148, in parse_tx
    raise exceptions.ParseTransactionError("%s" % e)
counterpartylib.lib.exceptions.ParseTransactionError: index out of range
```

**Comment by adamkrellenstein** [comment]
Fixed here: https://github.com/CounterpartyXCP/counterparty-core/pull/1620
