### ISSUE TITLE
Rust Panics in Counterparty Logs

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1622]
Panicking doesn't seem like right behavior, but if it is, it should be covered up.

```
18|counterparty  | thread '<unnamed>' panicked at src/b58.rs:19:10:
18|counterparty  | bad: NoChecksum
18|counterparty  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
18|counterparty  | thread '<unnamed>' panicked at src/b58.rs:19:10:
18|counterparty  | bad: NoChecksum
18|counterparty  | thread '<unnamed>' panicked at src/b58.rs:19:10:
18|counterparty  | bad: NoChecksum
18|counterparty  | thread '<unnamed>' panicked at src/b58.rs:19:10:
18|counterparty  | bad: NoChecksum
18|counterparty  | WARNING:root:Error composing send transaction via API: invalid public key: 
18|counterparty  | WARNING:root:Traceback (most recent call last):
18|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/api.py", line 649, in create_method
18|counterparty  |     return compose_transaction(self.db, name=tx, params=transaction_args, **common_args)
18|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/api.py", line 466, in compose_transaction
18|counterparty  |     raise script.AddressError(f'invalid public key: {pubkey}')
18|counterparty  | counterpartylib.lib.script.AddressError: invalid public key: 
```
```
16|counterparty  | [2024-04-14 19:07:09][WARNING] Invalid subasset None
16|counterparty  | ERROR:root:SQLITE_LOG: near ")": syntax error in "SELECT * FROM addresses WHERE ()" (1) SQLITE_ERROR
16|counterparty  | thread '<unnamed>' panicked at src/b58.rs:19:10:
16|counterparty  | bad: InvalidCharacter { character: 'l', index: 39 }
16|counterparty  | thread '<unnamed>' panicked at src/b58.rs:19:10:
16|counterparty  | bad: InvalidCharacter { character: 'l', index: 39 }
```

**Comment by warrenpuffett** [comment]
This is coming from here:

```
#[pyfunction]
fn b58_decode<'p>(py: Python<'p>, encoded: &str) -> &'p PyBytes {
    let s = bs58::decode(encoded)
        .with_check(None)
        .into_vec()
        .expect("bad");
    PyBytes::new(py, &s)
```

`expect` takes a `Result<T, E>` and panics if the `Result` resolves to an `E`. There's a few things we can do here. If we want to maintain the type signature:

```
fn b58_decode<'p>(py: Python<'p>, encoded: &str) -> &'p PyBytes
```

Then we have to keep this expect or simply swallow the errors and return essentially an empty string. Our other option would be to change the type signature to something like:

```
... -> PyResult<&'p PyBytes>
```

Which would produce a python exception instead of a rust panic. But we'd need to make sure the python call sites properly handle this exception.

**Comment by adamkrellenstein** [comment]
Sounds like the latter is the better option.

**Comment by ouziel-slama** [comment]
yeah agreed!

**Comment by ouziel-slama** [comment]
@warrenpuffett done here https://github.com/CounterpartyXCP/counterparty-core/pull/1694
Could you please review (done with chatgpt help :)) ?
