### ISSUE TITLE
Reparse hangs at the end

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1646]
Reparse done correctly but need a ctrl-c at the end

```
[OK] Block 838866 parsed in 0.710s [2867/2867 blocks parsed - 0:36:04/0:36:04 (0:00:00)]
All blocks reparsed in 2165.00s

^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
  File "/home/tower/counterparty/counterparty-core/counterparty-lib/counterpartylib/server.py", line 70, in sigterm_handler
    sys.exit(0)
SystemExit: 0
```

**Comment by ouziel-slama** [comment]
Fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1662
