### ISSUE TITLE
AddrIndexRs Communication Issue

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1659]
Getting a *ton* of this:
```
13|counterparty  | counterpartylib.lib.exceptions.BalanceError: Insufficient BTC at address 1Q8f3efUeUCxhwtU1yJGiXuwbMFxGz9sjd. (Need approximately 7.68e-05 BTC.)
13|counterparty  | [2024-04-14 10:57:13][ERROR] `localhost:8432` -- Timeout receiving message: timed out
13|counterparty  | Traceback (most recent call last):
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
13|counterparty  |     chunk = self.socket.recv(buffer_size)
13|counterparty  | TimeoutError: timed out
13|counterparty  | [2024-04-14 10:57:13][ERROR] AddrIndexRsClient.thread -- exception timed out
13|counterparty  | Traceback (most recent call last):
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 538, in _run
13|counterparty  |     res = self.socket_manager.recv()
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 422, in recv
13|counterparty  |     raise e
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
13|counterparty  |     chunk = self.socket.recv(buffer_size)
13|counterparty  | TimeoutError: timed out
13|counterparty  | [2024-04-14 10:57:27][ERROR] `localhost:8432` -- Timeout receiving message: timed out
13|counterparty  | Traceback (most recent call last):
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
13|counterparty  |     chunk = self.socket.recv(buffer_size)
13|counterparty  | TimeoutError: timed out
13|counterparty  | [2024-04-14 10:57:27][ERROR] AddrIndexRsClient.thread -- exception timed out
13|counterparty  | Traceback (most recent call last):
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 538, in _run
13|counterparty  |     res = self.socket_manager.recv()
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 422, in recv
13|counterparty  |     raise e
13|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
13|counterparty  |     chunk = self.socket.recv(buffer_size)
13|counterparty  | TimeoutError: timed out
13|counterparty  | [2024-04-14 10:57:52][INFO] Block: 839168 (225.37, hashes: L:06110 / TX:85520 / M:9e3f9)
```

and this:

```
13|counterparty  | [2024-04-14 11:01:59][ERROR] Key error in addrindexrs still exists!!!!!
13|counterparty  | [2024-04-14 11:01:59][WARNING] tx missing in rawtx cache: '692c6693aa4ee3787ece043700bcfc539877c310cf7e5c57751612738a455be5' -- txhash_list size: 20000, hash: 5d1411dbcf412ff2ce26f613025489e0 / raw_transactions_cache size: 20000 / # rpc_batch calls: 20000 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
13|counterparty  | [2024-04-14 11:01:59][ERROR] Key error in addrindexrs still exists!!!!!
13|counterparty  | [2024-04-14 11:01:59][WARNING] tx missing in rawtx cache: '46470c3739614f1614125815c96fe8301d1f6abad181337a81c289c2c24cab2b' -- txhash_list size: 20000, hash: 5d1411dbcf412ff2ce26f613025489e0 / raw_transactions_cache size: 20000 / # rpc_batch calls: 20000 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
```

And nodes are falling behind more often? Sometimes getting stuck?
Is something wrong?

**Comment by adamkrellenstein** [comment]
```
20|counterparty  | Traceback (most recent call last):
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
20|counterparty  |     chunk = self.socket.recv(buffer_size)
20|counterparty  | TimeoutError: timed out
20|counterparty  | [2024-04-14 14:06:53][ERROR] AddrIndexRsClient.thread -- exception timed out
20|counterparty  | Traceback (most recent call last):
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 538, in _run
20|counterparty  |     res = self.socket_manager.recv()
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 422, in recv
20|counterparty  |     raise e
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
20|counterparty  |     chunk = self.socket.recv(buffer_size)
20|counterparty  | TimeoutError: timed out
20|counterparty  | [2024-04-14 14:07:53][ERROR] `localhost:8432` -- Timeout receiving message: timed out
20|counterparty  | Traceback (most recent call last):
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
20|counterparty  |     chunk = self.socket.recv(buffer_size)
20|counterparty  | TimeoutError: timed out
20|counterparty  | [2024-04-14 14:07:53][ERROR] AddrIndexRsClient.thread -- exception timed out
20|counterparty  | Traceback (most recent call last):
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 538, in _run
20|counterparty  |     res = self.socket_manager.recv()
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 422, in recv
20|counterparty  |     raise e
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
20|counterparty  |     chunk = self.socket.recv(buffer_size)
20|counterparty  | TimeoutError: timed out



20|counterparty  | [2024-04-14 14:08:03][ERROR] `localhost:8432` -- Timeout receiving message: timed out
20|counterparty  | Traceback (most recent call last):
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
20|counterparty  |     chunk = self.socket.recv(buffer_size)
20|counterparty  | TimeoutError: timed out
20|counterparty  | [2024-04-14 14:08:03][ERROR] AddrIndexRsClient.thread -- exception timed out
20|counterparty  | Traceback (most recent call last):
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 538, in _run
20|counterparty  |     res = self.socket_manager.recv()
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 422, in recv
20|counterparty  |     raise e
20|counterparty  |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 405, in recv
20|counterparty  |     chunk = self.socket.recv(buffer_size)
20|counterparty  | TimeoutError: timed out
```

```
Every 2.0s: http POST http://rpc:rpc@api4.counterparty.io:4000/api/ jsonrpc="2.0" id=1 method="get_running_info"                 tang.local: Sun Apr 14 16:08:33 2024

{"result": {"server_ready": false, "db_caught_up": false, "bitcoin_block_count": 839199, "last_block": {"block_index": 839197, "block_hash": "00000000000000000001c13
afb0ebc892751dc5d685c23c7550ad28bd9982f29", "block_time": 1713103201, "previous_block_hash": "000000000000000000020920fa8290b8cd630ce4bd95887dae0ad8e972746e18", "dif
ficulty": 86388558925171.02, "ledger_hash": "18e312ad4ed4e9d1212efda438c4d7043cd5c0e5b63eedabae22ef4740714ea2", "txlist_hash": "01621f98d4c643bf3da79a0fb87fad0035efa
29dfee80adca4786d125ede202c", "messages_hash": "54975f04ef1cd9813114b45fdfb1069874df886332d6f0ae0ded427c14d40097"}, "indexd_caught_up": true, "indexd_blocks_behind":
 0, "last_message_index": 13636689, "api_limit_rows": 1000, "running_testnet": false, "running_regtest": false, "running_testcoin": false, "version_major": 10, "vers
ion_minor": 1, "version_revision": 0}, "id": "1", "jsonrpc": "2.0"}
```

**Comment by adamkrellenstein** [comment]
Timeout error was fixed with an increased timeout. Splitting off other issue here: https://github.com/CounterpartyXCP/counterparty-core/issues/1663
