### ISSUE TITLE
Consensus Errors on Testnet

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1703]
```
30|counter | counterpartylib.lib.check.ConsensusError: Empty previous txlist_hash for block 2587415. Please launch a `rollback`.
30|counter | Traceback (most recent call last):
30|counter |   File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
30|counter |     sys.exit(server.main())
30|counter |   File "/home/adam/counterparty-core/counterparty-core/counterpartycore/server.py", line 444, in main
30|counter |     server.start_all(catch_up=args.catch_up)
30|counter |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/server.py", line 631, in start_all
30|counter |     blocks.follow(db)
30|counter |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 1038, in follow
30|counter |     parse_block(db, block_index, block_time)
30|counter |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/blocks.py", line 291, in parse_block
30|counter |     new_txlist_hash, found_txlist_hash = check.consensus_hash(
30|counter |   File "/home/adam/counterparty-core/counterparty-lib/counterpartylib/lib/check.py", line 826, in consensus_hash
30|counter |     raise ConsensusError(
30|counter | counterpartylib.lib.check.ConsensusError: Empty previous txlist_hash for block 2587415. Please launch a `rollback`.
```

**Comment by adamkrellenstein** [comment]
Fixed here: https://github.com/CounterpartyXCP/counterparty-core/pull/1704/files

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterparty-core/issues/2167
