### ISSUE TITLE
Fix circular imports

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1724]
when trying to import modules inside lib from a tool script:
```
Traceback (most recent call last):
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/tools/genapidoc.py", line 1, in <module>
    from counterpartycore.lib.api.routes import ROUTES
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/routes.py", line 1, in <module>
    from counterpartycore.lib import (
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/transaction.py", line 20, in <module>
    from counterpartycore.lib import (
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 10, in <module>
    from counterpartycore.lib.kickstart.blocks_parser import BlockchainParser
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/kickstart/__init__.py", line 13, in <module>
    from counterpartycore import server
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/server.py", line 21, in <module>
    from counterpartycore.lib import (
  File "/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 42, in <module>
    from counterpartycore.lib.gettxinfo import get_tx_info  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'get_tx_info' from partially initialized module 'counterpartycore.lib.gettxinfo' (most likely due to a circular import) (/Users/ouzielslama/Work/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py)
```

**Comment by ouziel-slama** [comment]
done
