### ISSUE TITLE
`ctrl-c` is broken

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#1743]
hangs at "[2024-04-28 20:17:11][INFO] Stopping API Status Poller..."
after 2 more "ctrl-c":
```
^C[2024-04-28 20:17:38][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 332, in _bootstrap
    threading._shutdown()
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt
Unhandled Exception
[2024-04-28 20:17:38][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/tower/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/home/tower/counterparty/counterparty-core/counterparty-core/counterpartycore/cli.py", line 445, in main
    server.start_all(args)
  File "/home/tower/counterparty/counterparty-core/counterparty-core/counterpartycore/server.py", line 731, in start_all
    api_status_poller.stop()
  File "/home/tower/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 502, in stop
    time.sleep(0.1)
KeyboardInterrupt
Unhandled Exception
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tower/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/home/tower/counterparty/counterparty-core/counterparty-core/counterpartycore/cli.py", line 445, in main
    server.start_all(args)
  File "/home/tower/counterparty/counterparty-core/counterparty-core/counterpartycore/server.py", line 731, in start_all
    api_status_poller.stop()
  File "/home/tower/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 502, in stop
    time.sleep(0.1)
KeyboardInterrupt
  File "/usr/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 332, in _bootstrap
    threading._shutdown()
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/1748
