### ISSUE TITLE
Non-Graceful Shutdown

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1855]
```
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535560
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535560 - Order cancelled VACUS / XCP (9c53923) [expired]
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535560 - Order cancelled A2161830940746832633 / XCP (8cc4d0a) [expired]
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535560 - Order cancelled OJISANPEPE / PEPECASH (2608542) [cancelled]
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535560 - Cancel Order 2608542 (9a12296) [valid]
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535560 - Parsing Complete. L: fe3cd24, TX: 7bd7d42, M: 9871ab9 (0.03s)
2024-06-02-T09:45:39+0200 - [    INFO] - Block 535561
^C2024-06-02-T09:45:39+0200 - [ WARNING] - Keyboard interrupt.
2024-06-02-T09:45:39+0200 - [    INFO] - Stopping telemetry daemon...
2024-06-02-T09:45:39+0200 - [    INFO] - Stopping API Status Poller...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 523, in run
    api_util.check_last_parsed_block(self.db, backend.bitcoind.getblockcount())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/util.py", line 20, in check_last_parsed_block
    last_block = ledger.get_last_block(db)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/ledger.py", line 999, in get_last_block
    cursor = db.cursor()
             ^^^^^^^^^^^
apsw.ConnectionClosedError: The connection has been closed
2024-06-02-T09:45:40+0200 - [    INFO] - Stopping API Server v1...
2024-06-02-T09:45:40+0200 - [    INFO] - Stopping API server...
```

**Comment by ouziel-slama** [comment]
@adamkrellenstein  didn't manage to reproduce on my computer but should be fixed by https://github.com/CounterpartyXCP/counterparty-core/pull/1856/commits/1837a287238b2628e7c138500982d2873f497c55
