### ISSUE TITLE
Fetcher Crash

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1937]
```
~ > counterparty-server --indexd-port=8432 --database-file=/Users/adam/Library/Application\ Support/Bitcoin/counterparty.db start

Counterparty Core v10.2.0
Verbosity: 0
Quiet: False
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/Bitcoin/counterparty.db
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-06-14T16:52:30.053515000+02:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-06-14T16:52:30.065140000+02:00 - [    INFO] - Running PRAGMA optimize...
2024-06-14T16:52:31.498149000+02:00 - [    INFO] - Telemetry enabled.
2024-06-14T16:52:31.508764000+02:00 - [    INFO] - Starting API Server v1...
2024-06-14T14:52:31.673092Z  INFO counterparty_rs::indexer::handlers::new: Indexer initializing...
2024-06-14T14:52:31.674482Z  INFO counterparty_rs::indexer::workers: 12 BitcoinClient workers started
2024-06-14T14:52:31.674529Z  INFO counterparty_rs::indexer::handlers::new: Connecting to database: /Users/adam/Library/Application Support/Bitcoin/fetcherdb
2024-06-14T14:52:31.757294Z  INFO counterparty_rs::indexer::handlers::new: Connected
2024-06-14T14:52:31.757314Z  INFO counterparty_rs::indexer::handlers::new: Initialized
2024-06-14T16:52:31.757362000+02:00 - [   ERROR] - Failed to initialize fetcher: 'builtins.Indexer' object has no attribute 'get_version'. Retrying in 5 seconds...
2024-06-14T16:52:31.791813000+02:00 - [    INFO] - Starting API Server.
2024-06-14T16:52:36.762736000+02:00 - [    INFO] - Stopping API Server...
2024-06-14T16:52:37.271522000+02:00 - [    INFO] - Stopping telemetry daemon...
2024-06-14T16:52:37.565623000+02:00 - [    INFO] - Stopping API Status Poller...
2024-06-14T16:52:37.624926000+02:00 - [    INFO] - Stopping API Server v1...
2024-06-14T16:52:38.029351000+02:00 - [    INFO] - Closing database connections...
2024-06-14T16:52:38.030975000+02:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-06-14T16:52:38.031147000+02:00 - [    INFO] - Shutting down logging...
2024-06-14T14:52:38.031450Z  INFO counterparty_rs::indexer::handlers::stop: Stopping
2024-06-14T14:52:38.031630Z  INFO counterparty_rs::indexer::workers: 1 Consumer workers started
2024-06-14T14:52:38.031748Z  INFO counterparty_rs::indexer::workers: BitcoinClient-9 worker exited
2024-06-14T14:52:38.031739Z  INFO counterparty_rs::indexer::workers: BitcoinClient-1 worker exited
2024-06-14T14:52:38.031777Z  INFO counterparty_rs::indexer::workers: BitcoinClient-7 worker exited
2024-06-14T14:52:38.031796Z  INFO counterparty_rs::indexer::workers: BitcoinClient-8 worker exited
2024-06-14T14:52:38.031766Z  INFO counterparty_rs::indexer::workers: BitcoinClient-2 worker exited
2024-06-14T14:52:38.031731Z  INFO counterparty_rs::indexer::workers: BitcoinClient-0 worker exited
2024-06-14T14:52:38.031762Z  INFO counterparty_rs::indexer::workers: BitcoinClient-10 worker exited
2024-06-14T14:52:38.031748Z  INFO counterparty_rs::indexer::workers: BitcoinClient-11 worker exited
2024-06-14T14:52:38.031779Z  INFO counterparty_rs::indexer::workers: BitcoinClient-4 worker exited
2024-06-14T14:52:38.031787Z  INFO counterparty_rs::indexer::workers: BitcoinClient-6 worker exited
2024-06-14T14:52:38.031755Z  INFO counterparty_rs::indexer::workers: BitcoinClient-3 worker exited
2024-06-14T14:52:38.031761Z  INFO counterparty_rs::indexer::workers: BitcoinClient-5 worker exited
2024-06-14T14:52:38.032096Z  INFO counterparty_rs::indexer::workers: Consumer-0 worker exited
2024-06-14T14:52:38.032128Z  INFO counterparty_rs::indexer::handlers::stop: Stopped
2024-06-14T16:52:38.032179000+02:00 - [    INFO] - Shutdown complete.
2024-06-14T16:52:38.032400000+02:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/fetcher.py", line 33, in initialize
    fetcher_version = _fetcher.get_version()
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtins.Indexer' object has no attribute 'get_version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 464, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 728, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1186, in catch_up
    fetcher.initialize(util.CURRENT_BLOCK_INDEX + 1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/fetcher.py", line 51, in initialize
    initialize(start_height)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/fetcher.py", line 17, in initialize
    raise Exception("Fetcher has already been initialized.")
Exception: Fetcher has already been initialized.
Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/fetcher.py", line 33, in initialize
    fetcher_version = _fetcher.get_version()
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'builtins.Indexer' object has no attribute 'get_version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 464, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 728, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1186, in catch_up
    fetcher.initialize(util.CURRENT_BLOCK_INDEX + 1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/fetcher.py", line 51, in initialize
    initialize(start_height)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/fetcher.py", line 17, in initialize
    raise Exception("Fetcher has already been initialized.")
Exception: Fetcher has already been initialized.
adam@tang ~ > 
```

**Comment by adamkrellenstein** [comment]
happening again on restart

**Comment by ouziel-slama** [comment]
has counterparty-rs been recompiled?
