### ISSUE TITLE
Break on Early Keyboard Interrupt

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1968]
```
------------------------------ START ------------------------------

2024-06-26T08:59:13.498548000+02:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-06-26T08:59:13.523012000+02:00 - [    INFO] - Running PRAGMA optimize...
2024-06-26T08:59:16.077064000+02:00 - [    INFO] - Starting API Server.
^C2024-06-26T09:00:06.704614000+02:00 - [ WARNING] - Keyboard interrupt!
2024-06-26T09:00:06.705869000+02:00 - [    INFO] - Stopping API Server...
2024-06-26T09:00:08.726330000+02:00 - [   ERROR] - API Server did not stop in time. Terminating...
2024-06-26T09:00:08.726879000+02:00 - [    INFO] - Closing database connections...
2024-06-26T09:00:08.733957000+02:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-06-26T09:00:08.734260000+02:00 - [    INFO] - Shutting down logging...
2024-06-26T09:00:08.735035+02:00 - [    INFO] - RS Fetcher - Indexer initializing...
2024-06-26T09:00:08.735679+02:00 - [    INFO] - RS Fetcher - Connecting to database: /Users/adam/Library/Application Support/Bitcoin/fetcherdb
2024-06-26T09:00:08.954246+02:00 - [    INFO] - RS Fetcher - Connected
2024-06-26T09:00:08.954290+02:00 - [    INFO] - RS Fetcher - Initialized
2024-06-26T09:00:08.954346+02:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight...
2024-06-26T09:00:08.954406+02:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight took 26.75µs
2024-06-26T09:00:08.954707+02:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight...
2024-06-26T09:00:08.954959+02:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight took 230.458µs
2024-06-26T09:00:08.955026000+02:00 - [   ERROR] - Failed to initialize fetcher: RPC error: JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 61). Retrying in 5 seconds...
^C2024-06-26T09:00:11.084072000+02:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 57, in start
    self.fetcher.start()
Exception: RPC error: JSON-RPC error: transport error: Couldn't connect to host: Connection refused (os error 61)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 464, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 752, in start_all
    rsfetcher.RSFetcher().stop()
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/util.py", line 550, in __call__
    instance = super().__call__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 34, in __init__
    self.start()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 60, in start
    time.sleep(5)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 54, in handle_interrupt_signal
    raise KeyboardInterrupt(f"Received signal {signal.strsignal(signum)}")
KeyboardInterrupt: Received signal Interrupt: 2
```

**Comment by adamkrellenstein** [comment]
I *think* we should be able to detect it when Bitcoin Core is fully missing because the TCP port won't be open.

**Comment by adamkrellenstein** [comment]
Dependent on #1960
