### ISSUE TITLE
Fatal Crash when Catching Up

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#1988]
```
2024-07-01T20:18:45.126209000+02:00 - [    INFO] - Block 333499 - Send XCP from 1NjgRccf to 1GRPbfg8 (400fd53) [valid]
2024-07-01T20:18:45.137829000+02:00 - [    INFO] - Block 333499 - Send LTBCOIN from 1ChZNk7v to 1NF6DE9y (130da81) [valid]
2024-07-01T20:18:45.140633000+02:00 - [    INFO] - Block 333499 - Order opened for 22958842 XBTC at 18dDP1rt (09af5db) [open]
2024-07-01T20:18:45.163902000+02:00 - [    INFO] - Block 333499 - Order match for 7652947320 XCP against 22958842 XBTC (32955a8_09af5db) [completed]
2024-07-01T20:18:45.164329000+02:00 - [    INFO] - Block 333499 - Parsing complete. L: 0400319, TX: 9ca3b27, M: 82290d7 (0.08s)
2024-07-01T20:18:45.173196000+02:00 - [    INFO] - Block 333500
2024-07-01T20:18:45.173962000+02:00 - [    INFO] - Stopping API Server...
2024-07-01T20:18:45.679402000+02:00 - [    INFO] - Stopping telemetry daemon...
2024-07-01T20:18:46.117191000+02:00 - [    INFO] - Stopping API Status Poller...
2024-07-01T20:18:46.616269000+02:00 - [    INFO] - Stopping API Server v1...
2024-07-01T20:18:47.023247000+02:00 - [    INFO] - Closing database connections...
2024-07-01T20:18:47.104073000+02:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-07-01T20:18:47.104249000+02:00 - [    INFO] - Shutting down logging...
2024-07-01T20:18:47.111097+02:00 - [   ERROR] - RS Fetcher - Fetcher-1 worker exited with error: Stopped error
2024-07-01T20:18:47.111076+02:00 - [   ERROR] - RS Fetcher - Fetcher-2 worker exited with error: Stopped error
2024-07-01T20:18:47.111120+02:00 - [   ERROR] - RS Fetcher - Fetcher-4 worker exited with error: Stopped error
2024-07-01T20:18:47.116189+02:00 - [   ERROR] - RS Fetcher - Fetcher-3 worker exited with error: Stopped error
2024-07-01T20:18:47.313698000+02:00 - [    INFO] - Shutdown complete.
2024-07-01T20:18:47.314069000+02:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 465, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 728, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1199, in catch_up
    tx_index = parse_new_block(db, decoded_block, block_parser=None, tx_index=tx_index)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1113, in parse_new_block
    tx_index = list_tx(
               ^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 841, in list_tx
    source, destination, btc_amount, fee, data, dispensers_outs = get_tx_info(
                                                                  ^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 538, in get_tx_info
    return _get_tx_info(db, decoded_tx, block_index, block_parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 525, in _get_tx_info
    return get_tx_info_new(
           ^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 361, in get_tx_info_new
    destinations, btc_amount, fee, data, potential_dispensers = decoded_tx["parsed_vouts"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable Exception object
Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 465, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 728, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1199, in catch_up
    tx_index = parse_new_block(db, decoded_block, block_parser=None, tx_index=tx_index)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1113, in parse_new_block
    tx_index = list_tx(
               ^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 841, in list_tx
    source, destination, btc_amount, fee, data, dispensers_outs = get_tx_info(
                                                                  ^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 538, in get_tx_info
    return _get_tx_info(db, decoded_tx, block_index, block_parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 525, in _get_tx_info
    return get_tx_info_new(
           ^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/gettxinfo.py", line 361, in get_tx_info_new
    destinations, btc_amount, fee, data, potential_dispensers = decoded_tx["parsed_vouts"]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable Exception object
adam@tang ~/D/w/C/C/counterparty-core (develop=) > 
```

**Comment by adamkrellenstein** [comment]
Fixed by recompiling the rust module
