### ISSUE TITLE
SSL Handshakes at Startup

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#1989]
When trying to spin up a new node using docker, I get the following in my logs. I think it's related to ssl handshakes and redirects.

For example, PROTOCOL_CHANGES_URL = "https://counterparty.io/protocol_changes.json" but that 301s to https://counterpartyxcp.github.io/counterparty-lib/counterpartylib/protocol_changes.json.

https://github.com/CounterpartyXCP/counterparty-core/blob/03192939ccaea8cd81d8ba60f8e1c6cc648060e1/counterparty-core/counterpartycore/lib/check.py#L958-L960

**docker compose --profile mainnet logs --tail=10 -f counterparty-core**
```
counterparty-core-1  | Quiet: False
counterparty-core-1  | Configuration File: /root/.config/counterparty/server.conf
counterparty-core-1  | Counterparty Database: /data/counterparty/counterparty.db
counterparty-core-1  | Server Log: /root/.cache/counterparty/log/server.log
counterparty-core-1  | API Access Log: /root/.cache/counterparty/log/server.access.log
counterparty-core-1  |
counterparty-core-1  | ------------------------------ START ------------------------------
counterparty-core-1  |
counterparty-core-1  | 2024-07-01T19:32:48.324223000+00:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
counterparty-core-1  | 2024-07-01T19:32:48.334169000+00:00 - [    INFO] - Running PRAGMA optimize...
counterparty-core-1  | 2024-07-01T19:32:58.736368000+00:00 - [    INFO] - Closing database connections...
counterparty-core-1  | 2024-07-01T19:32:58.738818000+00:00 - [    INFO] - Stopping AddrIndexRs thread...
counterparty-core-1  | 2024-07-01T19:32:58.739032000+00:00 - [    INFO] - Shutting down logging...
counterparty-core-1  | 2024-07-01T19:32:58.739340000+00:00 - [    INFO] - Stopping fetcher...
counterparty-core-1  | 2024-07-01T19:32:58.739611000+00:00 - [    INFO] - Shutdown complete.
counterparty-core-1  | 2024-07-01T19:32:58.739817000+00:00 - [   ERROR] - Unhandled Exception
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
counterparty-core-1  |     self._validate_conn(conn)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
counterparty-core-1  |     conn.connect()
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 653, in connect
counterparty-core-1  |     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
counterparty-core-1  | Unhandled Exception
counterparty-core-1  |     ssl_sock = ssl_wrap_socket(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
counterparty-core-1  |     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
counterparty-core-1  |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
counterparty-core-1  |   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
counterparty-core-1  |     return self.sslsocket_class._create(
counterparty-core-1  |   File "/usr/lib/python3.10/ssl.py", line 1100, in _create
counterparty-core-1  |     self.do_handshake()
counterparty-core-1  |   File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
counterparty-core-1  |     self._sslobj.do_handshake()
counterparty-core-1  | TimeoutError: _ssl.c:990: The handshake operation timed out
counterparty-core-1  |
counterparty-core-1  | The above exception was the direct cause of the following exception:
counterparty-core-1  |
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 564, in send
counterparty-core-1  |     resp = conn.urlopen(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
counterparty-core-1  |     retries = retries.increment(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 470, in increment
counterparty-core-1  |     raise reraise(type(error), error, _stacktrace)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/util.py", line 39, in reraise
counterparty-core-1  |     raise value
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
counterparty-core-1  |     response = self._make_request(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
counterparty-core-1  |     raise new_e
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 469, in _make_request
counterparty-core-1  |     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
counterparty-core-1  |     raise ReadTimeoutError(
counterparty-core-1  | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='counterpartyxcp.github.io', port=443): Read timed out. (read timeout=10)
counterparty-core-1  |
counterparty-core-1  | During handling of the above exception, another exception occurred:
counterparty-core-1  |
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/bin/counterparty-server", line 8, in <module>
counterparty-core-1  |     sys.exit(cli.main())
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/cli.py", line 464, in main
counterparty-core-1  |     server.start_all(args)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 701, in start_all
counterparty-core-1  |     check.software_version()
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/check.py", line 958, in software_version
counterparty-core-1  |     response = requests.get(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
counterparty-core-1  |     return request("get", url, params=params, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
counterparty-core-1  |     return session.request(method=method, url=url, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
counterparty-core-1  |     resp = self.send(prep, **send_kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 724, in send
counterparty-core-1  |     history = [resp for resp in gen]
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 724, in <listcomp>
counterparty-core-1  |     history = [resp for resp in gen]
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 265, in resolve_redirects
counterparty-core-1  |     resp = self.send(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
counterparty-core-1  |     r = adapter.send(request, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 610, in send
counterparty-core-1  |     raise ReadTimeout(e, request=request)
counterparty-core-1  | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='counterpartyxcp.github.io', port=443): Read timed out. (read timeout=10)
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
counterparty-core-1  |     self._validate_conn(conn)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
counterparty-core-1  |     conn.connect()
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 653, in connect
counterparty-core-1  |     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
counterparty-core-1  |     ssl_sock = ssl_wrap_socket(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
counterparty-core-1  |     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
counterparty-core-1  |     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
counterparty-core-1  |   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
counterparty-core-1  |     return self.sslsocket_class._create(
counterparty-core-1  |   File "/usr/lib/python3.10/ssl.py", line 1100, in _create
counterparty-core-1  |     self.do_handshake()
counterparty-core-1  |   File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
counterparty-core-1  |     self._sslobj.do_handshake()
counterparty-core-1  | TimeoutError: _ssl.c:990: The handshake operation timed out
counterparty-core-1  |
counterparty-core-1  | The above exception was the direct cause of the following exception:
counterparty-core-1  |
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 564, in send
counterparty-core-1  |     resp = conn.urlopen(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
counterparty-core-1  |     retries = retries.increment(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 470, in increment
counterparty-core-1  |     raise reraise(type(error), error, _stacktrace)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/util.py", line 39, in reraise
counterparty-core-1  |     raise value
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
counterparty-core-1  |     response = self._make_request(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
counterparty-core-1  |     raise new_e
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 469, in _make_request
counterparty-core-1  |     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
counterparty-core-1  |     raise ReadTimeoutError(
counterparty-core-1  | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='counterpartyxcp.github.io', port=443): Read timed out. (read timeout=10)
counterparty-core-1  |
counterparty-core-1  | During handling of the above exception, another exception occurred:
counterparty-core-1  |
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/bin/counterparty-server", line 8, in <module>
counterparty-core-1  |     sys.exit(cli.main())
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/cli.py", line 464, in main
counterparty-core-1  |     server.start_all(args)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 701, in start_all
counterparty-core-1  |     check.software_version()
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/check.py", line 958, in software_version
counterparty-core-1  |     response = requests.get(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
counterparty-core-1  |     return request("get", url, params=params, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
counterparty-core-1  |     return session.request(method=method, url=url, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
counterparty-core-1  |     resp = self.send(prep, **send_kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 724, in send
counterparty-core-1  |     history = [resp for resp in gen]
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 724, in <listcomp>
counterparty-core-1  |     history = [resp for resp in gen]
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 265, in resolve_redirects
counterparty-core-1  |     resp = self.send(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
counterparty-core-1  |     r = adapter.send(request, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 610, in send
counterparty-core-1  |     raise ReadTimeout(e, request=request)
counterparty-core-1  | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='counterpartyxcp.github.io', port=443): Read timed out. (read timeout=10)
counterparty-core-1 exited with code 0

```

**Comment by droplister** [comment]
My node appears to eventually get past this after multiple tries, but my guess would be that the redirect sometimes results in the timeout being reached. Increase timeout to solve?

**Comment by adamkrellenstein** [comment]
Yeah, we should also be catching that exception explicitly.

**Comment by droplister** [comment]
Or reference the source controlled protocol changes rather than a server:
https://github.com/CounterpartyXCP/counterparty-core/blob/master/counterparty-core/counterpartycore/protocol_changes.json

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterparty-core/pull/1997/commits/c87726513d696447559f9f53dd03e9ed1ea61df2

**Comment by adamkrellenstein** [comment]
fixed?

**Comment by ouziel-slama** [comment]
yep!
