### ISSUE TITLE
'Spinner' object has no attribute 'set_message'

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2009]
When running counterparty-server kickstart, I get this error immediately related to the Spinner. It went away on a second try.

**counterparty-server kickstart --bitcoind-dir=/home/user/snap/bitcoin-core/common/.bitcoin**
```
Counterparty Core v10.2.0
Verbosity: 0
Quiet: False
Configuration File: /home/user/.config/counterparty/server.conf
Counterparty Database: /home/user/.local/share/counterparty/counterparty.db
Server Log: /home/user/.cache/counterparty/log/server.log
API Access Log: /home/ user/.cache/counterparty/log/server.access.log

------------------------------ KICKSTART ------------------------------

Warnings:
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N): y
[OK] Getting last known block hash... (in 0.45s)
[OK] Checking database state... (in 0.01s)
[OK] Initialising database... (in 0.08s)
Unhandled Exception
Traceback (most recent call last):
  File "/home/ user/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/home/ user/.local/lib/python3.10/site-packages/counterpartycore/cli.py", line 456, in main
    server.kickstart(
  File "/home/ user/.local/lib/python3.10/site-packages/counterpartycore/server.py", line 786, in kickstart
    kickstarter.run(
  File "/home/ user/.local/lib/python3.10/site-packages/counterpartycore/lib/kickstart/__init__.py", line 331, in run
    kickstart_db, block_count, tx_index, last_parsed_block = intialize_kickstart_db(
  File "/home/ user/.local/lib/python3.10/site-packages/counterpartycore/lib/kickstart/__init__.py", line 183, in intialize_kickstart_db
    fetch_blocks(cursor, bitcoind_dir, last_known_hash, first_block, spinner)
  File "/home/ user/.local/lib/python3.10/site-packages/counterpartycore/lib/kickstart/__init__.py", line 83, in fetch_blocks
    spinner.set_message(
AttributeError: 'Spinner' object has no attribute 'set_message'
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt:

```

However, when I try running the command a second time, it works without errror.

```
Counterparty Core v10.2.0
Verbosity: 0
Quiet: False
Configuration File: /home/ user/.config/counterparty/server.conf
Counterparty Database: /home/ user/.local/share/counterparty/counterparty.db
Server Log: /home/ user/.cache/counterparty/log/server.log
API Access Log: /home/ user/.cache/counterparty/log/server.access.log

------------------------------ KICKSTART ------------------------------

Warnings:
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N): y
[OK] Getting last known block hash... (in 0.02s)
[OK] Checking database state... (in 0.00s)
[OK] Backing up database... (in 0.00s)
[OK] Initialising database... (in 0.01s)
[OK] Starting blocks parser from block 278269... (in 0.21s)
[==  ] Block 278333 parsed in 0.06s [64/572374 blocks parsed - tx_index: 0 - 0:00:09/23:55:39 (23:55:30)]
```

I'm setting up two nodes and ran into this on both of them. Error first time, not encountered on second run.

**Comment by adamkrellenstein** [comment]
So we've removed `kickstart` in the latest version (v10.3.0-rc.1) but we should check to see if this is a problem for other operations that use the spinner.

**Comment by adamkrellenstein** [comment]
See also https://gist.github.com/droplister/2c4d45341a7e358201455cc37e0b4dfc

**Comment by ouziel-slama** [comment]
`kickstart` is dead and no problem with other spinners.
