### ISSUE TITLE
yoyo.exceptions.LockTimeout

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2010]
when starting dev mainnet server with `v10.3.0-rc.1`

```
File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_server.py", line 376, in run_api_server
    watcher = api_watcher.APIWatcher()
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_watcher.py", line 548, in __init__
    apply_migration()
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_watcher.py", line 483, in apply_migration
    with backend.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 324, in lock
    self._insert_lock_row(pid, timeout)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 350, in _insert_lock_row
    raise exceptions.LockTimeout(
yoyo.exceptions.LockTimeout: Process 33 has locked this database (run yoyo break-lock to remove this lock)
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2007

**Comment by adamkrellenstein** [comment]
Any idea?

```
$ docker logs --follow c29074450196

Counterparty Core v10.3.0-rc.1
Verbosity: 1
Quiet: False
Configuration File: /root/.config/counterparty/server.conf
Counterparty Database: /data/counterparty/counterparty.db
Network: `mainnet`
Bitcoin Core: http://rpc:*****@prd-btc-mainnet-h2rx:8332
AddrIndexRs: http://prd-btc-mainnet-h2rx:8432
Counterparty RPC Server: http://rpc:*****@0.0.0.0:4100/rpc/
Server Log: /root/.cache/counterparty/log/server.log
API Access Log: /root/.cache/counterparty/log/server.access.log

------------------------------ START ------------------------------

2024-07-05T16:34:04.675+00:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-07-05T16:34:04.677+00:00 - [   DEBUG] - Creating connection to `/data/counterparty/counterparty.db`...
2024-07-05T16:34:04.679+00:00 - [ WARNING] - Database WAL file detected. To ensure no data corruption has occurred, run `counterpary-server check-db`.
ERROR:root:SQLITE_LOG: recovered 1489 frames from WAL file /data/counterparty/counterparty.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
2024-07-05T16:34:04.685+00:00 - [   DEBUG] - Creating connection to `/data/counterparty/counterparty.db`...
2024-07-05T16:34:04.782+00:00 - [   DEBUG] - Checking database version...
2024-07-05T16:34:04.783+00:00 - [    INFO] - Running PRAGMA optimize...
2024-07-05T16:34:04.830+00:00 - [   DEBUG] - PRAGMA optimize completed.
2024-07-05T16:34:04.831+00:00 - [   DEBUG] - Checking Counterparty version...
2024-07-05T16:34:05.318+00:00 - [   DEBUG] - Version check passed.
2024-07-05T16:34:06.242+00:00 - [   DEBUG] - Initializing API Watcher...
2024-07-05T16:34:06.242+00:00 - [   DEBUG] - API Watcher - Applying migrations...
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 338, in _insert_lock_row
    self.execute(
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 388, in execute
    cursor.execute(sql, params)
sqlite3.IntegrityError: UNIQUE constraint failed: yoyo_lock.locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_server.py", line 375, in run_api_server
    watcher = api_watcher.APIWatcher()
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_watcher.py", line 556, in __init__
    apply_migration()
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_watcher.py", line 485, in apply_migration
    with backend.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 324, in lock
    self._insert_lock_row(pid, timeout)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 350, in _insert_lock_row
    raise exceptions.LockTimeout(
yoyo.exceptions.LockTimeout: Process 33 has locked this database (run yoyo break-lock to remove this lock)
 ^C
adam@dev-xcp-mainnet-develop-9ccp ~ $
```
```
root@c29074450196:/counterparty-core# yoyo break-lock --database sqlite:///data/counterparty/counterparty.api.db 
Traceback (most recent call last):
  File "/usr/local/bin/yoyo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/main.py", line 310, in main
    exitcode = args.func(args, config)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/migrate.py", line 329, in break_lock
    backend = get_backend(args, config)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/main.py", line 272, in get_backend
    return connections.get_backend(dburi, migration_table)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/connections.py", line 79, in get_backend
    backend = backend_class(parsed, migration_table)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 159, in __init__
    self._connection = self.connect(dburi)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/core/sqlite3.py", line 26, in connect
    conn = self.driver.connect(
sqlite3.OperationalError: unable to open database file
root@c29074450196:/counterparty-core# yoyo break-lock --database sqlite:///data/counterparty/counterparty.api.db 
Traceback (most recent call last):
  File "/usr/local/bin/yoyo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/main.py", line 310, in main
    exitcode = args.func(args, config)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/migrate.py", line 329, in break_lock
    backend = get_backend(args, config)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/main.py", line 272, in get_backend
    return connections.get_backend(dburi, migration_table)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/connections.py", line 79, in get_backend
    backend = backend_class(parsed, migration_table)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 159, in __init__
    self._connection = self.connect(dburi)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/core/sqlite3.py", line 26, in connect
    conn = self.driver.connect(
sqlite3.OperationalError: unable to open database file
root@c29074450196:/counterparty-core# yoyo break-lock --database sqlite:///data/counterparty/counterparty.db     
Traceback (most recent call last):
  File "/usr/local/bin/yoyo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/main.py", line 310, in main
    exitcode = args.func(args, config)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/migrate.py", line 329, in break_lock
    backend = get_backend(args, config)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/scripts/main.py", line 272, in get_backend
    return connections.get_backend(dburi, migration_table)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/connections.py", line 79, in get_backend
    backend = backend_class(parsed, migration_table)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/base.py", line 159, in __init__
    self._connection = self.connect(dburi)
  File "/usr/local/lib/python3.10/dist-packages/yoyo/backends/core/sqlite3.py", line 26, in connect
    conn = self.driver.connect(
sqlite3.OperationalError: unable to open database file
root@c29074450196:/counterparty-core# 
```

**Comment by ouziel-slama** [comment]
should be fixed with https://github.com/CounterpartyXCP/counterparty-core/pull/1997/commits/459522d59c878f15b8a946de11dc9d6dfca4df83
