### ISSUE TITLE
Error on Startup with Fresh DB

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2019]
```
> counterparty-server --indexd-port=8432 --database-file=/Users/adam/Library/Application\ Support/Bitcoin/counterparty-4.db start -v

Counterparty Core v10.3.0-rc.1
Verbosity: 1
Quiet: False
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/Bitcoin/counterparty-4.db
Network: `mainnet`
Bitcoin Core: http://rpc:*****@localhost:8332
AddrIndexRs: http://localhost:8432
Counterparty RPC Server: http://rpc:*****@localhost:4100/rpc/
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-07-04T18:07:16.012732000+02:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-07-04T18:07:16.013001000+02:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/Bitcoin/counterparty-4.db`...
2024-07-04T18:07:16.040317000+02:00 - [    INFO] - Database version number updated.
2024-07-04T18:07:16.040513000+02:00 - [    INFO] - Running PRAGMA optimize...
2024-07-04T18:07:16.041034000+02:00 - [   DEBUG] - PRAGMA optimize completed.
2024-07-04T18:07:16.041202000+02:00 - [   DEBUG] - Checking Counterparty version...
2024-07-04T18:07:17.393947000+02:00 - [   DEBUG] - Version check passed.
2024-07-04T18:07:17.418430000+02:00 - [    INFO] - Telemetry enabled.
2024-07-04T18:07:17.418897000+02:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/Bitcoin/counterparty-4.db`...
2024-07-04T18:07:17.423779000+02:00 - [   DEBUG] - Starting API Status Poller...
2024-07-04T18:07:17.423960000+02:00 - [    INFO] - Starting API Server v1...
2024-07-04T18:07:17.424212000+02:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/Bitcoin/counterparty-4.api.db`...
2024-07-04T18:07:17.426585000+02:00 - [    INFO] - New database.
ERROR:root:SQLITE_LOG: cannot open file at line 44373 of [e876e51a0e] (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: os_unix.c:44373: (0) open(/Users/adam/Library/Application Support/Bitcoin/counterparty-4.api.db) - Undefined error: 0 (14) SQLITE_CANTOPEN
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 467, in run
    self.db = database.get_db_connection(config.API_DATABASE, read_only=True, check_wal=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/database.py", line 67, in get_db_connection
    db = apsw.Connection(db_file, flags=apsw.SQLITE_OPEN_READONLY)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
apsw.CantOpenError: CantOpenError: unable to open database file
2024-07-04T18:07:17.529487000+02:00 - [   DEBUG] - Starting Prefetcher...
2024-07-04T18:07:17.529922+02:00 - [    INFO] - RS Fetcher - Indexer initializing...
2024-07-04T18:07:17.530545+02:00 - [   DEBUG] - RS Fetcher - 12 BitcoinClient workers started
2024-07-04T18:07:17.530575+02:00 - [    INFO] - RS Fetcher - Connecting to database: /Users/adam/Library/Application Support/Bitcoin/fetcherdb
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2028/commits/f63d76ce491627b4a9b134a23bccfb082ef3354e
