### ISSUE TITLE
Extra Zeros in Log Timestamps

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2020]
I thought I fixed this?

```
 > counterparty-server --indexd-port=8432 --database-file=/Users/adam/Library/Application\ Support/Bitcoin/counterparty-4.db start -v

Counterparty Core v10.3.0-rc.1
Verbosity: 1
Quiet: False
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/Bitcoin/counterparty-4.db
Network: `mainnet`
Bitcoin Core: http://rpc:*****@localhost:8332
AddrIndexRs: http://localhost:8432
Counterparty RPC Server: http://rpc:*****@localhost:4100/rpc/
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-07-04T18:07:16.012732000+02:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-07-04T18:07:16.013001000+02:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/Bitcoin/counterparty-4.db`...
2024-07-04T18:07:16.040317000+02:00 - [    INFO] - Database version number updated.
2024-07-04T18:07:16.040513000+02:00 - [    INFO] - Running PRAGMA optimize...
2024-07-04T18:07:16.041034000+02:00 - [   DEBUG] - PRAGMA optimize completed.
2024-07-04T18:07:16.041202000+02:00 - [   DEBUG] - Checking Counterparty version...
2024-07-04T18:07:17.393947000+02:00 - [   DEBUG] - Version check passed.
2024-07-04T18:07:17.418430000+02:00 - [    INFO] - Telemetry enabled.
2024-07-04T18:07:17.418897000+02:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/Bitcoin/counterparty-4.db`...
2024-07-04T18:07:17.423779000+02:00 - [   DEBUG] - Starting API Status Poller...
2024-07-04T18:07:17.423960000+02:00 - [    INFO] - Starting API Server v1...
2024-07-04T18:07:17.424212000+02:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/Bitcoin/counterparty-4.api.db`...
2024-07-04T18:07:17.426585000+02:00 - [    INFO] - New database.
ERROR:root:SQLITE_LOG: cannot open file at line 44373 of [e876e51a0e] (14) SQLITE_CANTOPEN
ERROR:root:SQLITE_LOG: os_unix.c:44373: (0) open(/Users/adam/Library/Application Support/Bitcoin/counterparty-4.api.db) - Undefined error: 0 (14) SQLITE_CANTOPEN
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 467, in run
    self.db = database.get_db_connection(config.API_DATABASE, read_only=True, check_wal=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/database.py", line 67, in get_db_connection
    db = apsw.Connection(db_file, flags=apsw.SQLITE_OPEN_READONLY)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
apsw.CantOpenError: CantOpenError: unable to open database file
2024-07-04T18:07:17.529487000+02:00 - [   DEBUG] - Starting Prefetcher...
2024-07-04T18:07:17.529922+02:00 - [    INFO] - RS Fetcher - Indexer initializing...
2024-07-04T18:07:17.530545+02:00 - [   DEBUG] - RS Fetcher - 12 BitcoinClient workers started
2024-07-04T18:07:17.530575+02:00 - [    INFO] - RS Fetcher - Connecting to database: /Users/adam/Library/Application Support/Bitcoin/fetcherdb
2024-07-04T18:07:17.546685+02:00 - [    INFO] - RS Fetcher - Connected
2024-07-04T18:07:17.546709+02:00 - [    INFO] - RS Fetcher - Initialized
2024-07-04T18:07:17.546733000+02:00 - [   DEBUG] - Current Fetcher version: 10.3.0-rc.1
2024-07-04T18:07:17.546997+02:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight...
2024-07-04T18:07:17.547127+02:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight took 101.209µs
2024-07-04T18:07:17.547211+02:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight...
2024-07-04T18:07:17.547934+02:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight took 688.875µs
2024-07-04T18:07:17.547958+02:00 - [    INFO] - RS Fetcher - Starting at block height: 278270
2024-07-04T18:07:17.547976+02:00 - [    INFO] - RS Fetcher - Targeting block height: 850692
2024-07-04T18:07:17.548010+02:00 - [   DEBUG] - RS Fetcher - 1 Producer workers started
2024-07-04T18:07:17.548110+02:00 - [   DEBUG] - RS Fetcher - 6 Fetcher workers started
2024-07-04T18:07:17.548164+02:00 - [   DEBUG] - RS Fetcher - 3 Extractor workers started
2024-07-04T18:07:17.548192+02:00 - [   DEBUG] - RS Fetcher - 1 Orderer workers started
2024-07-04T18:07:17.548215+02:00 - [   DEBUG] - RS Fetcher - 1 Writer workers started
2024-07-04T18:07:17.548242+02:00 - [   DEBUG] - RS Fetcher - 1 Reporter workers started
2024-07-04T18:07:17.548261+02:00 - [    INFO] - RS Fetcher - Fetcher started
2024-07-04T18:07:17.548462000+02:00 - [   DEBUG] - Starting prefetching blocks...
2024-07-04T18:07:17.548795000+02:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-07-04T18:07:17.548821000+02:00 - [   DEBUG] - Looking for Block 278270 in prefetch queue...
2024-07-04T18:07:17.549202000+02:00 - [ WARNING] - Prefetch queue is empty.
2024-07-04T18:07:17.549321000+02:00 - [   DEBUG] - Block 278270 not found in prefetch queue. Waiting...
2024-07-04T18:07:17.654458000+02:00 - [ WARNING] - Prefetch queue is empty.
2024-07-04T18:07:17.654715000+02:00 - [   DEBUG] - Block 278270 not found in prefetch queue. Waiting...
2024-07-04T18:07:17.759873000+02:00 - [ WARNING] - Prefetch queue is empty.
2024-07-04T18:07:17.760143000+02:00 - [   DEBUG] - Block 278270 not found in prefetch queue. Waiting...
2024-07-04T18:07:17.828840000+02:00 - [   DEBUG] - Block 278270 prefetched. (Queue: 1/20)
2024-07-04T18:07:17.830856000+02:00 - [   DEBUG] - Block 278271 prefetched. (Queue: 2/20)
2024-07-04T18:07:17.832119000+02:00 - [   DEBUG] - Block 278272 prefetched. (Queue: 3/20)
2024-07-04T18:07:17.834166000+02:00 - [   DEBUG] - Block 278273 prefetched. (Queue: 4/20)
2024-07-04T18:07:17.834534000+02:00 - [   DEBUG] - Block 278274 prefetched. (Queue: 5/20)
2024-07-04T18:07:17.835296000+02:00 - [   DEBUG] - Block 278275 prefetched. (Queue: 6/20)
2024-07-04T18:07:17.836944000+02:00 - [   DEBUG] - Block 278276 prefetched. (Queue: 7/20)
2024-07-04T18:07:17.837670000+02:00 - [   DEBUG] - Block 278277 prefetched. (Queue: 8/20)
2024-07-04T18:07:17.838914000+02:00 - [   DEBUG] - Block 278278 prefetched. (Queue: 9/20)
2024-07-04T18:07:17.839820000+02:00 - [   DEBUG] - Block 278279 prefetched. (Queue: 10/20)
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2023/commits/63ad196b1b629571b241861927f7be7638840fba
