### ISSUE TITLE
Failure Shutting Down when Something is Already Wrong :)

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2021]
```
2024-07-04T18:21:49.337395000+02:00 - [    INFO] - Block 314909 - Issuance of 100000000000000 BITCOINTALK by 14gLYZgA [a4a6b60] (valid)
2024-07-04T18:21:49.339136000+02:00 - [    INFO] - Block 314909 - Issuance of 100000000000000 EXTREMECOIN by 14gLYZgA [35a16fb] (valid)
2024-07-04T18:21:49.340066000+02:00 - [    INFO] - Block 314909 - Parsing complete. L: e3f228c, TX: e2eb703, M: 0d4b6c6 (0.21s)
2024-07-04T18:21:49.382845000+02:00 - [   DEBUG] - Block 314909/850692 parsed, for 36640 blocks in 0h 14m 31s.
2024-07-04T18:21:49.383159000+02:00 - [   DEBUG] - Looking for Block 314910 in prefetch queue...
2024-07-04T18:21:49.383271000+02:00 - [   DEBUG] - Block 314910 retrieved from queue. (Queue: 19/20)
2024-07-04T18:21:49.385400000+02:00 - [   DEBUG] - Block 314910 fetched. (0.002303s)
2024-07-04T18:21:49.385605000+02:00 - [    INFO] - Block 314910
2024-07-04T18:21:49.394529000+02:00 - [   DEBUG] - Could not connect to backend at `http://XXXXXXXX@localhost:8332`. (Attempt: 1)
2024-07-04T18:21:49.460264+02:00 - [   DEBUG] - RS Fetcher - Write height=314994 max_height=850692 progress="8471716.03" avg_bps="27.02" avg_eps="6.47" total_elapsed="871" remaining_hrs="5.51" f_c_len=32 e_c_len=32 o_c_len=32 w_c_len=32 r_c_len=32 c_c_len=64 total_num_entries=36725
2024-07-04T18:21:49.460819+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315134 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:21:49.460910+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315135 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:21:49.462096000+02:00 - [   DEBUG] - Block 314930 prefetched. (Queue: 20/20)
2024-07-04T18:21:50.465677+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315134 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:21:50.465734+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315135 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:21:51.470688+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315134 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
 2024-07-04T18:21:52.470567+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315135 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:21:54.402503000+02:00 - [   DEBUG] - Could not connect to backend at `http://XXXXXXXX@localhost:8332`. (Attempt: 2)
2024-07-04T18:21:54.475296+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315134 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:21:56.475242+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315135 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
^C2024-07-04T18:21:58.292266000+02:00 - [    INFO] - Stopping API Watcher...
2024-07-04T18:21:58.292996000+02:00 - [ WARNING] - Keyboard interrupt!
2024-07-04T18:21:58.293508000+02:00 - [    INFO] - Stopping API Server...
2024-07-04T18:21:58.800204000+02:00 - [   DEBUG] - Could not connect to backend at `http://XXXXXXXX@localhost:8332`. (Attempt: 1)
2024-07-04T18:22:00.308658000+02:00 - [   ERROR] - API Server did not stop in time. Terminating...
2024-07-04T18:22:00.309993000+02:00 - [    INFO] - Stopping telemetry daemon...
2024-07-04T18:22:00.410781000+02:00 - [    INFO] - Stopping API Status Poller...
2024-07-04T18:22:00.411509000+02:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 448, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 742, in start_all
    api_status_poller.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 460, in stop
    self.db.close()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
             ^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 448, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 742, in start_all
    api_status_poller.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_v1.py", line 460, in stop
    self.db.close()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-07-04T18:22:00.476659+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315135 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:22:01.479130+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315134 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
2024-07-04T18:22:09.478319+02:00 - [   DEBUG] - RS Fetcher - Error fetching block hash for height 315135 Retrying after error: Rpc(JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }))))
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2039/commits/08838593dbc0822b5002bee15b86e77f1af6b5d1
