### ISSUE TITLE
Consensus Error at Block 280,000

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2024]
I'm trying to manually install 10.2, I went down a rabbit hole with kickstart for a while and I am not trying just start and encountered this:
```
Unhandled Exception
Traceback (most recent call last):
  File "/home/rsa-key-20240114/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/cli.py", line 464, in main
    server.start_all(args)
  File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/server.py", line 728, in start_all
    blocks.catch_up(db)
  File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 1199, in catch_up
    tx_index = parse_new_block(db, decoded_block, block_parser=None, tx_index=tx_index)
  File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 1124, in parse_new_block
    new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
  File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 295, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(
  File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/check.py", line 886, in consensus_hash
    raise ConsensusError(error_message)
counterpartycore.lib.check.ConsensusError: Incorrect txlist_hash hash for block 280000.  Calculated f548e8626d1544503b280002ccc7a1ebd5c50ae8aafce2e6c92c465c190c6170 but expected a59b33b4633649db4f14586af47e258ed9b8884dbb7aa308fb1f49a653ee60f4
```

This occurred on two different nodes I've setup the same way.

**Comment by droplister** [comment]
When I delete the contents of /.local/share/counterparty and try again I am able to get beyond 280,000. This could be an artifact of trying to use kickstart and then switching to start or something like this.

**Comment by ouziel-slama** [comment]
> This could be an artifact of trying to use kickstart and then switching to start or something like this.

yep most probably! `kickstart` is dead, if `start` works on a fresh db then all good!
