### ISSUE TITLE
Empty previous txlist_hash

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2025]
In docker compose test vm:

```
counterparty-core-1  | 2024-07-05T09:30:21.459+00:00 - [    INFO] - Starting API Server...
counterparty-core-1  | 2024-07-05T09:30:21.693+00:00 - [    INFO] - Block 850788
counterparty-core-1  | 2024-07-05T09:30:21.849+00:00 - [   ERROR] - Exception caught!
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 727, in start_all
counterparty-core-1  |     blocks.catch_up(db)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1234, in catch_up
counterparty-core-1  |     tx_index = parse_new_block(db, decoded_block, tx_index=tx_index)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1152, in parse_new_block
counterparty-core-1  |     new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 324, in parse_block
counterparty-core-1  |     new_txlist_hash, found_txlist_hash = check.consensus_hash(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/check.py", line 845, in consensus_hash
counterparty-core-1  |     raise ConsensusError(
counterparty-core-1  | counterpartycore.lib.check.ConsensusError: Empty previous txlist_hash for block 850788. Please launch a `rollback`.
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2023/commits/ef809af918382551a7c400536bbd724eab99d7cc
