### ISSUE TITLE
sqlite3.OperationalError: error in view xcp_holders: no such function: CONCAT

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2054]
```
2024-07-10T10:34:47.947+00:00 - [    INFO] - Add defaul value for `locked` and `reset` fields in `issuances` table...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_server.py", line 377, in run_api_server
    watcher = api_watcher.APIWatcher()
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 584, in __init__
    apply_migration()
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 489, in apply_migration
    backend.apply_migrations(backend.to_apply(migrations))
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/backends/base.py", line 449, in apply_migrations
    self.apply_migrations_only(migrations, force=force)
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/backends/base.py", line 461, in apply_migrations_only
    self.apply_one(m, force=force)
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/backends/base.py", line 507, in apply_one
    migration.process_steps(migration_backend, "apply", force=force)
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/migrations.py", line 271, in process_steps
    raise exc_info[1].with_traceback(exc_info[2])
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/migrations.py", line 256, in process_steps
    getattr(step, direction)(backend, force)
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/migrations.py", line 314, in apply
    getattr(self.step, direction)(backend, force)
  File "/home/ouziel/.local/lib/python3.10/site-packages/yoyo/migrations.py", line 412, in apply
    self._apply(backend.connection)
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/migrations/0002.add_default_values_to_issuances.py", line 42, in apply
    cursor.execute(sql)
sqlite3.OperationalError: error in view xcp_holders: no such function: CONCAT
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2059
