### ISSUE TITLE
Testnet Consensus Break

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2056]
```
2024-07-10T13:52:09.799+02:00 - [    INFO] - Block 315996 - Parsing complete. L: ea4beaa, TX: ea4beaa, M: ea4beaa (0.00s)
2024-07-10T13:52:09.800+02:00 - [    INFO] - Block 315997
2024-07-10T13:52:09.800+02:00 - [    INFO] - Block 315997 - Parsing complete. L: 7f0ba94, TX: 7f0ba94, M: 7f0ba94 (0.00s)
2024-07-10T13:52:09.801+02:00 - [    INFO] - Block 315998
2024-07-10T13:52:09.801+02:00 - [    INFO] - Block 315998 - Parsing complete. L: 793aa4b, TX: 793aa4b, M: 793aa4b (0.00s)
2024-07-10T13:52:09.802+02:00 - [    INFO] - Block 315999
2024-07-10T13:52:09.802+02:00 - [    INFO] - Block 315999 - Parsing complete. L: 8a35d99, TX: 8a35d99, M: 8a35d99 (0.00s)
2024-07-10T13:52:09.802+02:00 - [ WARNING] - Prefetch queue is empty.
2024-07-10T13:52:09.908+02:00 - [    INFO] - Block 316000
2024-07-10T13:52:09.908+02:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 730, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1237, in catch_up
    tx_index = parse_new_block(db, decoded_block, tx_index=tx_index)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1153, in parse_new_block
    new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
                                                          ^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 324, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 890, in consensus_hash
    raise ConsensusError(error_message)
counterpartycore.lib.check.ConsensusError: Incorrect txlist_hash hash for block 316000.  Calculated d956a0869b4bb0f1f694dadbcf47fa5a401fafca8f79bb4ef300d1451a87a59c but expected 3e29bcbf3873326097024cc26e9296f0164f552dd79c2ee7cfc344e6d64fa87d
2024-07-10T13:52:09.910+02:00 - [    INFO] - Stopping API Server...
2024-07-10T13:52:10.019+02:00 - [    INFO] - Stopping API Watcher...
2024-07-10T13:52:11.418+02:00 - [    INFO] - Stopping telemetry daemon...
2024-07-10T13:52:11.767+02:00 - [    INFO] - Stopping API Status Poller...
2024-07-10T13:52:12.057+02:00 - [    INFO] - Stopping API Server v1...
2024-07-10T13:52:12.098+02:00 - [    INFO] - Closing database connections...
2024-07-10T13:52:12.112+02:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-07-10T13:52:12.112+02:00 - [    INFO] - Shutting down logging...
2024-07-10T13:52:12.114+02:00 - [    INFO] - Stopping prefetcher...
2024-07-10T13:52:12.185+02:00 - [    INFO] - Shutdown complete.
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2057
