### ISSUE TITLE
`counterpartycore.lib.check.ConsensusError: Incorrect txlist_hash hash for block 700000`

### ISSUE THREAD

**Issue by pinnate-modo** [CounterpartyXCP/counterparty-core#2065]
Having copied over my addrindexrs db from another drive, I was synching Counterparty Core for the first time on a new device when I got the following error:

```
2024-07-13T02:56:31.633-04:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users//repos/counterparty-core/counterparty-core/counterpartycore/server.py", line 730, in start_all
    blocks.catch_up(db)
  File "/Users//repos/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1238, in catch_up
    tx_index = parse_new_block(db, decoded_block, tx_index=tx_index)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//repos/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1154, in parse_new_block
    new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
                                                          ^^^^^^^^^^^^
  File "/Users//repos/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 324, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users//repos/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 890, in consensus_hash
    raise ConsensusError(error_message)
counterpartycore.lib.check.ConsensusError: Incorrect txlist_hash hash for block 700000.  Calculated 997c53b7ca735452ea954d1cf3fc74e9b37eaaf4e180b092576483df12274cdd but expected abb48c10d692c159180a376b4a9002abcf582fab1b5652ba3ccdc73f4b5e0d8a
2024-07-13T02:56:31.640-04:00 - [    INFO] - Stopping API Server...
2024-07-13T02:56:31.791-04:00 - [    INFO] - Stopping API Watcher...
2024-07-13T02:56:33.171-04:00 - [    INFO] - Stopping telemetry daemon...
2024-07-13T02:56:33.388-04:00 - [    INFO] - Stopping API Status Poller...
2024-07-13T02:56:33.638-04:00 - [    INFO] - Stopping API Server v1...
2024-07-13T02:56:33.665-04:00 - [    INFO] - Closing database connections...
2024-07-13T02:56:33.686-04:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-07-13T02:56:33.686-04:00 - [    INFO] - Shutting down logging...
2024-07-13T02:56:33.686-04:00 - [    INFO] - Stopping prefetcher...
ERROR:root:SQLITE_LOG: recovered 806 frames from WAL file /Users//Library/Application Support/counterparty/counterparty.api.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
2024-07-13T02:56:34.874-04:00 - [    INFO] - Shutdown complete.
```

**Comment by pinnate-modo** [comment]
This was fixed with a rollback.

**Comment by ouziel-slama** [comment]
most probably a bad rsfetcher version.

**Comment by adamkrellenstein** [comment]
I thought we were doing a version check to prevent that?

**Comment by ouziel-slama** [comment]
yep but @pinnate-modo compiled a version from branch `apidb`, after we bump the version but before we fixed all the bugs..

**Comment by pinnate-modo** [comment]
makes sense!
