### ISSUE TITLE
10.3.0 Upgrade - Consensus Error at Block 700,000

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2067]
Trying to upgrade to 10.3 from 10.2, I've encountered a consensus error at Block 700,000 each try.

```
counterpartycore.lib.check.ConsensusError: Incorrect txlist_hash hash for block 700000.  Calculated 997c53b7ca735452ea954d1cf3fc74e9b37eaaf4e180b092576483df12274cdd but expected abb48c10d692c159180a376b4a9002abcf582fab1b5652ba3ccdc73f4b5e0d8a
```

The upgrade steps I took are as follows:
```
Shutdown complete.

git fetch --tags
git checkout v10.3.0
git status

pip uninstall counterparty-rs counterparty-core counterparty-wallet

cd counterparty-rs
pip3 install .

cd counterparty-core
pip3 install .

cd counterparty-wallet
pip3 install .

counterparty-server start
```

I have two nodes and both are replicating this error. After it hit this error, I also tried deleting the local database to truly start fresh and that did not solve this either. Here is a longer version of the error log.

```
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]: 2024-07-14T04:45:17.875+00:00 - [    INFO] - Block 700000 - Order opened for 7215 BTC at 16xG9NoS (fbd0cfd) [open]
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]: 2024-07-14T04:45:17.882+00:00 - [   ERROR] - Exception caught!
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]: Traceback (most recent call last):
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/server.py", line 730, in start_all
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:     blocks.catch_up(db)
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 1238, in catch_up
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:     tx_index = parse_new_block(db, decoded_block, tx_index=tx_index)
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 1154, in parse_new_block
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:     new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 324, in parse_block
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:     new_txlist_hash, found_txlist_hash = check.consensus_hash(
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/check.py", line 890, in consensus_hash
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]:     raise ConsensusError(error_message)
Jul 14 04:45:17 counterparty-core-2 counterparty-server[970223]: counterpartycore.lib.check.ConsensusError: Incorrect txlist_hash hash for block 700000.  Calculated 997c53b7ca735452ea954d1cf3fc74e9b37eaaf4e180b092576483df12274cdd but expected abb48c10d692c159180a376b4a9002abcf582fab1b5652ba3ccdc73f4b5e0d8a
```

**Comment by pinnate-modo** [comment]
I had the same consensus error at the same block height with the same calculated hash: uninstalling counterparty-rs and counterparty-core and reinstalling them, and then doing a rollback to block 645030 fixed it.

**Comment by droplister** [comment]
`counterparty-server rollback 645030` worked for me too.

**Comment by droplister** [comment]
It got me passed Block 700,000, but now I'm getting a lot of event mismatches in the log. I'll keep it running.

```
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.014+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969801
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.015+00:00 - [ WARNING] - API Watcher - Event hash mismatch: b77028aaff58beccf78e626bd29858276878444c936bdf89bd40030d4f961a26 != 02bb7081a88c63e45d6bbbb45fc50b6230117aa9cd2f10960b45fd87612410ac
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.015+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969800
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.017+00:00 - [ WARNING] - API Watcher - Event hash mismatch: f0e53bafa29b03a3d4f087f7f32f005c0391c64870c7f518a858b2c5bc4f66ae != 6a4b7a91704b2c63bb3e19c2ea6dae271c2056b869f0213e167ceb8380e4dcb3
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.018+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969799
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.019+00:00 - [ WARNING] - API Watcher - Event hash mismatch: af03f52b5304c63f2f43d44239ee0afa62d98e5e106b301d07f54542cd787df6 != 416f7f43140bec5b01c31be2e93f2b0371a0512fb2c118b50d2e58df3ae8ac69
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.019+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969798
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.020+00:00 - [ WARNING] - API Watcher - Event hash mismatch: d300d584e5323e6eea85929bb5c003eefcc3b7adfced07d044bb5bbdc96b369e != 6aeb3cab059e4dc58aa534f03380470872adf802a150d0a15abfc04430ed1ab7
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.021+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969797
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.022+00:00 - [ WARNING] - API Watcher - Event hash mismatch: 599162c25d5f3d05481a1edb5a96b60196e8f32ffdff5d4647f5118d4a8d9285 != 64ab8ba9f69c1b7eff75e558553d898e6697741bcaffd71f6d912a0b5581fa0f
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.022+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969796
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.022+00:00 - [ WARNING] - API Watcher - Event hash mismatch: ac2b063698a758e0ecddf9697ad537f0623bf758f7c25ee7813a7d5677c2c820 != b405c9bc812a702471fc31f05e9a38801c159dc94591f3a486645d5f4e20e325
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.023+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969795
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700382]: 2024-07-14T18:18:12.023+00:00 - [    INFO] - Block 702652 - Dispense 35000000000 XCP from 1MEYKG9J to 17bK1YeL (bce133b) [valid]
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.024+00:00 - [ WARNING] - API Watcher - Event hash mismatch: 8fd98d29f13f3b50653f0477e36b11fa65325421b2d806fdd98e0bc934fa07e7 != 6844472d17ee5dc55948873d54de3bd085bbe1d032d87db4b1c8d72770c964fe
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.024+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969794
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.026+00:00 - [ WARNING] - API Watcher - Event hash mismatch: 970f8b947cb77d3d32e920be64628073f632d7887e2fcc512dad1beed293ffd8 != 1994d9154deb6f6aeeeea92eac484ec0b1e05d7c5807ddd75c6370921072df02
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.026+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969793
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.027+00:00 - [ WARNING] - API Watcher - Event hash mismatch: e7d56a56f8b969cc26fee9f7368e80f8e2a3c1e4526aecd7e87cc43dcb92aa50 != 2393aaafa897447fb7712f90cda8b0a38b8f5bb9df21348372e194928e74d37b
Jul 14 18:18:12 counterparty-core-1 counterparty-server[1700408]: 2024-07-14T18:18:12.028+00:00 - [ WARNING] - API Watcher - Rolling back event: 9969792

```

**Comment by pinnate-modo** [comment]
This is expected, it's the API rollback. Synching the chain happens in tandem with it.

**Comment by droplister** [comment]
Ok, great, as you replied my nodes have finished doing the api rollback and continued.

**Comment by adamkrellenstein** [comment]
Those log messages should be fixed then: https://github.com/CounterpartyXCP/counterparty-core/issues/2068
