### ISSUE TITLE
Block 853628: ZeroDivisionError

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2120]
I ran into this on two nodes I'm running and I haven't seen it reported here. I will try a reparse. It looks like `ledger.price` may need some logic to catch division by zero errors and possibly negative numbers.

```
Jul 31 03:40:37 counterparty-core-2 systemd[1]: Started Counterparty Server.
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: Counterparty Core v10.3.0
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: Verbosity: 0
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: Quiet: False
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: Configuration File: /home/rsa-key-20240114/.config/counterparty/server.conf
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: Counterparty Database: /home/rsa-key-20240114/.local/share/counterparty/counterparty.db
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: Server Log: /home/rsa-key-20240114/.cache/counterparty/log/server.log
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: API Access Log: /home/rsa-key-20240114/.cache/counterparty/log/server.access.log
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: ------------------------------ START ------------------------------
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:37.905+00:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:37.910+00:00 - [    INFO] - Initializing database...
Jul 31 03:40:37 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:37.915+00:00 - [    INFO] - Running PRAGMA optimize...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871964]: 2024-07-31T03:40:39.015+00:00 - [    INFO] - Starting API Watcher...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871964]: 2024-07-31T03:40:39.015+00:00 - [    INFO] - Starting API Server...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.107+00:00 - [    INFO] - Telemetry enabled.
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.114+00:00 - [    INFO] - Starting API Server v1...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.258+00:00 - [    INFO] - RS Fetcher - Indexer initializing...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.258+00:00 - [    INFO] - RS Fetcher - Connecting to database: /home/rsa-key-20240114/.local/share/counterparty/fetcherdb
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.280+00:00 - [    INFO] - RS Fetcher - Connected
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.280+00:00 - [    INFO] - RS Fetcher - Initialized
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.282+00:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.282+00:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight took 29.553µs
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.282+00:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight...
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.283+00:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight took 593.907µs
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.283+00:00 - [    INFO] - RS Fetcher - Starting at block height: 853628
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.283+00:00 - [    INFO] - RS Fetcher - Targeting block height: 854747
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.283+00:00 - [    INFO] - RS Fetcher - Fetcher started
Jul 31 03:40:39 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:39.990+00:00 - [    INFO] - Block 853628
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:56.108+00:00 - [    INFO] - Block 853628 - Order match cancelled XCP / BTC (3a5aea4_7f6913e) [expired]
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:56.111+00:00 - [   ERROR] - Exception caught!
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]: Traceback (most recent call last):
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/server.py", line 730, in start_all
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     blocks.catch_up(db)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 1238, in catch_up
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     tx_index = parse_new_block(db, decoded_block, tx_index=tx_index)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 1154, in parse_new_block
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/blocks.py", line 302, in parse_block
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     order.expire(db, block_index)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/order.py", line 1012, in expire
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     match(db, ledger.get_order(db, order_hash=order_match["tx0_hash"])[0], block_index)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/order.py", line 729, in match
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     tx1_price = ledger.price(tx1["get_quantity"], tx1["give_quantity"])
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/ledger.py", line 637, in price
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     return fractions.Fraction(numerator, denominator)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:   File "/usr/lib/python3.10/fractions.py", line 156, in __new__
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]:     raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]: ZeroDivisionError: Fraction(108852, 0)
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:56.115+00:00 - [    INFO] - Stopping API Server...
Jul 31 03:40:56 counterparty-core-2 counterparty-server[871964]: 2024-07-31T03:40:56.258+00:00 - [    INFO] - Stopping API Watcher...
Jul 31 03:40:57 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:57.617+00:00 - [    INFO] - Stopping telemetry daemon...
Jul 31 03:40:57 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:57.904+00:00 - [    INFO] - Stopping API Status Poller...
Jul 31 03:40:57 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:57.974+00:00 - [    INFO] - Stopping API Server v1...
Jul 31 03:40:58 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:58.457+00:00 - [    INFO] - Closing database connections...
Jul 31 03:40:58 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:58.461+00:00 - [    INFO] - Stopping AddrIndexRs thread...
Jul 31 03:40:58 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:58.461+00:00 - [    INFO] - Shutting down logging...
Jul 31 03:40:58 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:58.461+00:00 - [    INFO] - Stopping prefetcher...
Jul 31 03:40:59 counterparty-core-2 counterparty-server[871938]: ERROR:root:SQLITE_LOG: recovered 7 frames from WAL file /home/rsa-key-20240114/.local/share/counterparty/counterparty.api.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
Jul 31 03:40:59 counterparty-core-2 counterparty-server[871938]: 2024-07-31T03:40:59.505+00:00 - [    INFO] - Shutdown complete.
Jul 31 03:41:00 counterparty-core-2 kill[872165]: Usage:
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  kill [options] <pid> [...]
Jul 31 03:41:00 counterparty-core-2 kill[872165]: Options:
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  <pid> [...]            send signal to every <pid> listed
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  -<signal>, -s, --signal <signal>
Jul 31 03:41:00 counterparty-core-2 kill[872165]:                         specify the <signal> to be sent
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  -q, --queue <value>    integer value to be sent with the signal
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  -l, --list=[<signal>]  list all signal names, or convert one to a name
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  -L, --table            list all signal names in a nice table
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  -h, --help     display this help and exit
Jul 31 03:41:00 counterparty-core-2 kill[872165]:  -V, --version  output version information and exit
Jul 31 03:41:00 counterparty-core-2 kill[872165]: For more details see kill(1).
Jul 31 03:41:00 counterparty-core-2 systemd[1]: counterparty.service: Control process exited, code=exited, status=1/FAILURE
Jul 31 03:41:00 counterparty-core-2 systemd[1]: counterparty.service: Failed with result 'exit-code'.
Jul 31 03:41:00 counterparty-core-2 systemd[1]: counterparty.service: Consumed 47.163s CPU time.
```

**Comment by droplister** [comment]
Looks like a duplicate of #2093. But it's not database corruption as thought in that closed issue.

It's the price function and the fact that this order has a zero value: https://xchain.io/tx/2742192

It would be easier to debug these types of things if the log included the full tx hash.

This code needs a check that if denominator is less than or equal to 0 then the price returned is 0.

https://github.com/CounterpartyXCP/counterparty-core/blob/870987710dedea9ef15e2724b6ad6cdd06483b97/counterparty-core/counterpartycore/lib/ledger.py#L634-L641

**Comment by ouziel-slama** [comment]
the problem actually comes from a bug 20 blocks earlier. An order match with an order still in the mempool (`tx0`):

```
17627926|853607|insert|order_matches|{"backward_asset":"BTC","backward_quantity":108852,"block_index":853607,"fee_paid":0,"forward_asset":"XCP","forward_quantity":679687969,"id":"3a5aea4bfac7c9a9b8f4aab "match_expire_index":853627,"status":"p ending","tx0_address":"1LTQabo8z1C4Ns8e7NAZpZjazx1sfDbubx","tx0_block _index":9999999,"tx0_expiration":8064,"tx0_hash":"3a5aea4bfac7c9a9b8f4aab782e8e483e282e1abe691900a29ae390a5f42a4b0","tx0_index":2742186,"tx1_address":"bc1q2tpg cau64pff95phsduz4rt24re8n484vz7lqw","tx1_block_index":853 607,"tx1_expiration":8064,"tx1_hash":"7f6913e8e0b8b792e22645a91ea7a2e7beaba777c14a88b9876dd4daf4a4b8a5","tx1_index":2735121}|1721762824|ORDER_MATCH||41927 38441e86292d442f9d4dc1e6a8e9035da98b54529c506ccb7ad7b51878f 
````

fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2121

**Comment by ouziel-slama** [comment]
@droplister A reparse from a block before 853607 should fix the problem.
