### ISSUE TITLE
Transaction Cursor: Internal Server Error

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2123]
Paginating through all transactions, around 8500-8600 txs in the next_cursor gives me an error when I use it. Same error if I use offset/limit too. The error goes away after 8600, so there may be a tx within this range that does something unexpected.

https://api.counterparty.io:4000/v2/transactions?verbose=true&cursor=2735172

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

https://api.counterparty.io:4000/v2/transactions?verbose=true&offset=8500&limit=100

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by droplister** [comment]
Somewhere between tx_index 2735162 and 2735165.

**Comment by droplister** [comment]
```
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]: 2024-08-03T18:48:54.101+00:00 - [   ERROR] - Exception on /v2/transactions [GET]
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]: Traceback (most recent call last):
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     response = self.full_dispatch_request()
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     rv = self.handle_user_exception(e)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     rv = self.dispatch_request()
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     return self.ensure_sync(f)(*args, **kwargs)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/api/api_server.py", line 351, in handle_route
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     result = inject_details(db, result)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/api/util.py", line 593, in inject_details
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     result_list = inject_unpacked_data(db, result_list)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/api/util.py", line 577, in inject_unpacked_data
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     result_item = inject_unpacked_data_in_dict(db, result_item)  # noqa PLW2901
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/api/util.py", line 570, in inject_unpacked_data_in_dict
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     item["unpacked_data"] = transaction.unpack(db, data, block_index=block_index)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/transaction.py", line 1830, in unpack
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     mpma_message_data = messages.versions.mpma.unpack(message, block_index)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/versions/mpma.py", line 26, in unpack
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     unpacked = _decode_mpma_send_decode(message, block_index)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/versions/mpma_util/internals.py", line 243, in _decode_mpma_send_decode
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     sends = _decode_decode_sends(stream, nbits, lut, block_index)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/versions/mpma_util/internals.py", line 218, in _decode_decode_sends
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     asset, send_list = _decode_decode_send_list(stream, nbits, lut, block_index)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/versions/mpma_util/internals.py", line 204, in _decode_decode_send_list
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     memo, is_hex = _decode_memo(stream)
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:   File "/home/rsa-key-20240114/.local/lib/python3.10/site-packages/counterpartycore/lib/messages/versions/mpma_util/internals.py", line 232, in _decode_memo
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]:     data = data.decode("utf-8")
Aug 03 18:48:54 counterparty-core-1 counterparty-server[950278]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 7: unexpected end of data
```

**Comment by droplister** [comment]
Maybe there's a way to try/catch utf-8 and then try another encoding like before finally just returning the data undecoded?
https://github.com/CounterpartyXCP/counterparty-core/blob/870987710dedea9ef15e2724b6ad6cdd06483b97/counterparty-core/counterpartycore/lib/messages/versions/mpma_util/internals.py#L224-L236

**Comment by droplister** [comment]
Other tx_index with the same error: 2726873

**Comment by ouziel-slama** [comment]
@droplister thanks for the report! fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2124
