### ISSUE TITLE
apsw.ConstraintError: ConstraintError

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2300]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 920, in run
    self.follow()
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 907, in follow
    parse_next_event(self.api_db, self.ledger_db)
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 752, in parse_next_event
    parse_event(api_db, next_event)
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 647, in parse_event
    event["insert_rowid"] = execute_event(api_db, event)
  File "/home/ouziel/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 540, in execute_event
    cursor.execute(sql, sql_bindings)
  File "src/cursor.c", line 169, in resetcursor
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: transactions.tx_hash
```

**Comment by ouziel-slama** [comment]
should be fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2299/commits/2a2a6b507c8ed2c1326279dfd55a365574ba24ea
