### ISSUE TITLE
ValueError: Error processing script

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2333]
````
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/script.py", line 338, in script_to_asm
    asm = utils.script_to_asm(scriptpubkey)
ValueError: Error processing script

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 746, in start_all
    blocks.catch_up(db)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1337, in catch_up
    tx_index = parse_new_block(db, decoded_block, tx_index=tx_index)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1242, in parse_new_block
    tx_index = list_tx(
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 966, in list_tx
    source, destination, btc_amount, fee, data, dispensers_outs, utxos_info = get_tx_info(
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/gettxinfo.py", line 581, in get_tx_info
    utxos_info = get_utxos_info(db, decoded_tx)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/gettxinfo.py", line 570, in get_utxos_info
    asm = script.script_to_asm(vout["script_pub_key"])
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/script.py", line 344, in script_to_asm
    raise exceptions.DecodeError("invalid script")  # noqa: B904
counterpartycore.lib.exceptions.DecodeError: invalid script
````

**Comment by ouziel-slama** [comment]
already fixed in 10.4.0
