### ISSUE TITLE
`Negative quantity` Crash

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2371]
> this is the first error when i just went to run 10.4.4 after git pull to update from 10.2.0…

```
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /root/.config/counterparty/server.conf
Counterparty Database: /data/counterparty/counterparty.db
Counterparty API Database: /data/counterparty/counterparty.api.db
Rust Fetcher Database: /data/counterparty/fetcherdb
Server Log: /root/.cache/counterparty/log/server.log
API Access Log: /root/.cache/counterparty/log/server.access.log

------------------------------ START ------------------------------

2024-10-16T15:44:19.606+00:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-10-16T15:44:19.615+00:00 - [    INFO] - Initializing database...
ERROR:root:SQLITE_LOG: statement aborts at 3: [
        CREATE TABLE IF NOT EXISTS destructions(
            tx_index INTEGER,
            tx_hash TEXT,
            block_index INTEGER,
            source TEXT,
            asset INT (17) SQLITE_SCHEMA
2024-10-16T15:47:09.828+00:00 - [    INFO] - Client minor version number mismatch. Triggering a reparse... (2 ≠ 4)
2024-10-16T15:47:09.829+00:00 - [    INFO] - Rolling database back to Block 0...
2024-10-16T15:48:09.696+00:00 - [    INFO] - Initializing database...
2024-10-16T15:48:09.750+00:00 - [    INFO] - Recalculating consensus hashes…
```

> this error caused another reparse from 0…

```
sorry that got cut off, heres the moment it happened…
2024-10-16T16:59:57.528+00:00 - [    INFO] - Block 283657 - Order opened for 101490909091 XCP at 1DVDX2pa (50f7c62) [open]
2024-10-16T16:59:57.532+00:00 - [ WARNING] - ParseTransactionError for tx 50f7c6268e1d44e4f3ccc04a810b6b329ce68ebb81d1e5222f7c11eded204797: Negative quantity.
2024-10-16T16:59:57.688+00:00 - [    INFO] - 5387 blocks reparsed in 34.98s.
2024-10-16T16:59:57.688+00:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1294, in check_database_version
    check.database_version(db)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/check.py", line 1028, in database_version
    raise DatabaseVersionError(
counterpartycore.lib.check.DatabaseVersionError: Client minor version number mismatch. Triggering a reparse... (2 ≠ 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 154, in parse_tx
    order.parse(db, tx, message)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/order.py", line 630, in parse
    match(db, tx)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/order.py", line 911, in match
    ledger.credit(
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 380, in credit
    raise CreditError("Negative quantity.")
counterpartycore.lib.ledger.CreditError: Negative quantity.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 722, in start_all
    blocks.check_database_version(db)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1301, in check_database_version
    reparse(db, block_index=e.from_block_index)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1154, in reparse
    parse_block(
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 356, in parse_block
    raise e
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 349, in parse_block
    parse_tx(db, tx)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 247, in parse_tx
    raise exceptions.ParseTransactionError(f"{e}")  # noqa: B904
counterpartycore.lib.exceptions.ParseTransactionError: Negative quantity.
2024-10-16T16:59:57.698+00:00 - [    INFO] - Closing database connections…
```

> the reparse was triggered when upgrading from v10.2.0 to v10.4.4 as i followed the instructions for updating with docker
> 
> then it was subsequently retriggered when encountering txid 50f7c6268e1d44e4f3ccc04a810b6b329ce68ebb81d1e5222f7c11eded204797

**Comment by adamkrellenstein** [comment]
I don't think so. this was from a while ago
