### ISSUE TITLE
Waitress Crash

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2374]
```

------------------------------ START ------------------------------

2024-10-16T18:43:46.579-04:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-10-16T18:43:46.582-04:00 - [    INFO] - Initializing database...
2024-10-16T18:43:46.593-04:00 - [    INFO] - Running PRAGMA optimize...
2024-10-16T18:46:00.552-04:00 - [    INFO] - Starting API Watcher...
2024-10-16T18:46:00.552-04:00 - [    INFO] - Starting API Server...
2024-10-16T18:46:00.661-04:00 - [    INFO] - Stopping API Watcher...
2024-10-16T18:46:00.706-04:00 - [    INFO] - API Watcher - Catch up completed.
Process Process-1:
Traceback (most recent call last):
  File "/home/evan/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_server.py", line 406, in run_api_server
    wsgi_server = wsgi.WSGIApplication(app, args=args)
  File "/home/evan/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/wsgi.py", line 297, in __init__
    self.server = WaitressApplication(self.app, self.args)
  File "/home/evan/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/wsgi.py", line 276, in __init__
    self.server = waitress.server.create_server(
  File "/home/evan/.local/lib/python3.10/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/home/evan/.local/lib/python3.10/site-packages/waitress/server.py", line 236, in __init__
    self.create_socket(self.family, self.socktype)
  File "/home/evan/.local/lib/python3.10/site-packages/waitress/wasyncore.py", line 351, in create_socket
    sock = socket.socket(family, type)
  File "/usr/lib/python3.10/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/evan/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_server.py", line 418, in run_api_server
    wsgi_server.stop()
UnboundLocalError: local variable 'wsgi_server' referenced before assignment
```

**Comment by adamkrellenstein** [comment]
so obv. there's a local variable referencing issue, but for some reason on @pinnate-modo 's computer, there's some issue with spinning up Waitress in the first place. this is *probably* just an OS / configuration issue.

**Comment by adamkrellenstein** [comment]
okay problem was @pinnate-modo had ipv6 disabled. we should make this cleaner at least

**Comment by pinnate-modo** [comment]
for completeness: I fixed this by setting `--rpc-host` and `--api-host` to 127.0.0.1

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2382
