### ISSUE TITLE
unsupported operand type(s) for |: 'NoneType' and 'dict'

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2415]
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/8eb7e021-bc17-44b0-b180-1d52424b4ad4">

**Comment by adamkrellenstein** [comment]
This broke `prd-xcp-dev`:

<img width="918" alt="image" src="https://github.com/user-attachments/assets/158d1356-8c99-4042-8b27-90c54a482b63">

**Comment by adamkrellenstein** [comment]
possible non-determinism. it's killing `dev`:

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/e80db53d-3d3b-4fe4-8d4a-d6c0b5e30ba4">

but it's parsing fine locally:

```
> http GET 'localhost:4000/v2/transactions/f929eb0a8290d1330e88576765d57323e46bddeb391b84726af64fc1c2b26070'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Content-Length: 542
Content-Type: application/json
Date: Thu, 17 Oct 2024 22:43:19 GMT
Server: waitress
X-Bitcoin-Height: 866119
X-Counterparty-Height: 866119
X-Counterparty-Ready: True
X-Counterparty-Version: 10.4.8

{
    "result": {
        "block_hash": "0000000000000000000231657d25de8f2d317d08d1fbae11b642dd9107c3dec3",
        "block_index": 866114,
        "block_time": 1729201973,
        "btc_amount": 0,
        "confirmed": true,
        "data": "5b4131333931373839323333373435373737323735397c313030303030",
        "destination": null,
        "fee": 5000,
        "source": "bc1qxv9chehvqpyvxpp36q3rzrk8zals498n96dnzd",
        "supported": true,
        "tx_hash": "f929eb0a8290d1330e88576765d57323e46bddeb391b84726af64fc1c2b26070",
        "tx_index": 2764758,
        "utxos_info": "f929eb0a8290d1330e88576765d57323e46bddeb391b84726af64fc1c2b26070:1"
    }
}
adam@Adams-MacBook-Pro ~ > 
```

**Comment by adamkrellenstein** [comment]
So we have a discrepancy in the messages hash:

```
http GET 'localhost:4000/v2/blocks/866113'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Content-Length: 554
Content-Type: application/json
Date: Thu, 17 Oct 2024 22:51:56 GMT
Server: waitress
X-Bitcoin-Height: 866120
X-Counterparty-Height: 866120
X-Counterparty-Ready: True
X-Counterparty-Version: 10.4.8

{
    "result": {
        "block_hash": "0000000000000000000270e8a49183b9715382dde4906ef33bfe9af63b11c396",
        "block_index": 866113,
        "block_time": 1729201419,
        "confirmed": true,
        "difficulty": 386076365,
        "ledger_hash": "e2feb32fa8ab97505b253b8314bee931d6cac2c4f9d285ef95716423c089ca81",
        "messages_hash": "3dd86264beebd5dd744761eb3ae67175322f8328db63264ac263b12e44a9847a",
        "previous_block_hash": "00000000000000000000b74ad040b30e45aca96573cd0537e38c67914b529da5",
        "transaction_count": 19,
        "txlist_hash": "ce3a2895d080c0b927a5b6b86df65f7d3d2d566175390dda4c0fe57ecfde87df"
    }
}
```

`dev-xcp-main`
```
{
  "insertId": "bo091hf1xtn8v",
  "jsonPayload": {
    "pathname": "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py",
    "thread": 137163103506432,
    "block_index": null,
    "message": "Block 866113 - Parsing complete. L: e2feb32fa8ab97505b253b8314bee931d6cac2c4f9d285ef95716423c089ca81, TX: ce3a2895d080c0b927a5b6b86df65f7d3d2d566175390dda4c0fe57ecfde87df, M: 8c32a05cbc613a77445ae06aa0ae907aa7230004c3a99f40e8f0ee2d707c167c (2.20s)",
    "module": "blocks",
    "cos.googleapis.com/container_id": "35773304cb9b8343e73fab2c904e164d4b1a6624b3137a1dbd84aa88368f4ca8",
    "cos.googleapis.com/container_name": "etc-counterparty-api-1",
    "name": "counterparty",
    "process": 1,
    "stack_info": null,
    "cos.googleapis.com/stream": "stderr",
    "levelname": "INFO",
    "threadName": "MainThread",
    "lineno": 1274,
    "processName": "MainProcess",
    "filename": "blocks.py",
    "time": "2024-10-17T21:44:03.675508+00:00",
    "funcName": "parse_new_block"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "project_id": "noted-extension-407918",
      "instance_id": "8878289658435634410",
      "zone": "us-east4-c"
    }
  },
  "timestamp": "2024-10-17T21:44:03.675836387Z",
  "logName": "projects/noted-extension-407918/logs/cos_containers",
  "receiveTimestamp": "2024-10-17T21:44:04.329992223Z"
}
```

**Comment by adamkrellenstein** [comment]
I think we need to roll `dev-xcp-main` back...

**Comment by loon3** [comment]
i just crashed the server with a manually constructed fairmint for a numeric asset

```counterparty-core-1  | 2024-10-18T00:14:06.680+00:00 - [ WARNING] - ParseTransactionError for tx 25fcc26c8a27cf0c1679f17aec5889d1b715f201c74fa74cd5dea27ba9a98414: unsupported operand type(s) for |: 'NoneType' and 'dict'```

the message is ```434e5452505254595b4131323639373037373234323532333036343830307c343230303030```

**Comment by loon3** [comment]
was able to get the node started again using ```--force-recreate``` but the tx has since been mined in block 866128 and as soon as it saw it the node crashed with the following warning... 

```
counterparty-core-1  | 2024-10-18T00:52:32.920+00:00 - [ WARNING] - ParseTransactionError for tx 25fcc26c8a27cf0c1679f17aec5889d1b715f201c74fa74cd5dea27ba9a98414: unsupported operand type(s) for |: 'NoneType' and 'dict'
counterparty-core-1  | 2024-10-18T00:52:32.978+00:00 - [   ERROR] - Exception caught!
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 205, in parse_tx
counterparty-core-1  |     fairmint.parse(db, tx, message)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/fairmint.py", line 280, in parse
counterparty-core-1  |     bindings = last_issuance | {
counterparty-core-1  | TypeError: unsupported operand type(s) for |: 'NoneType' and 'dict'
counterparty-core-1  | 
counterparty-core-1  | During handling of the above exception, another exception occurred:
counterparty-core-1  | 
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 753, in start_all
counterparty-core-1  |     blocks.catch_up(db)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1348, in catch_up
counterparty-core-1  |     tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1262, in parse_new_block
counterparty-core-1  |     new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 356, in parse_block
counterparty-core-1  |     raise e
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 349, in parse_block
counterparty-core-1  |     parse_tx(db, tx)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 247, in parse_tx
counterparty-core-1  |     raise exceptions.ParseTransactionError(f"{e}")  # noqa: B904
counterparty-core-1  | counterpartycore.lib.exceptions.ParseTransactionError: unsupported operand type(s) for |: 'NoneType' and 'dict'
counterparty-core-1  | 2024-10-18T00:52:32.987+00:00 - [    INFO] - Stopping API Server...
counterparty-core-1  | 2024-10-18T00:52:33.993+00:00 - [    INFO] - Stopping API Watcher...
counterparty-core-1  | 2024-10-18T00:52:34.991+00:00 - [   ERROR] - API Server did not stop in time. Terminating...
counterparty-core-1  | 2024-10-18T00:52:34.992+00:00 - [    INFO] - Stopping API Status Poller...
counterparty-core-1  | 2024-10-18T00:52:35.490+00:00 - [    INFO] - Stopping API Server v1...
counterparty-core-1  | 2024-10-18T00:52:36.768+00:00 - [    INFO] - Closing database connections...
counterparty-core-1  | 2024-10-18T00:52:36.788+00:00 - [    INFO] - Stopping AddrIndexRs thread...
counterparty-core-1  | 2024-10-18T00:52:36.789+00:00 - [    INFO] - Shutting down logging...
counterparty-core-1  | 2024-10-18T00:52:36.790+00:00 - [    INFO] - Stopping prefetcher...
counterparty-core-1  | ERROR:root:SQLITE_LOG: recovered 810 frames from WAL file /data/counterparty/counterparty.api.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
counterparty-core-1  | 2024-10-18T00:52:43.538+00:00 - [    INFO] - Shutdown complete.
counterparty-core-1 exited with code 0

```

**Comment by loon3** [comment]
this was fixed with a rollback to 866100 using ```docker compose run -it counterparty-core rollback 866100```

rather than the error when it sees the problem tx now it just gives an invalid response...

```counterparty-core-1  | 2024-10-18T01:26:15.299+00:00 - [    INFO] - Block 866128 - Fairmint 25fcc26c8a27cf0c1679f17aec5889d1b715f201c74fa74cd5dea27ba9a98414 is invalid: invalid: fairminter not found for asset: `A12697077242523064800```

**Comment by loon3** [comment]
...and now my API is still stuck, /v2 endpoint gives...

```{
"result": {
"server_ready": false,
"network": "mainnet",
"version": "10.4.8",
"backend_height": 866134,
"counterparty_height": 866126,
```

**Comment by pinnate-modo** [comment]
For reference, here was @wasthatawolf's invalid tx that triggered this 
```
234323532333036343830307c343230303030"
HTTP/1.1 200 OK
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Content-Length: 114
Content-Type: application/json
Date: Fri, 18 Oct 2024 01:09:19 GMT
Server: waitress
X-Bitcoin-Height: 866131
X-Counterparty-Height: 866131
X-Counterparty-Ready: True
X-Counterparty-Version: 10.4.8

{
    "result": {
        "message_data": [
            "A12697077242523064800",
            420000
        ],
        "message_type": "fairmint",
        "message_type_id": 91
    }
}
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2427/commits/cc34da4ba0e2d20cf613753bed0f0eb8fc37678d
