### ISSUE TITLE
Unclean Shutdown

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2437]
```
2024-10-18T10:39:16.890-04:00 - [    INFO] - RS Fetcher - Connecting to database: /Users/adam/Library/Application Support/counterparty/fetcherdb
2024-10-18T10:39:16.906-04:00 - [    INFO] - RS Fetcher - Connected
2024-10-18T10:39:16.907-04:00 - [    INFO] - RS Fetcher - Initialized
2024-10-18T10:39:16.907-04:00 - [   DEBUG] - Current Fetcher version: 10.4.8
2024-10-18T10:39:16.907-04:00 - [   ERROR] - Fetcher version mismatch. Expected: 10.5.0, Got: 10.4.8. Please re-compile `counterparty-rs`.
2024-10-18T10:39:16.907-04:00 - [   ERROR] - Failed to initialize fetcher: Fetcher version mismatch 10.5.0 != 10.4.8.. Retrying in 5 seconds...
2024-10-18T10:39:16.908-04:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 753, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1337, in catch_up
    fetcher.start(util.CURRENT_BLOCK_INDEX + 1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 61, in start
    raise e
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 55, in start
    raise ValueError(
ValueError: Fetcher version mismatch 10.5.0 != 10.4.8.
2024-10-18T10:39:16.911-04:00 - [    INFO] - Stopping API Server...
2024-10-18T10:39:16.934-04:00 - [    INFO] - Stopping API Watcher...
2024-10-18T10:39:16.998-04:00 - [   DEBUG] - API Status Poller - Backend state check passed.
2024-10-18T10:39:17.015-04:00 - [   DEBUG] - API Status Poller: Counterparty database is behind backend.
2024-10-18T10:39:17.370-04:00 - [   DEBUG] - Counterparty is currently behind Bitcoin Core. (866192 < 866204)
2024-10-18T10:39:18.932-04:00 - [   ERROR] - API Server did not stop in time. Terminating...
2024-10-18T10:39:18.933-04:00 - [    INFO] - Stopping API Status Poller...
2024-10-18T10:39:19.031-04:00 - [    INFO] - Stopping API Server v1...
2024-10-18T10:40:07.390-04:00 - [   DEBUG] - All assets have been conserved.
2024-10-18T10:40:08.412-04:00 - [   DEBUG] - Creating connection to `/Users/adam/Library/Application Support/counterparty/counterparty.db`...
2024-10-18T10:40:08.433-04:00 - [    INFO] - Closing database connections...
2024-10-18T10:40:08.462-04:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-10-18T10:40:08.462-04:00 - [    INFO] - Shutting down logging...
2024-10-18T10:40:08.463-04:00 - [    INFO] - Stopping prefetcher...
2024-10-18T10:40:08.464-04:00 - [   ERROR] - Error during stop: 'RSFetcher' object has no attribute 'executor'
2024-10-18T10:40:08.467-04:00 - [   DEBUG] - Prefetcher shutdown complete.
2024-10-18T10:40:08.467-04:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 471, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 782, in start_all
    rsfetcher.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 185, in stop
    RSFetcher().stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 170, in stop
    raise e
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 161, in stop
    if self.executor:
AttributeError: 'RSFetcher' object has no attribute 'executor'
Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 471, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 782, in start_all
    rsfetcher.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 185, in stop
    RSFetcher().stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 170, in stop
    raise e
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 161, in stop
    if self.executor:
AttributeError: 'RSFetcher' object has no attribute 'executor'
adam@Adams-MacBook-Pro ~/D/w/C/C/c/counterparty-core (develop=) > 
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2786
