### ISSUE TITLE
Another Unclean Shutdown

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2438]
```
2024-10-18T10:56:13.833-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866199 to be written Retrying after error: BlockNotWritten(866199)
2024-10-18T10:56:13.859-04:00 - [    INFO] - Block 866193 - 100000000000 MINTS minted for 0 XCP by 1LEVY62hNa2qQybRFWLb2h9sdPPexnDcR
2024-10-18T10:56:13.959-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866199 and target height 866206
2024-10-18T10:56:14.040-04:00 - [    INFO] - Block 866193 - 100000000000 MINTS minted for 0 XCP by 1LEVY62hNa2qQybRFWLb2h9sdPPexnDcR
2024-10-18T10:56:14.153-04:00 - [   DEBUG] - Block 866199 prefetched. (Queue: 6/20)
2024-10-18T10:56:14.153-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:14.233-04:00 - [    INFO] - Block 866193 - 100000000000 MINTS minted for 0 XCP by 1LEVY62hNa2qQybRFWLb2h9sdPPexnDcR
^C2024-10-18T10:56:14.368-04:00 - [    INFO] - Stopping API Watcher...
2024-10-18T10:56:14.370-04:00 - [ WARNING] - Keyboard interrupt!
2024-10-18T10:56:14.372-04:00 - [    INFO] - Stopping API Server...
2024-10-18T10:56:14.380-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:14.838-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866199 to be written Retrying after error: BlockNotWritten(866199)
2024-10-18T10:56:14.961-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:14.988-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866200 and target height 866206
2024-10-18T10:56:14.989-04:00 - [   DEBUG] - RS Fetcher - Write height=866200 max_height=866206 progress="99.99" avg_bps="1.06" avg_eps="1.06" total_elapsed="7" remaining_hrs="0.00" f_c_len=0 e_c_len=0 o_c_len=0 w_c_len=0 r_c_len=0 c_c_len=1 total_num_entries=8
2024-10-18T10:56:15.710-04:00 - [   DEBUG] - Block 866200 prefetched. (Queue: 7/20)
2024-10-18T10:56:15.710-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:15.889-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866200 to be written Retrying after error: BlockNotWritten(866200)
2024-10-18T10:56:15.926-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:15.939-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866201 to be written Retrying after error: BlockNotWritten(866201)
2024-10-18T10:56:16.017-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866201 and target height 866206
2024-10-18T10:56:16.018-04:00 - [   DEBUG] - RS Fetcher - Write height=866201 max_height=866206 progress="99.99" avg_bps="1.05" avg_eps="1.05" total_elapsed="8" remaining_hrs="0.00" f_c_len=0 e_c_len=0 o_c_len=0 w_c_len=0 r_c_len=0 c_c_len=1 total_num_entries=9
2024-10-18T10:56:16.394-04:00 - [   ERROR] - API Server did not stop in time. Terminating...
2024-10-18T10:56:16.394-04:00 - [    INFO] - Stopping API Status Poller...
2024-10-18T10:56:16.560-04:00 - [   DEBUG] - Block 866201 prefetched. (Queue: 8/20)
2024-10-18T10:56:16.560-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:16.636-04:00 - [    INFO] - Stopping API Server v1...
2024-10-18T10:56:16.944-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866201 to be written Retrying after error: BlockNotWritten(866201)
2024-10-18T10:56:16.986-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866202 to be written Retrying after error: BlockNotWritten(866202)
2024-10-18T10:56:17.068-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866202 and target height 866206
2024-10-18T10:56:17.069-04:00 - [   DEBUG] - RS Fetcher - Write height=866202 max_height=866206 progress="99.99" avg_bps="1.04" avg_eps="1.04" total_elapsed="9" remaining_hrs="0.00" f_c_len=0 e_c_len=0 o_c_len=0 w_c_len=0 r_c_len=0 c_c_len=1 total_num_entries=10
2024-10-18T10:56:17.276-04:00 - [   DEBUG] - Block 866202 prefetched. (Queue: 9/20)
2024-10-18T10:56:17.277-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:17.797-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:17.991-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866202 to be written Retrying after error: BlockNotWritten(866202)
2024-10-18T10:56:18.027-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:18.122-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866203 and target height 866206
2024-10-18T10:56:18.123-04:00 - [   DEBUG] - RS Fetcher - Write height=866203 max_height=866206 progress="100.00" avg_bps="1.03" avg_eps="1.03" total_elapsed="10" remaining_hrs="0.00" f_c_len=0 e_c_len=0 o_c_len=0 w_c_len=0 r_c_len=0 c_c_len=1 total_num_entries=11
2024-10-18T10:56:18.388-04:00 - [   DEBUG] - Block 866203 prefetched. (Queue: 10/20)
2024-10-18T10:56:18.388-04:00 - [   DEBUG] - Prefetch queue initialized.
2024-10-18T10:56:18.388-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:18.826-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:19.045-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866203 to be written Retrying after error: BlockNotWritten(866203)
2024-10-18T10:56:19.122-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:19.167-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866204 and target height 866206
2024-10-18T10:56:19.168-04:00 - [   DEBUG] - RS Fetcher - Write height=866204 max_height=866206 progress="100.00" avg_bps="1.02" avg_eps="1.02" total_elapsed="11" remaining_hrs="0.00" f_c_len=0 e_c_len=0 o_c_len=0 w_c_len=0 r_c_len=0 c_c_len=1 total_num_entries=12
2024-10-18T10:56:19.762-04:00 - [   DEBUG] - Block 866204 prefetched. (Queue: 11/20)
2024-10-18T10:56:19.762-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
^C2024-10-18T10:56:20.056-04:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 471, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 773, in start_all
    asset_conservation_checker.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 696, in stop
    time.sleep(0.1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 50, in handle_interrupt_signal
    raise KeyboardInterrupt(f"Received signal {signal.strsignal(signum)}")
KeyboardInterrupt: Received signal Interrupt: 2
Unhandled Exception2024-10-18T10:56:20.058-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 471, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 773, in start_all
    asset_conservation_checker.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 696, in stop
    time.sleep(0.1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 50, in handle_interrupt_signal
    raise KeyboardInterrupt(f"Received signal {signal.strsignal(signum)}")
KeyboardInterrupt: Received signal Interrupt: 2
2024-10-18T10:56:20.089-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866204 to be written Retrying after error: BlockNotWritten(866204)
2024-10-18T10:56:20.133-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866205 to be written Retrying after error: BlockNotWritten(866205)
2024-10-18T10:56:20.229-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866205 and target height 866206
2024-10-18T10:56:20.229-04:00 - [   DEBUG] - RS Fetcher - Write height=866205 max_height=866206 progress="100.00" avg_bps="1.01" avg_eps="1.01" total_elapsed="12" remaining_hrs="0.00" f_c_len=0 e_c_len=0 o_c_len=0 w_c_len=0 r_c_len=0 c_c_len=1 total_num_entries=13
2024-10-18T10:56:20.574-04:00 - [   DEBUG] - Block 866205 prefetched. (Queue: 12/20)
2024-10-18T10:56:20.575-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:21.070-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:21.138-04:00 - [   DEBUG] - RS Fetcher - Timedout waiting for block at index 866205 to be written Retrying after error: BlockNotWritten(866205)
2024-10-18T10:56:21.221-04:00 - [   DEBUG] - RS Fetcher - Writing batch of length 1 with max height 866206 and target height 866206
2024-10-18T10:56:21.847-04:00 - [   DEBUG] - Block 866206 prefetched. (Queue: 13/20)
2024-10-18T10:56:21.847-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:22.054-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:22.609-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:23.233-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:23.644-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:24.229-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
2024-10-18T10:56:24.559-04:00 - [   DEBUG] - No block fetched. Waiting before next fetch.
^CException ignored in: <module 'threading' from '/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 50, in handle_interrupt_signal
    raise KeyboardInterrupt(f"Received signal {signal.strsignal(signum)}")
KeyboardInterrupt: Received signal Interrupt: 2
adam@Adams-MacBook-Pro ~/D/w/C/C/c/counterparty-core (develop=) > 
```

**Comment by adamkrellenstein** [comment]
fixed
