### ISSUE TITLE
`ParseTransactionError: Insufficient funds.`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2441]
On community member's node:
```
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 201, in parse_tx
counterparty-core-1  |     fairminter.parse(db, tx, message)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/fairminter.py", line 522, in parse
counterparty-core-1  |     ledger.debit(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 321, in debit
counterparty-core-1  |     remove_from_balance(db, address, asset, quantity, tx_index, utxo_address)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 259, in remove_from_balance
counterparty-core-1  |     raise DebitError("Insufficient funds.")
counterparty-core-1  | counterpartycore.lib.ledger.DebitError: Insufficient funds.
counterparty-core-1  |
counterparty-core-1  | During handling of the above exception, another exception occurred:
counterparty-core-1  |
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 753, in start_all
counterparty-core-1  |     blocks.catch_up(db)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1348, in catch_up
counterparty-core-1  |     tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1262, in parse_new_block
counterparty-core-1  |     new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 356, in parse_block
counterparty-core-1  |     raise e
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 349, in parse_block
counterparty-core-1  |     parse_tx(db, tx)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 247, in parse_tx
counterparty-core-1  |     raise exceptions.ParseTransactionError(f"{e}")  # noqa: B904
counterparty-core-1  | counterpartycore.lib.exceptions.ParseTransactionError: Insufficient funds.
```

**Comment by adamkrellenstein** [comment]
Would this be fixed in v10.5.0 anyway?

**Comment by adamkrellenstein** [comment]
on my node:
```
2024-10-18T13:19:43.881-04:00 - [    INFO] - Block 866218 - Parsing complete. L: 8235c05, TX: 27de523, M: 78c02e5 (350.61s)
2024-10-18T13:19:48.390-04:00 - [    INFO] - Block 866219
2024-10-18T13:19:49.123-04:00 - [    INFO] - Block 866219 - Fair minter opened for ORTUS by 1MZUaVy6y7vmwh2MqMKTFy2JiqXteyevpN.
2024-10-18T13:19:49.126-04:00 - [ WARNING] - ParseTransactionError for tx 60a05e11454eb0856bcde91bf6b1a8aee90fecb890e6a4ad33877af6e519d38a: Insufficient funds.
2024-10-18T13:19:49.127-04:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 201, in parse_tx
    fairminter.parse(db, tx, message)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/messages/fairminter.py", line 522, in parse
    ledger.debit(
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/ledger.py", line 321, in debit
    remove_from_balance(db, address, asset, quantity, tx_index, utxo_address)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/ledger.py", line 259, in remove_from_balance
    raise DebitError("Insufficient funds.")
counterpartycore.lib.ledger.DebitError: Insufficient funds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 753, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1348, in catch_up
    tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1262, in parse_new_block
    new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 356, in parse_block
    raise e
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 349, in parse_block
    parse_tx(db, tx)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 247, in parse_tx
    raise exceptions.ParseTransactionError(f"{e}")  # noqa: B904
counterpartycore.lib.exceptions.ParseTransactionError: Insufficient funds.
2024-10-18T13:19:49.130-04:00 - [    INFO] - Stopping API Server...
2024-10-18T13:19:49.133-04:00 - [    INFO] - Stopping API Watcher...
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
```

**Comment by adamkrellenstein** [comment]
on my other server:

<img width="1479" alt="image" src="https://github.com/user-attachments/assets/81ad95bc-22ab-4e6e-b83a-c84332edaf0c">

**Comment by pinnate-modo** [comment]
Hit this, too.

**Comment by reinamora137** [comment]
this was the compose request I believe

```
compose/fairminter?asset=ORTUS&encoding=multisig&lock_quantity=true&divisible=false&max_mint_per_tx=100000&hard_cap=1000000000&description='STAMP:'&allow_unconfirmed_inputs=true&exact_fee=100000&lock_description=true
```

**Comment by adamkrellenstein** [comment]
fixed!
