### ISSUE TITLE
Missing Protocol Changes File Creates a Mess

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2456]
This error is *not* presenting the way it should.

```
------------------------------ START ------------------------------

2024-10-18T21:06:16.913-04:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-10-18T21:06:16.917-04:00 - [    INFO] - Initializing database...
2024-10-18T21:06:16.920-04:00 - [    INFO] - Running PRAGMA optimize...
2024-10-18T21:06:17.272-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:06:17.612-04:00 - [    INFO] - Starting API Watcher...
2024-10-18T21:06:17.612-04:00 - [    INFO] - Starting API Server...
2024-10-18T21:06:17.724-04:00 - [    INFO] - Starting API Server v1...
2024-10-18T21:06:17.724-04:00 - [    INFO] - Catching up...
2024-10-18T21:06:17.819-04:00 - [    INFO] - Catch up complete.
2024-10-18T21:06:17.819-04:00 - [    INFO] - Watching for new blocks...
2024-10-18T21:07:29.798-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.802-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.806-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.810-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.952-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.064-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.178-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.330-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.446-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.546-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.660-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.821-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.930-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:31.068-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:31.177-04:00 - [ WARNING] - Unable to check Counterparty version.
```

**Comment by adamkrellenstein** [comment]
```
------------------------------ START ------------------------------

2024-10-18T21:06:16.913-04:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-10-18T21:06:16.917-04:00 - [    INFO] - Initializing database...
2024-10-18T21:06:16.920-04:00 - [    INFO] - Running PRAGMA optimize...
2024-10-18T21:06:17.272-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:06:17.612-04:00 - [    INFO] - Starting API Watcher...
2024-10-18T21:06:17.612-04:00 - [    INFO] - Starting API Server...
2024-10-18T21:06:17.724-04:00 - [    INFO] - Starting API Server v1...
2024-10-18T21:06:17.724-04:00 - [    INFO] - Catching up...
2024-10-18T21:06:17.819-04:00 - [    INFO] - Catch up complete.
2024-10-18T21:06:17.819-04:00 - [    INFO] - Watching for new blocks...
2024-10-18T21:07:29.798-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.802-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.806-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.810-04:00 - [    INFO] - Mempool - 100000000000 MINTS minted for 0 XCP by 1XEgHAwGnfxZBJQcXKh1fZ4aNwzUpDS8v
2024-10-18T21:07:29.952-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.064-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.178-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.330-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.446-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.546-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.660-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.821-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:30.930-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:31.068-04:00 - [ WARNING] - Unable to check Counterparty version.
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 974, in software_version
    versions = json.loads(response.text)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-18T21:07:31.177-04:00 - [ WARNING] - Unable to check Counterparty version.
```

**Comment by adamkrellenstein** [comment]
fixed!

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/3035/commits/5f0f65f7bb8bfe170cd21a8c4221d4cfdc8333f6
