### ISSUE TITLE
Ugly Failure on Version Mismatch

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2533]
```
2024-10-21T17:20:19.471-04:00 - [    INFO] - RS Fetcher - Connected
2024-10-21T17:20:19.472-04:00 - [    INFO] - RS Fetcher - Initialized
2024-10-21T17:20:19.472-04:00 - [   ERROR] - Fetcher version mismatch. Expected: 10.5.0, Got: 10.5.0-rc.1. Please re-compile `counterparty-rs`.
2024-10-21T17:20:19.472-04:00 - [   ERROR] - Failed to initialize fetcher: Fetcher version mismatch 10.5.0 != 10.5.0-rc.1.. Retrying in 5 seconds...
2024-10-21T17:20:19.472-04:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 781, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1341, in catch_up
    fetcher.start(util.CURRENT_BLOCK_INDEX + 1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 61, in start
    raise e
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 55, in start
    raise ValueError(
ValueError: Fetcher version mismatch 10.5.0 != 10.5.0-rc.1.
2024-10-21T17:20:19.474-04:00 - [    INFO] - Stopping API Server...
2024-10-21T17:20:19.481-04:00 - [    INFO] - Stopping API Watcher...
2024-10-21T17:20:19.592-04:00 - [    INFO] - API Watcher - Catch up completed.
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_server.py", line 416, in run_api_server
    wsgi_server.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/wsgi.py", line 261, in run
    self.server.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/wsgi.py", line 243, in run
    self.server.run()
  File "/opt/homebrew/lib/python3.10/site-packages/waitress/server.py", line 325, in run
    self.asyncore.loop(
  File "/opt/homebrew/lib/python3.10/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/opt/homebrew/lib/python3.10/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
OSError: [Errno 9] Bad file descriptor
2024-10-21T17:20:21.482-04:00 - [   ERROR] - API Server did not stop in time. Terminating...
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/3035/commits/cdca458e0598aaaa47e00ff3bf32a443833c36bf
