### ISSUE TITLE
Asset Conservation Check Failed with `develop`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2535]
```
2024-10-21T17:23:55.926-04:00 - [    INFO] - Block 866754 - Parsing complete. L: 20d07c1, TX: 56c99c3, M: 3193eb0 (0.03s)
2024-10-21T17:23:55.933-04:00 - [    INFO] - Block 866755
2024-10-21T17:23:55.982-04:00 - [    INFO] - Block 866755 - Order opened for 1 TALISMANCARD at 15LtfdyJ (1180bea) [open]
2024-10-21T17:23:55.996-04:00 - [    INFO] - Block 866755 - Order match for 2500000000 XCP against 1 TALISMANCARD (5274eb0_1180bea) [completed]
2024-10-21T17:23:56.001-04:00 - [    INFO] - Block 866755 - Order opened for 100 SLACKCARD at bc1qcc6d (861e5b6) [open]
2024-10-21T17:23:56.006-04:00 - [    INFO] - Block 866755 - Order opened for 1 STBNIMBUS at 1LzF33fG (0a0ee04) [open]
2024-10-21T17:23:56.015-04:00 - [    INFO] - Block 866755 - Order match for 2500000000 XCP against 1 STBNIMBUS (9bf93f9_0a0ee04) [completed]
2024-10-21T17:23:56.022-04:00 - [    INFO] - Block 866755 - Send (Enhanced) TRUMPWINS from 1LSbNkNG to 1CZ2VVEn (284418f) [valid]
^C2024-10-21T17:23:58.764-04:00 - [    INFO] - Stopping API Watcher...
2024-10-21T17:23:58.767-04:00 - [ WARNING] - Keyboard interrupt!
2024-10-21T17:23:58.831-04:00 - [    INFO] - Stopping API Server...
2024-10-21T17:24:00.840-04:00 - [   ERROR] - API Server did not stop in time. Terminating...
2024-10-21T17:24:00.840-04:00 - [    INFO] - Stopping API Status Poller...
2024-10-21T17:24:01.229-04:00 - [    INFO] - Stopping API Server v1...
2024-10-21T17:24:19.412-04:00 - [   ERROR] - Asset conservation check failed: 2592113.04348124 XCP issued ≠ 2593445.97457738 XCP held
2024-10-21T17:24:19.479-04:00 - [   ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 497, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 801, in start_all
    asset_conservation_checker.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 722, in stop
    time.sleep(0.1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 50, in handle_interrupt_signal
    raise KeyboardInterrupt(f"Received signal {signal.strsignal(signum)}")
KeyboardInterrupt: Received signal Interrupt: 2
Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 497, in main
    server.start_all(args)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 801, in start_all
    asset_conservation_checker.stop()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 722, in stop
    time.sleep(0.1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 50, in handle_interrupt_signal
    raise KeyboardInterrupt(f"Received signal {signal.strsignal(signum)}")
KeyboardInterrupt: Received signal Interrupt: 2
```

**Comment by ouziel-slama** [comment]
```
$ sqlite3 counterparty.db 
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select * from credits where address='1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr' and asset='XCP';
866184|1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr|XCP|100000000|dispense|525f0c3af12319e5a0936593dfa82a1b38a53fb95a07af513fa8debdc15e2884|2773059||
866663|1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr|XCP|100000000|dispense|c7e97b2529a006c87690139187d21cf57bd5ed03281e5848ceeee4561641493c|2950309||
sqlite> select * from balances where address='1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr' and asset='XCP';
1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr|XCP|100000000|866184|2773059||
1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr|XCP|200000000|866663|2950309||
sqlite> .quit
ouziel@counterparty:~/.local/share/counterparty$ sqlite3 asset_conservation.db 
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select * from credits where address='1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr' and asset='XCP';
866184|1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr|XCP|100000000|dispense|525f0c3af12319e5a0936593dfa82a1b38a53fb95a07af513fa8debdc15e2884|2773059||
866663|1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr|XCP|100000000|dispense|c7e97b2529a006c87690139187d21cf57bd5ed03281e5848ceeee4561641493c|2950309||
sqlite> select * from balances where address='1BvnyiJZf7zbXkiuSndR6M7tdgopw9RJSr' and asset='XCP';
sqlite> .quit
```

**Comment by adamkrellenstein** [comment]
This seems like a database corruption issue. Doesn't seem possible in the logic. Also asset conservation checks will detect 100% of these problems.
