### ISSUE TITLE
Broken Log Rotation

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2583]
```
2024-10-24T16:01:12.351-04:00 - [    INFO] - Stopping RSFetcher thread...
2024-10-24T16:01:20.715-04:00 - [    INFO] - RSFetcher thread stopped.
2024-10-24T16:01:20.716-04:00 - [    INFO] - Catch up complete.
2024-10-24T16:01:20.723-04:00 - [    INFO] - Watching for new blocks...
--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/handlers.py", line 74, in emit
    self.doRollover()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/handlers.py", line 175, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/adam/Library/Logs/counterparty/server.log.18' -> '/Users/adam/Library/Logs/counterparty/server.log.19'
Call stack:
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 938, in run
    self.follow()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 945, in follow
    last_parsed_event = parse_next_event(self.api_db, self.ledger_db, self)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 759, in parse_next_event
    check_event_hashes(api_db, ledger_db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 733, in check_event_hashes
    logger.trace("API Watcher - Checking event hashes...")
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/log.py", line 33, in trace
    self._log(logging.TRACE, msg, args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/log.py", line 187, in locked_emit
    original_emit(record)
Message: 'API Watcher - Checking event hashes...'
Arguments: ()
2024-10-24T16:04:27.651-04:00 - [    INFO] - Mempool - Move PORPEPELAMBO from utxo: 6eff8e31a4b29d7d56ecdea77bd3e1f1999be96f6d958cffb99dd859458a316f:0 to utxo: 3b32f22ba45ad535505c5cd2aac3efc01108f7d293993385ca0f116bb6a7cef2:0 (3b32f22ba45ad535505c5cd2aac3efc01108f7d293993385ca0f116bb6a7cef2)
2024-10-24T16:04:27.658-04:00 - [    INFO] - Mempool - Send (Enhanced
```

**Comment by adamkrellenstein** [comment]
```
~/L/L/counterparty > ls
fetcher.log          server.log.7               server.log.gunicorn.14800  server.log.gunicorn.14819  server.log.gunicorn.14837  server.log.gunicorn.14855  server.log.gunicorn.14873  server.log.gunicorn.14892
fetcher.log.2        server.log.8               server.log.gunicorn.14801  server.log.gunicorn.14820  server.log.gunicorn.14838  server.log.gunicorn.14856  server.log.gunicorn.14874  server.log.gunicorn.14893
fetcher.log.3        server.log.9               server.log.gunicorn.14802  server.log.gunicorn.14821  server.log.gunicorn.14839  server.log.gunicorn.14857  server.log.gunicorn.14875  server.log.gunicorn.14894
fetcher.testnet.log  server.log.10              server.log.gunicorn.14803  server.log.gunicorn.14822  server.log.gunicorn.14840  server.log.gunicorn.14858  server.log.gunicorn.14876  server.log.gunicorn.14895
log_analysis.py      server.log.11              server.log.gunicorn.14804  server.log.gunicorn.14823  server.log.gunicorn.14841  server.log.gunicorn.14859  server.log.gunicorn.14877  server.log.gunicorn.14896
server.access.log    server.log.12              server.log.gunicorn.14805  server.log.gunicorn.14824  server.log.gunicorn.14842  server.log.gunicorn.14860  server.log.gunicorn.14878  server.testnet.access.log
server.access.log.1  server.log.13              server.log.gunicorn.14806  server.log.gunicorn.14825  server.log.gunicorn.14843  server.log.gunicorn.14861  server.log.gunicorn.14879  server.testnet.log
server.access.log.2  server.log.14              server.log.gunicorn.14807  server.log.gunicorn.14826  server.log.gunicorn.14844  server.log.gunicorn.14862  server.log.gunicorn.14880  server.testnet.log.1
server.access.log.3  server.log.15              server.log.gunicorn.14808  server.log.gunicorn.14827  server.log.gunicorn.14845  server.log.gunicorn.14863  server.log.gunicorn.14881  server.testnet.log.2
server.access.log.4  server.log.16              server.log.gunicorn.14809  server.log.gunicorn.14828  server.log.gunicorn.14846  server.log.gunicorn.14864  server.log.gunicorn.14882  server.testnet.log.3
server.access.log.5  server.log.17              server.log.gunicorn.14810  server.log.gunicorn.14829  server.log.gunicorn.14847  server.log.gunicorn.14865  server.log.gunicorn.14883  server.testnet.log.4
server.log           server.log.18              server.log.gunicorn.14811  server.log.gunicorn.14830  server.log.gunicorn.14848  server.log.gunicorn.14866  server.log.gunicorn.14885  server.testnet.log.5
server.log.1         server.log.19              server.log.gunicorn.14813  server.log.gunicorn.14831  server.log.gunicorn.14849  server.log.gunicorn.14867  server.log.gunicorn.14886  
server.log.2         server.log.20              server.log.gunicorn.14814  server.log.gunicorn.14832  server.log.gunicorn.14850  server.log.gunicorn.14868  server.log.gunicorn.14887  
server.log.3         server.log.gunicorn.14796  server.log.gunicorn.14815  server.log.gunicorn.14833  server.log.gunicorn.14851  server.log.gunicorn.14869  server.log.gunicorn.14888  
server.log.4         server.log.gunicorn.14797  server.log.gunicorn.14816  server.log.gunicorn.14834  server.log.gunicorn.14852  server.log.gunicorn.14870  server.log.gunicorn.14889  
server.log.5         server.log.gunicorn.14798  server.log.gunicorn.14817  server.log.gunicorn.14835  server.log.gunicorn.14853  server.log.gunicorn.14871  server.log.gunicorn.14890  
server.log.6         server.log.gunicorn.14799  server.log.gunicorn.14818  server.log.gunicorn.14836  server.log.gunicorn.14854  server.log.gunicorn.14872  server.log.gunicorn.14891  
```

**Comment by adamkrellenstein** [comment]
again

```
- Order cancelled TATIANACOIN / XCP (25d1ea2) [cancelled]
2024-10-27T11:27:34.264-04:00 - [    INFO] - Block 867463 - Cancel Order 25d1ea2 (867d925) [valid]
2024-10-27T11:27:34.266-04:00 - [    INFO] - Block 867463 - Parsing complete. L: a14e17f, TX: 58f7e42, M: ab085fd (0.05s)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/handlers.py", line 74, in emit
    self.doRollover()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/handlers.py", line 175, in doRollover
    os.rename(sfn, dfn)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/adam/Library/Logs/counterparty/server.log.15' -> '/Users/adam/Library/Logs/counterparty/server.log.16'
Call stack:
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 938, in run
    self.follow()
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 945, in follow
    last_parsed_event = parse_next_event(self.api_db, self.ledger_db, self)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 779, in parse_next_event
    parse_event(api_db, next_event, watcher)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/api/api_watcher.py", line 672, in parse_event
    logger.event(f"API Watcher - Event parsed: {event['message_index']} {event['event']}")
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/log.py", line 37, in event
    self._log(logging.EVENT, msg, args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/log.py", line 187, in locked_emit
    original_emit(record)
Message: 'API Watcher - Event parsed: 18715015 BLOCK_PARSED'
Arguments: ()
2024-10-27T11:27:34.785-04:00 - [    INFO] - Block 867464
2024-10-27T11:27:34.827-04:00 - [    INFO] - Block 867464 - Send (Enhanced) A8874407951669816000 from bc1qd9sv to bc1qls6n (05b21b6) [valid]
2024-10-27T11:27:34.833-04:00 - [    INFO] - Block 867
```

```
 > ls
fetcher.log          log_analysis.py      server.access.log.3  server.log.1  server.log.5  server.log.9   server.log.13  server.log.17  server.testnet.access.log  server.testnet.log.3
fetcher.log.2        server.access.log    server.access.log.4  server.log.2  server.log.6  server.log.10  server.log.14  server.log.18  server.testnet.log         server.testnet.log.4
fetcher.log.3        server.access.log.1  server.access.log.5  server.log.3  server.log.7  server.log.11  server.log.15  server.log.19  server.testnet.log.1       server.testnet.log.5
fetcher.testnet.log  server.access.log.2  server.log           server.log.4  server.log.8  server.log.12  server.log.16  server.log.20  server.testnet.log.2       
adam@Adams-MacBook-Pro ~/L/L/counterparty > 
```

**Comment by ouziel-slama** [comment]
@adamkrellenstein I can't reproduce but most probably fixed by https://github.com/CounterpartyXCP/counterparty-core/pull/2609
