### ISSUE TITLE
Random errors on api calls

### ISSUE THREAD

**Issue by JavierCervilla** [CounterpartyXCP/counterparty-core#2584]
Random exceptions on api calls

```
counterparty-core-1  | 2024-10-25T03:52:25.753+00:00 - [   ERROR] - Exception on /v2/assets/A95428959331670606 [GET]
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1455, in wsgi_app
counterparty-core-1  |     response = self.full_dispatch_request()
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 869, in full_dispatch_request
counterparty-core-1  |     rv = self.handle_user_exception(e)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 867, in full_dispatch_request
counterparty-core-1  |     rv = self.dispatch_request()
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 852, in dispatch_request
counterparty-core-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/flask_httpauth.py", line 174, in decorated
counterparty-core-1  |     return self.ensure_sync(f)(*args, **kwargs)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/api_server.py", line 342, in handle_route
counterparty-core-1  |     result = inject_details(db, result)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/util.py", line 714, in inject_details
counterparty-core-1  |     result_list = inject_dispensers(db, result_list)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/util.py", line 668, in inject_dispensers
counterparty-core-1  |     dispenser_info = ledger.get_dispensers_info(db, dispenser_list)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 1438, in get_dispensers_info
counterparty-core-1  |     cursor = db.cursor()
counterparty-core-1  | apsw.ConnectionClosedError: The connection has been closed
```

**Comment by JavierCervilla** [comment]
perfect sir, thanks

**Comment by adamkrellenstein** [comment]
Yeah, this is a bunch of separate issues. We're tracking them all independently.
