### ISSUE TITLE
Cleaner Gunicorn Shutdown

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2621]
**Exhibit A**

```
2024-10-28T23:40:18.765+00:00 - [ WARNING] - Stopping Gunicorn
2024-10-28T23:40:18.765+00:00 - [ WARNING] - Stopping Gunicorn
2024-10-28T23:40:18.765+00:00 - [    INFO] - Stopping WSGI Server thread...
2024-10-28T23:40:18.765+00:00 - [    INFO] - API Watcher thread stopped.
2024-10-28T23:40:18.765+00:00 - [ WARNING] - Stopping Gunicorn
2024-10-28T23:40:18.766+00:00 - [    INFO] - Stopping WSGI Server thread...
2024-10-28T23:40:18.765+00:00 - [    INFO] - API Watcher thread stopped.
2024-10-28T23:40:18.767+00:00 - [    INFO] - Stopping WSGI Server thread...
2024-10-28T23:40:18.767+00:00 - [ WARNING] - Stopping Gunicorn
2024-10-28T23:40:18.765+00:00 - [ WARNING] - Stopping Gunicorn
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955891) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955881) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955924) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955919) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955899) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955909) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955883) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955911) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955906) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955875) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955897) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955903) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955893) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955901) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955917) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955879) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955895) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955922) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955927) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955942) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955889) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955930) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955937) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955914) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955932) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955940) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955934) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955945) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955887) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955949) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955951) was sent SIGKILL! Perhaps out of memory?
[2024-10-28 23:40:18 +0000] [1955849] [ERROR] Worker (pid:1955954) was sent SIGKILL! Perhaps out of memory?
2024-10-28T23:40:20.626+00:00 - [   ERROR] - API Server process did not stop in time. Terminating forcefully...
2024-10-28T23:40:20.626+00:00 - [    INFO] - API Server process stopped.
2024-10-28T23:40:20.626+00:00 - [    INFO] - Stopping API v1 Status Poller thread...
2024-10-28T23:40:20.627+00:00 - [    INFO] - API v1 Status Poller thread stopped.
2024-10-28T23:40:20.628+00:00 - [    INFO] - API v1 Status Poller thread stopped.
2024-10-28T23:40:20.628+00:00 - [    INFO] - Stopping API Server v1 thread...
2024-10-28T23:40:21.107+00:00 - [    INFO] - Closing database connections...
2024-10-28T23:40:21.114+00:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-10-28T23:40:21.116+00:00 - [    INFO] - Shutting down logging...
2024-10-28T23:40:21.128+00:00 - [ WARNING] - Database WAL file detected. To ensure no data corruption has occurred, run `counterparty-server check-db`.
2024-10-28T23:40:21.129+00:00 - [   DEBUG] - Cleaning up WAL and SHM files...
2024-10-28T23:40:21.131+00:00 - [   DEBUG] - SQLITE_LOG: recovered 926 frames from WAL file /ramdisk/counterparty/counterparty.api.db-wal (283) SQLITE_NOTICE_RECOVER_WAL
2024-10-28T23:40:21.137+00:00 - [    INFO] - Shutdown complete.
```

**Exhibit B**
```
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48439) was sent SIGKILL! Perhaps out of memory?
2024-11-16T14:43:27.133-05:00 - [ WARNING] - Stopping Gunicorn
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48440) was sent SIGKILL! Perhaps out of memory?
--- Logging error ---
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48441) was sent SIGKILL! Perhaps out of memory?
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48438) was sent SIGKILL! Perhaps out of memory?
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48447) was sent SIGKILL! Perhaps out of memory?
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48444) was sent SIGKILL! Perhaps out of memory?
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48446) was sent SIGKILL! Perhaps out of memory?
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
  File "/opt/homebrew/lib/python3.10/site-packages/gunicorn/arbiter.py", line 553, in reap_workers
    self.log.error(msg)
  File "/opt/homebrew/lib/python3.10/site-packages/gunicorn/glogging.py", line 271, in error
    self.error_log.error(msg, *args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1108, in emit
    self.handleError(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1021, in handleError
    sys.stderr.write('--- Logging error ---\n')
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
```

**Exhibit C**

https://counterparty.sentry.io/issues/6041592970?alert_rule_id=15343752&alert_type=issue&groupId=6041592970&notification_uuid=adc3227d-c68a-46b8-8917-2a76418b37c9&pageEnd=2024-11-04T21%3A11%3A38.112&pageStart=2024-11-03T21%3A11%3A38.112&project=4507062633365504&referrer=slack&source=issue_details

<img width="873" alt="Capture d’écran 2024-11-04 à 10 15 22" src="https://github.com/user-attachments/assets/9ebed269-157e-4b6e-b4d9-131f717bad91">

**Comment by ouziel-slama** [comment]
already done
