### ISSUE TITLE
better error handling for port taken 

### ISSUE THREAD

**Issue by dime-squanderer** [CounterpartyXCP/counterparty-core#2669]
```
venv)  ~/Library/Application Support/counterparty/ /Users/dime/counterparty/counterparty-core/venv/bin/python /opt/homebrew/bin/counterparty-server --testnet start --indexd-port 28432


Counterparty Core v10.6.1
Verbosity: 0
Quiet: False
Network: testnet
Configuration File: /Users/dime/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/dime/Library/Application Support/counterparty/counterparty.testnet.db
Counterparty API Database: /Users/dime/Library/Application Support/counterparty/counterparty.testnet.api.db
Rust Fetcher Database: /Users/dime/Library/Caches/counterparty/fetcherdb.testnet
Server Log: /Users/dime/Library/Logs/counterparty/server.testnet.log
API Access Log: /Users/dime/Library/Logs/counterparty/server.testnet.access.log

------------------------------ START ------------------------------

2024-11-06T19:23:47.330-05:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-11-06T19:23:47.338-05:00 - [    INFO] - Initializing database...
2024-11-06T19:23:47.344-05:00 - [    INFO] - Running PRAGMA optimize...
2024-11-06T19:23:48.652-05:00 - [    INFO] - Starting API Watcher thread...
2024-11-06T19:23:48.702-05:00 - [    INFO] - Starting Parent Process Checker thread...
2024-11-06T19:23:48.703-05:00 - [    INFO] - Starting WSGI Server: waitress
2024-11-06T19:23:48.705-05:00 - [   ERROR] - Exception in API Server process!
2024-11-06T19:23:48.706-05:00 - [    INFO] - Stopping API Watcher thread...
2024-11-06T19:23:48.725-05:00 - [    INFO] - API Watcher - Catch up completed.
2024-11-06T19:23:48.726-05:00 - [    INFO] - API Watcher thread stopped.
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dime/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_server.py", line 438, in run_api_server
    raise e
  File "/Users/dime/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/api_server.py", line 429, in run_api_server
    wsgi_server = wsgi.WSGIApplication(app, args=args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dime/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/wsgi.py", line 259, in __init__
    self.server = WaitressApplication(self.app, self.args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dime/counterparty/counterparty-core/counterparty-core/counterpartycore/lib/api/wsgi.py", line 237, in __init__
    self.server = waitress.server.create_server(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dime/counterparty/counterparty-core/venv/lib/python3.12/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
                ^^^^^^^^^^^^^^
  File "/Users/dime/counterparty/counterparty-core/venv/lib/python3.12/site-packages/waitress/server.py", line 243, in __init__
    self.bind_server_socket()
  File "/Users/dime/counterparty/counterparty-core/venv/lib/python3.12/site-packages/waitress/server.py", line 364, in bind_server_socket
    self.bind(sockaddr)
  File "/Users/dime/counterparty/counterparty-core/venv/lib/python3.12/site-packages/waitress/wasyncore.py", line 395, in bind
    return self.socket.bind(addr)
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 48] Address already in use
^C2024-11-06T19:24:04.789-05:00 - [ WARNING] - Keyboard interrupt received. Shutting down...
2024-11-06T19:24:04.791-05:00 - [    INFO] - Stopping API Server process...
2024-11-06T19:24:04.792-05:00 - [    INFO] - API Server process stopped.
2024-11-06T19:24:04.793-05:00 - [    INFO] - Closing database connections...
2024-11-06T19:24:04.796-05:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-11-06T19:24:04.796-05:00 - [    INFO] - Shutting down logging...
2024-11-06T19:24:04.798-05:00 - [    INFO] - Shutdown complete.
```
```
(venv)  ~/Library/Application Support/counterparty/ /Users/dime/counterparty/counterparty-core/venv/bin/python /opt/homebrew/bin/counterparty-server --testnet start --indexd-port 28432 --wsgi-server=werkzeug


Counterparty Core v10.6.1
Verbosity: 0
Quiet: False
Network: testnet
Configuration File: /Users/dime/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/dime/Library/Application Support/counterparty/counterparty.testnet.db
Counterparty API Database: /Users/dime/Library/Application Support/counterparty/counterparty.testnet.api.db
Rust Fetcher Database: /Users/dime/Library/Caches/counterparty/fetcherdb.testnet
Server Log: /Users/dime/Library/Logs/counterparty/server.testnet.log
API Access Log: /Users/dime/Library/Logs/counterparty/server.testnet.access.log

------------------------------ START ------------------------------

2024-11-06T19:24:37.958-05:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-11-06T19:24:37.964-05:00 - [    INFO] - Initializing database...
2024-11-06T19:24:37.969-05:00 - [    INFO] - Running PRAGMA optimize...
2024-11-06T19:24:39.138-05:00 - [    INFO] - Starting API Watcher thread...
2024-11-06T19:24:39.186-05:00 - [    INFO] - Starting Parent Process Checker thread...
2024-11-06T19:24:39.186-05:00 - [    INFO] - Starting WSGI Server: werkzeug
Address already in use
Port 14000 is in use by another program. Either identify and stop that program, or start the server with a different port.
2024-11-06T19:24:39.188-05:00 - [    INFO] - Stopping API Watcher thread...
2024-11-06T19:24:39.213-05:00 - [    INFO] - API Watcher - Catch up completed.
2024-11-06T19:24:39.213-05:00 - [    INFO] - API Watcher thread stopped.
^C2024-11-06T19:24:48.248-05:00 - [ WARNING] - Keyboard interrupt received. Shutting down...
2024-11-06T19:24:48.250-05:00 - [    INFO] - Stopping API Server process...
2024-11-06T19:24:48.250-05:00 - [    INFO] - API Server process stopped.
2024-11-06T19:24:48.251-05:00 - [    INFO] - Closing database connections...
2024-11-06T19:24:48.253-05:00 - [    INFO] - Stopping AddrIndexRs thread...
2024-11-06T19:24:48.254-05:00 - [    INFO] - Shutting down logging...
2024-11-06T19:24:48.256-05:00 - [    INFO] - Shutdown complete.
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/3028/commits/aa61fbe345064ffaef0d4d78799f7a78424328f9
