### ISSUE TITLE
RSFetcher Crashes on Startup

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2678]
```
> counterparty-server --data-dir=/Users/adam/Library/Application\ Support/counterparty/double/ start

Counterparty Core v10.6.1
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/counterparty/double/counterparty.db
Counterparty API Database: /Users/adam/Library/Application Support/counterparty/double/counterparty.api.db
Rust Fetcher Database: /Users/adam/Library/Caches/counterparty/fetcherdb
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-11-10T14:00:22.282-05:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-11-10T14:00:22.480-05:00 - [ WARNING] - Database WAL file detected. To ensure no data corruption has occurred, run `counterpary-server check-db`.
2024-11-10T14:00:22.529-05:00 - [    INFO] - Initializing database...
2024-11-10T14:00:22.560-05:00 - [    INFO] - Running PRAGMA optimize...
2024-11-10T14:00:23.135-05:00 - [    INFO] - Starting API Watcher thread...
2024-11-10T14:00:23.164-05:00 - [    INFO] - Starting Parent Process Checker thread...
2024-11-10T14:00:23.164-05:00 - [    INFO] - Starting WSGI Server: waitress
2024-11-10T14:00:23.166-05:00 - [    INFO] - Starting WSGI Server thread...
2024-11-10T14:00:24.789-05:00 - [    INFO] - Starting v1 API Status Poller thread...
2024-11-10T14:00:24.789-05:00 - [    INFO] - Starting API Server v1 thread...
2024-11-10T14:00:24.792-05:00 - [    INFO] - Catching up...
2024-11-10T14:00:24.890-05:00 - [ WARNING] - Counterparty is currently behind Bitcoin Core. (867856 < 869748)
2024-11-10T14:00:25.014-05:00 - [    INFO] - Starting RSFetcher thread...
2024-11-10T14:00:25.016-05:00 - [    INFO] - RS Fetcher - Indexer initializing...
2024-11-10T14:00:25.016-05:00 - [    INFO] - RS Fetcher - Connecting to database: /Users/adam/Library/Caches/counterparty/fetcherdb
2024-11-10T14:00:25.022-05:00 - [    INFO] - RS Fetcher - Connected
2024-11-10T14:00:25.022-05:00 - [    INFO] - RS Fetcher - Initialized
2024-11-10T14:00:25.022-05:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight...
2024-11-10T14:00:25.022-05:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight took 139.042µs
2024-11-10T14:00:25.022-05:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight...
2024-11-10T14:00:25.040-05:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight took 17.950166ms
2024-11-10T14:00:25.040-05:00 - [   ERROR] - Failed to initialize fetcher: RPC error: JSON error: invalid type: sequence, expected a string. Retrying in 5 seconds...
2024-11-10T14:00:25.041-05:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 792, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1366, in catch_up
    fetcher.start(util.CURRENT_BLOCK_INDEX + 1)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 120, in start
    raise e
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/backend/rsfetcher.py", line 117, in start
    self.fetcher.start()
Exception: RPC error: JSON error: invalid type: sequence, expected a string
2024-11-10T14:00:25.042-05:00 - [    INFO] - Stopping API Server process...
2024-11-10T14:00:25.044-05:00 - [    INFO] - API Server process stopped.
2024-11-10T14:00:25.044-05:00 - [    INFO] - Stopping API v1 Status Poller thread...
2024-11-10T14:00:25.044-05:00 - [    INFO] - API v1 Status Poller thread stopped.
```

**Comment by adamkrellenstein** [comment]
Also the Rust process should log (at `DEBUG`) the address and port it's using to connect.
```

**Comment by adamkrellenstein** [comment]
Fixed: https://github.com/CounterpartyXCP/counterparty-core/pull/2680
