### ISSUE TITLE
Crash When Starting from Scratch

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2682]
```
> counterparty-server start

Counterparty Core v10.6.1
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/counterparty/counterparty.db
Counterparty API Database: /Users/adam/Library/Application Support/counterparty/counterparty.api.db
Rust Fetcher Database: /Users/adam/Library/Caches/counterparty/fetcherdb
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-11-10T17:26:47.753-05:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-11-10T17:26:47.754-05:00 - [    INFO] - Initializing database...
2024-11-10T17:26:47.776-05:00 - [    INFO] - Database version number updated.
2024-11-10T17:26:47.776-05:00 - [    INFO] - Running PRAGMA optimize...
2024-11-10T17:26:48.376-05:00 - [    INFO] - Add defaul value for `locked` and `reset` fields in `issuances` table...
2024-11-10T17:26:48.384-05:00 - [    INFO] - `locked` and `reset` fields updated...
2024-11-10T17:26:48.393-05:00 - [    INFO] - Create and populate `address_events` table...
2024-11-10T17:26:48.394-05:00 - [    INFO] - `address_events` tables created...
2024-11-10T17:26:48.439-05:00 - [    INFO] - Update `asset_longname` field...
2024-11-10T17:26:48.439-05:00 - [    INFO] - `asset_longname` field updated...
2024-11-10T17:26:48.444-05:00 - [    INFO] - Starting API Watcher thread...
2024-11-10T17:26:48.446-05:00 - [    INFO] - API Watcher - Catch up completed.
2024-11-10T17:26:48.471-05:00 - [    INFO] - Starting Parent Process Checker thread...
2024-11-10T17:26:48.471-05:00 - [    INFO] - Starting WSGI Server: waitress
2024-11-10T17:26:48.473-05:00 - [    INFO] - Starting WSGI Server thread...
2024-11-10T17:26:48.578-05:00 - [    INFO] - Starting v1 API Status Poller thread...
2024-11-10T17:26:48.578-05:00 - [    INFO] - Starting API Server v1 thread...
2024-11-10T17:26:48.582-05:00 - [    INFO] - Catching up...
2024-11-10T17:26:48.582-05:00 - [    INFO] - New database.
2024-11-10T17:26:48.711-05:00 - [    INFO] - Starting RSFetcher thread...
2024-11-10T17:26:48.712-05:00 - [    INFO] - RS Fetcher - Indexer initializing...
2024-11-10T17:26:48.712-05:00 - [    INFO] - RS Fetcher - Connecting to database: /Users/adam/Library/Caches/counterparty/fetcherdb
2024-11-10T17:26:48.718-05:00 - [    INFO] - RS Fetcher - Connected
2024-11-10T17:26:48.718-05:00 - [    INFO] - RS Fetcher - Initialized
2024-11-10T17:26:48.718-05:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight...
2024-11-10T17:26:48.718-05:00 - [    INFO] - RS Fetcher - First database op: GetMaxBlockHeight took 7.583µs
2024-11-10T17:26:48.718-05:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight...
2024-11-10T17:26:48.719-05:00 - [    INFO] - RS Fetcher - First Bitcoin client op: GetBlockchainHeight took 608.875µs
2024-11-10T17:26:48.719-05:00 - [    INFO] - RS Fetcher - Starting at block height: 278270
2024-11-10T17:26:48.719-05:00 - [    INFO] - RS Fetcher - Targeting block height: 869773
2024-11-10T17:26:48.719-05:00 - [    INFO] - RS Fetcher - Fetcher started
2024-11-10T17:26:49.076-05:00 - [ WARNING] - Counterparty is currently behind Bitcoin Core. (0 < 869773)
2024-11-10T17:26:49.375-05:00 - [    INFO] - Block 278270
2024-11-10T17:26:49.409-05:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 792, in start_all
    blocks.catch_up(db)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1377, in catch_up
    tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1281, in parse_new_block
    tx_index = list_tx(
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1002, in list_tx
    utxos_info[0] != ""
IndexError: list index out of range
2024-11-10T17:26:49.409-05:00 - [    INFO] - Stopping API Server process...
2024-11-10T17:26:49.411-05:00 - [    INFO] - API Server process stopped.
```

**Comment by ouziel-slama** [comment]
already fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2679/commits/102711b932cd738e665c70a969acbc721c926933
