### ISSUE TITLE
Handle reparse interruptions correctly

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-core#2702]
```
2024-11-12T17:27:34.482+00:00 - [    INFO] - Block 869900
2024-11-12T17:27:34.601+00:00 - [   DEBUG] - Block 869904 prefetched. (Queue size: 4/20)
2024-11-12T17:27:34.603+00:00 - [   DEBUG] - SQLITE_LOG: abort at 28 in [INSERT INTO blocks (block_index, block_hash, block_time, previous_block_hash, difficulty) VALUES (?, ?, ?, ?, ?)]: UNIQUE constraint failed: blocks.block_index, blocks.block_hash (1555) SQLITE_CONSTRAINT_PRIMARYKEY
2024-11-12T17:27:34.637+00:00 - [   DEBUG] - Block 869905 prefetched. (Queue size: 5/20)
2024-11-12T17:27:34.639+00:00 - [   DEBUG] - Counterparty is currently behind Bitcoin Core. (870011 < 870020)
2024-11-12T17:27:34.638+00:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 792, in start_all
    blocks.catch_up(db)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1379, in catch_up
    tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1279, in parse_new_block
    ledger.insert_record(db, "blocks", block_bindings, "NEW_BLOCK")
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 38, in insert_record
    cursor.execute(query, list(record.values()))
  File "src/cursor.c", line 169, in resetcursor
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: blocks.block_index, blocks.block_hash
```

**Comment by ouziel-slama** [comment]
fxed here https://github.com/CounterpartyXCP/counterparty-core/pull/2700/commits/18bfdeb717e45470ae1dc3722db547f295b79df1
