### ISSUE TITLE
`SQLError: no such table: assets_info` after Bootstrap

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2703]
[logs_counterparty_v10.7.0.txt.txt](https://github.com/user-attachments/files/17723252/logs_counterparty_v10.7.0.txt.txt)

**Comment by adamkrellenstein** [comment]
Okay, also seeing this: https://counterparty.sentry.io/issues/6060755065/?alert_rule_id=15343752&alert_type=issue&notification_uuid=cab276be-ee7d-422c-8ce9-23bece106c92&project=4507062633365504&referrer=slack

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/8a5d74da-7bb2-4003-930e-75ecad7ff521">

**Comment by ouziel-slama** [comment]
```
counterparty-core-1  | 2024-11-12T20:15:53.781+00:00 - [    INFO] - Block 869844
counterparty-core-1  | 2024-11-12T20:15:53.782+00:00 - [   DEBUG] - SQLITE_LOG: no such table: assets_info in "
counterparty-core-1  |         SELECT asset, asset_longname, description, issuer, divisible, locked FROM assets_info
counterparty-core-1  |         WHERE asset IN ()
counterparty-core-1  |     " (1) SQLITE_ERROR
counterparty-core-1  | 2024-11-12T20:15:53.782+00:00 - [   ERROR] - Exception caught!
counterparty-core-1  | Traceback (most recent call last):
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 792, in start_all
counterparty-core-1  |     blocks.catch_up(db)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1379, in catch_up
counterparty-core-1  |     tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1279, in parse_new_block
counterparty-core-1  |     ledger.insert_record(db, "blocks", block_bindings, "NEW_BLOCK")
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 54, in insert_record
counterparty-core-1  |     add_to_journal(db, util.CURRENT_BLOCK_INDEX, "insert", table_name, event, record | event_info)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 211, in add_to_journal
counterparty-core-1  |     log.log_event(db, block_index, message_index, event, items)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/log.py", line 286, in log_event
counterparty-core-1  |     zmq_publisher.publish_event(db, zmq_event)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/log.py", line 339, in publish_event
counterparty-core-1  |     event = inject_details(db, event)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/util.py", line 730, in inject_details
counterparty-core-1  |     result_list = inject_issuances_and_block_times(db, result_list)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/api/util.py", line 376, in inject_issuances_and_block_times
counterparty-core-1  |     issuance_by_asset = ledger.get_assets_last_issuance(db, asset_list)
counterparty-core-1  |   File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/ledger.py", line 931, in get_assets_last_issuance
counterparty-core-1  |     cursor.execute(query, asset_list)
counterparty-core-1  |   File "src/cursor.c", line 959, in APSWCursor_execute.sqlite3_prepare_v3
counterparty-core-1  | apsw.SQLError: SQLError: no such table: assets_info
counterparty-core-1  | 2024-11-12T20:15:53.790+00:00 - [    INFO] - Stopping API Server process...
````

**Comment by ouziel-slama** [comment]
problem comes from the `--enable-zmq-publisher` flag.

**Comment by ouziel-slama** [comment]
> Okay, also seeing this: https://counterparty.sentry.io/issues/6060755065/?alert_rule_id=15343752&alert_type=issue&notification_uuid=cab276be-ee7d-422c-8ce9-23bece106c92&project=4507062633365504&referrer=slack
> 
@adamkrellenstein this is a different problem, opened an issue: https://github.com/CounterpartyXCP/counterparty-core/issues/2709

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2708/commits/494e954ca02baed5d8d62acf6d3cc5977709b8ad
