### ISSUE TITLE
Ledger Hash Mismatch

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2704]
```
> counterparty-server --data-dir=/Users/adam/Library/Application\ Support/counterparty/triple reparse 866000

Counterparty Core v10.7.0
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/counterparty/triple/counterparty.db
Counterparty API Database: /Users/adam/Library/Application Support/counterparty/triple/counterparty.api.db
Rust Fetcher Database: /Users/adam/Library/Caches/counterparty/fetcherdb
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ REPARSE ------------------------------

[OK] Rolling database back to Block 866000... (in 148.43s)
[OK] Recalculating consensus hashes... (in 0.01s)
[OK] Block 869835 parsed in 0.00s [3836/3924 blocks parsed - 0:10:03/0:10:17 (0:00:13)] (in 604.09s)
Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 489, in main
    server.reparse(block_index=args.block_index)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/server.py", line 857, in reparse
    blocks.reparse(db, block_index=block_index)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 1185, in reparse
    parse_block(
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/blocks.py", line 387, in parse_block
    new_ledger_hash, found_ledger_hash = check.consensus_hash(
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/lib/check.py", line 918, in consensus_hash
    raise ConsensusError(error_message)
counterpartycore.lib.check.ConsensusError: Incorrect ledger_hash hash for block 869836.  Calculated 047fd30be903b86edfde70989350fda758db09c9baa6dab9bc25b09d003a91fe but expected cffb619abf5cbf297d3bf837369cae8e80eafb047bc26db9698d2ea6fd7cb9b9
```

**Comment by adamkrellenstein** [comment]
Weird issue! We don't want to get stuck on this if we can't reproduce it...

**Comment by ouziel-slama** [comment]
Downloaded the db and checked the last block

```
sqlite> select * from blocks order by block_index desc limit 1;
866113|0000000000000000000270e8a49183b9715382dde4906ef33bfe9af63b11c396|1729201419|00000000000000000000b74ad040b30e45aca96573cd0537e38c67914b529da5|386076365|e2feb32fa8ab97505b253b8314bee931d6cac2c4f9d285ef95716423c089ca81|ce3a2895d080c0b927a5b6b86df65f7d3d2d566175390dda4c0fe57ecfde87df|8c32a05cbc613a77445ae06aa0ae907aa7230004c3a99f40e8f0ee2d707c167c|19
```

then I run `counterparty-server start` on it:

```
2024-11-13T09:04:29.056+00:00 - [    INFO] - Client minor version number mismatch: 4 ≠ 7. Checking if a reparse is needed...
2024-11-13T09:04:29.056+00:00 - [    INFO] - Rolling database back to Block 865999...
...
...
2024-11-13T09:06:01.101+00:00 - [    INFO] - Block 866113 - Order opened for 1 RAREWOJAK at 1JBEzg8Z (126d27a) [open]
2024-11-13T09:06:01.103+00:00 - [    INFO] - 115 blocks reparsed in 80.50s.
2024-11-13T09:06:01.104+00:00 - [    INFO] - Database version number updated
...
...
2024-11-13T09:10:16.280+00:00 - [   DEBUG] - Block 866185/870106 parsed, for 72 blocks in 0h 3m 25s.
...
...
2024-11-13T10:23:13.454+00:00 - [   DEBUG] - Block 870113/870113 parsed, for 4000 blocks in 1h 16m 22s
...
...
2024-11-13T10:25:59.271+00:00 - [    INFO] - Mempool - Order opened for 1 TRANSCENDEN at 1BV65dgP (48ae269) [open]
2024-11-13T10:25:59.277+00:00 - [    INFO] - Mempool - 1 DRAGONS minted for 0 XCP by 1KUgDptRM3ncsBHZasb7tPJ7Vz8adqiQAp
```

seems to works well

**Comment by adamkrellenstein** [comment]
yeah I think it was a weird issue with pre-release versions
