### ISSUE TITLE
Exception with Missing CLI Command

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2717]
```
> counterparty-server

Counterparty Core v10.7.0
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/counterparty/counterparty.db
Counterparty State Database: /Users/adam/Library/Application Support/counterparty/counterparty.state.db
Rust Fetcher Database: /Users/adam/Library/Caches/counterparty/fetcherdb
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log
Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(cli.main())
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 487, in main
    welcome_message(args.action, server_configfile)
  File "/Users/adam/Documents/work/Counterparty/CounterpartyXCP/counterparty-core/counterparty-core/counterpartycore/cli.py", line 392, in welcome_message
    cprint(f"\n{'-' * 30} {action.upper()} {'-' * 30}\n", "green")
AttributeError: 'NoneType' object has no attribute 'upper'
adam@Adams-MacBook-Pro-2 ~/D/w/C/C/counterparty-core (apidb=) > 
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2721/commits/8618eccab110f439d18f5243f0bf4bb2a00534bc
