### ISSUE TITLE
Bad Shutdown of Logging

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2723]
```
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48439) was sent SIGKILL! Perhaps out of memory?
2024-11-16T14:43:27.133-05:00 - [ WARNING] - Stopping Gunicorn
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48440) was sent SIGKILL! Perhaps out of memory?
--- Logging error ---
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48441) was sent SIGKILL! Perhaps out of memory?
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48438) was sent SIGKILL! Perhaps out of memory?
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48447) was sent SIGKILL! Perhaps out of memory?
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48444) was sent SIGKILL! Perhaps out of memory?
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Worker (pid:48446) was sent SIGKILL! Perhaps out of memory?
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
  File "/opt/homebrew/lib/python3.10/site-packages/gunicorn/arbiter.py", line 553, in reap_workers
    self.log.error(msg)
  File "/opt/homebrew/lib/python3.10/site-packages/gunicorn/glogging.py", line 271, in error
    self.error_log.error(msg, *args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1108, in emit
    self.handleError(record)
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1021, in handleError
    sys.stderr.write('--- Logging error ---\n')
[2024-11-16 14:43:27 -0500] [48422] [ERROR] Unhandled exception in main loop
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/opt/homebrew/lib/python3.10/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
```

**Comment by adamkrellenstein** [comment]
Merged with https://github.com/CounterpartyXCP/counterparty-core/issues/2621
