### ISSUE TITLE
Couterparty server is shutdown 

### ISSUE THREAD

**Issue by kurata-yuya** [CounterpartyXCP/counterparty-core#2776]
Target block is 872,018

**Logfiles**
```
2024-11-26T06:31:33.274+00:00 - [ WARNING] - ParseTransactionError for tx dde20ff6b742ce2e75aa23d36c38317edd328432623615d8cd2249cc8b573060: Cannot unpack utxo message: too many values to unpack (expected 3)
2024-11-26T06:31:33.275+00:00 - [   ERROR] - Exception caught!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/attach.py", line 117, in unpack
    (asset, quantity, destination_vout) = data_content
ValueError: too many values to unpack (expected 3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 221, in parse_tx
    attach.parse(db, tx, message)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/attach.py", line 158, in parse
    (asset, quantity, destination_vout) = unpack(message)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/messages/attach.py", line 129, in unpack
    raise exceptions.UnpackError(f"Cannot unpack utxo message: {e}") from e
counterpartycore.lib.exceptions.UnpackError: Cannot unpack utxo message: too many values to unpack (expected 3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/server.py", line 797, in start_all
    blocks.catch_up(db)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1409, in catch_up
    tx_index, parsed_block_index = parse_new_block(db, decoded_block, tx_index=tx_index)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 1293, in parse_new_block
    new_ledger_hash, new_txlist_hash, new_messages_hash = parse_block(
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 376, in parse_block
    raise e
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 369, in parse_block
    parse_tx(db, tx)
  File "/usr/local/lib/python3.10/dist-packages/counterpartycore/lib/blocks.py", line 267, in parse_tx
    raise exceptions.ParseTransactionError(f"{e}") from e
counterpartycore.lib.exceptions.ParseTransactionError: Cannot unpack utxo message: too many values to unpack (expected 3)
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/2777
