### ISSUE TITLE
Conservation Check Failing Ungracefully

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2812]
```
2024-12-09T11:40:44.117-05:00 - [    INFO] - Ledger.Main - Block 873493 - Order opened for 129 LATOMOSI at 1GthHWTh (4e758b8) [open]
2024-12-09T11:40:44.119-05:00 - [    INFO] - Ledger.Main - Block 873493 - Parsing complete. L: 024f231, TX: 185882a, M: 56e4a67 (0.03s)
2024-12-09T11:40:44.135-05:00 - [    INFO] - Ledger.Main - Block 873494
2024-12-09T11:40:44.148-05:00 - [   ERROR] - Ledger.AssetConservationChecker - Asset conservation check failed: 499999999.99 SJCX issued ≠ 500000000.99 SJCX held
2024-12-09T11:40:44.151-05:00 - [    INFO] - Ledger.Main - Stopping RSFetcher thread...
2024-12-09T11:40:45.481-05:00 - [    INFO] - Ledger.Main - RSFetcher thread stopped.
2024-12-09T11:40:45.482-05:00 - [ WARNING] - Ledger.Main - Keyboard interrupt received. Shutting down...
2024-12-09T11:40:45.484-05:00 - [    INFO] - Ledger.Main - Stopping API v1 Status Poller thread...
2024-12-09T11:40:45.484-05:00 - [    INFO] - Ledger.Main - API v1 Status Poller thread stopped.
2024-12-09T11:40:45.484-05:00 - [    INFO] - Ledger.Main - Stopping API Server v1 thread...
2024-12-09T11:40:45.492-05:00 - [    INFO] - Ledger.Main - API Server v1 thread stopped.
2024-12-09T11:40:45.493-05:00 - [    INFO] - Ledger.Main - Stopping Asset Conservation Checker thread...
2024-12-09T11:40:45.903-05:00 - [    INFO] - API.ParentProcessChecker - Stopping WSGI Server thread...
2024-12-09T11:40:45.906-05:00 - [    INFO] - API.Main - Stopping API Server...
2024-12-09T11:40:45.908-05:00 - [    INFO] - API.Main - Stopping WSGI Server thread...
2024-12-09T11:40:45.910-05:00 - [    INFO] - API.Main - Stopping API Watcher thread...
2024-12-09T11:40:45.924-05:00 - [    INFO] - API.Main - API Watcher thread stopped.
2024-12-09T11:40:45.924-05:00 - [    INFO] - API.Main - API Server stopped.
Process Process-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/api_server.py", line 522, in run_api_server
    wsgi_server.run()
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/wsgi.py", line 238, in run
    self.server.run()
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/wsgi.py", line 217, in run
    self.server.run()
  File "/opt/homebrew/lib/python3.10/site-packages/waitress/server.py", line 325, in run
    self.asyncore.loop(
  File "/opt/homebrew/lib/python3.10/site-packages/waitress/wasyncore.py", line 245, in loop
    poll_fun(timeout, map)
  File "/opt/homebrew/lib/python3.10/site-packages/waitress/wasyncore.py", line 172, in poll
    r, w, e = select.select(r, w, e, timeout)
OSError: [Errno 9] Bad file descriptor
2024-12-09T11:40:46.162-05:00 - [    INFO] - Ledger.AssetConservationChecker - Thread stopped.
2024-12-09T11:40:46.163-05:00 - [    INFO] - Ledger.Main - Closing database connections...
2024-12-09T11:41:05.807-05:00 - [    INFO] - Ledger.Main - Stopping AddrIndexRs thread...
2024-12-09T11:41:05.808-05:00 - [    INFO] - Ledger.Main - Shutting down logging...
2024-12-09T11:41:05.808-05:00 - [    INFO] - Ledger.Main - Shutdown complete.
```

**Comment by adamkrellenstein** [comment]
This happens on `develop` even after a rollback to 872000.

**Comment by adamkrellenstein** [comment]
This also happens after a `build-state-db`.
