### ISSUE TITLE
Upgrade to `fixes` Branch Leads to Migration Error

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2819]
```
 > counterparty-server --data-dir=/Users/adam/Library/Application\ Support/counterparty/quad start

Counterparty Core v10.7.4
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/counterparty/quad/counterparty.db
Counterparty API Database: /Users/adam/Library/Application Support/counterparty/quad/counterparty.api.db
Rust Fetcher Database: /Users/adam/Library/Caches/counterparty/fetcherdb
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-12-09T18:28:00.736-05:00 - [    INFO] - Connecting to database... (SQLite 3.45.1.0)
2024-12-09T18:28:00.771-05:00 - [ WARNING] - Database WAL file detected. To ensure no data corruption has occurred, run `counterpary-server check-db`.
2024-12-09T18:28:00.774-05:00 - [    INFO] - Initializing database...
2024-12-09T18:28:00.777-05:00 - [    INFO] - Running PRAGMA optimize...
2024-12-09T18:28:01.709-05:00 - [    INFO] - Starting API Watcher thread...
2024-12-09T18:28:01.736-05:00 - [    INFO] - Starting Parent Process Checker thread...
2024-12-09T18:28:01.736-05:00 - [    INFO] - Starting WSGI Server: waitress
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-12-09T18:28:01.738-05:00 - [    INFO] - Starting WSGI Server thread...
    self.run()
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/api_watcher.py", line 972, in run
    catch_up(self.api_db, self.ledger_db, self)
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/api_watcher.py", line 723, in catch_up
    parse_event(api_db, next_event, watcher, catching_up=True)
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/api_watcher.py", line 700, in parse_event
    event["insert_rowid"] = execute_event(api_db, event)
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/lib/api/api_watcher.py", line 591, in execute_event
    cursor.execute(sql, sql_bindings)
  File "src/cursor.c", line 959, in APSWCursor_execute.sqlite3_prepare_v3
apsw.SQLError: SQLError: table transactions has no column named transaction_type
2024-12-09T18:28:01.827-05:00 - [    INFO] - Starting v1 API Status Poller thread...
2024-12-09T18:28:01.827-05:00 - [    INFO] - Starting API Server v1 thread...
2024-12-09T18:28:01.838-05:00 - [    INFO] - Catching up...
2024-12-09T18:28:01.938-05:00 - [    INFO] - Starting RSFetcher thread...
```

**Comment by ouziel-slama** [comment]
hum.. seems you mixed here a State DB from `develop` and a Ledger DB from `master`.

**Comment by ouziel-slama** [comment]
just try to run develop on bootstrap database and works well
