### ISSUE TITLE
Failing Bootstrap

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2865]
```
> counterparty-server start --catch-up=bootstrap-always

Counterparty Core v10.8.0
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/adam/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/adam/Library/Application Support/counterparty/counterparty.db
Counterparty State Database: /Users/adam/Library/Application Support/counterparty/state.db
Rust Fetcher Database: /Users/adam/Library/Caches/counterparty/fetcherdb
Server Log: /Users/adam/Library/Logs/counterparty/server.log
API Access Log: /Users/adam/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

2024-12-18T08:06:49.208-05:00 - [   ERROR] - Ledger.Main - Exception caught!
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/counterpartycore/server.py", line 760, in start_all
    bootstrap(no_confirm=True, snapshot_url=args.bootstrap_url)
TypeError: 'module' object is not callable
2024-12-18T08:06:49.208-05:00 - [    INFO] - Ledger.Main - Stopping AddrIndexRs thread...
2024-12-18T08:06:49.208-05:00 - [    INFO] - Ledger.Main - Shutting down logging...
2024-12-18T08:06:49.209-05:00 - [    INFO] - Ledger.Main - Shutdown complete.
```
```
➜  ~ counterparty-server start
➜  ~ source $HOME/repos/counterparty-core/venv/bin/activate
(venv) ➜  ~ counterparty-server start --catch-up=bootstrap-always

Counterparty Core v10.8.0
Verbosity: 0
Quiet: False
Network: mainnet
Configuration File: /Users/evan/Library/Application Support/counterparty/server.conf
Counterparty Database: /Users/evan/Library/Application Support/counterparty/counterparty.db
Counterparty State Database: /Users/evan/Library/Application Support/counterparty/state.db
Rust Fetcher Database: /Users/evan/Library/Caches/counterparty/fetcherdb
Server Log: /Users/evan/Library/Logs/counterparty/server.log
API Access Log: /Users/evan/Library/Logs/counterparty/server.access.log

------------------------------ START ------------------------------

WARNING: `counterparty-server bootstrap` downloads a recent snapshot of a Counterparty database
from a centralized server maintained by the Counterparty Core development team.
Because this method does not involve verifying the history of Counterparty transactions yourself,
the `bootstrap` command should not be used for mission-critical, commercial or public-facing nodes.
        
2024-12-18T08:13:24.427-05:00 - [    INFO] - Ledger.Main - Downloading database from https://bootstrap.counterparty.io/counterparty.latest.tar.gz...
2024-12-18T08:24:33.539-05:00 - [    INFO] - Ledger.Main - Verifying signature...
2024-12-18T08:24:45.700-05:00 - [    INFO] - Ledger.Main - Extracting database to /Users/evan/Library/Application Support/counterparty...
2024-12-18T08:25:46.374-05:00 - [   ERROR] - Ledger.Main - Exception caught!
Traceback (most recent call last):
  File "/Users/evan/repos/counterparty-core/counterparty-core/counterpartycore/server.py", line 759, in start_all
    bootstrap(no_confirm=True, snapshot_url=args.bootstrap_url)
  File "/Users/evan/repos/counterparty-core/counterparty-core/counterpartycore/server.py", line 1040, in bootstrap
    assert os.path.exists(api_database_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
2024-12-18T08:25:46.380-05:00 - [    INFO] - Ledger.Main - Stopping AddrIndexRs thread...
2024-12-18T08:25:46.380-05:00 - [    INFO] - Ledger.Main - Shutting down logging...
2024-12-18T08:25:46.381-05:00 - [    INFO] - Ledger.Main - Shutdown complete.
```

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterparty-core/pull/2867
