### ISSUE TITLE
Add support for stateless RPC connection (tolerate backend service restart/downtime)

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-core#873]
Currently counterparty-server can't recover from Bitcoin Core service restart even if it's immediate. 

```
2016-05-20-T09:42:00+0100 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 1145, in follow
    tx_index = list_tx(db, block_hash, block_index, block_time, tx_hash, tx_index, tx_hex)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 845, in list_tx
    source, destination, btc_amount, fee, data = get_tx_info(tx_hex)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 424, in get_tx_info
    tx_info = get_tx_info2(tx_hex, block_parser=block_parser)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 665, in get_tx_info2
    vin_tx = backend.getrawtransaction(ib2h(vin.prevout.hash))
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/backend/__init__.py", line 55, in getrawtransaction
    return BACKEND().getrawtransaction(tx_hash, verbose=verbose, skip_missing=skip_missing)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 230, in getrawtransaction
    return getrawtransaction_batch([tx_hash], verbose=verbose, skip_missing=skip_missing)[tx_hash]
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 291, in getrawtransaction_batch
    raise BackendRPCError('{} (txhash:: {})'.format(response['error'], tx_hash_call_id.get(response.get('id', '??'), '??')))
counterpartylib.lib.backend.addrindex.BackendRPCError: {'message': 'Loading block index...', 'code': -28} (txhash:: 633077620cae25bc0cbcbf35545d9ca3c91b338112bc7364e1bf2d5a5d8022bd)
```

(crash)

This is a problem when one has to restart bitcoind (upgrade, migration, change of settings, extended loss of connectivity due to overload, Bitcoin Core crash, etc.).

If zero-conf tx parsing (see https://github.com/CounterpartyXCP/counterparty-lib/pull/869) could be disabled perhaps this connection could be "stateless" which would be a reliability improvement for services that do not depend on zero-conf transactions (which could be useful to CP EVM users where uptime is important while zero-conf may not be?).
It would also be possible to use a floating IP to run 2 or more BC instances with 1 virtual IP and move the IP to another instance and thereby insure smooth backend failover.
##

**Comment by rubensayshi** [comment]
I'm working on making it possible to run without zero-conf enabled.

I think the problem is that the poll interval is 0.5s, so the bitcoind RPC only has 0.5s to do a restart ...\

maybe an option would be to handle that 'Loading block index' message specifically as a reload/restart

**Comment by unsystemizer** [comment]
Looking at the error output and previous bugs related to tx cache (`tx missing in rawtx cache`), I was under the impression that what causes counterparty-server to stop isn't the timeouts (thought that was set by `requests-timeout`, btw) but inconsistency between the transaction caches of Bitcoin Core and that of Counterparty server. But the code doesn't lie, so if that's what it is then my impression is wrong.

I just tried with `backend-poll-interval` 120s (one instance used the default setting, the other 120s) and after Bitcoin Core was restarted, the one with the default setting managed to continue, while the one with 120s got `tx missing in rawtx cache` and crashed.  (The both have `requests-timeout = 300`).

I wouldn't say this confirms my theory, but I'm pretty sure Bitcoin Core was responding to RPC requests with `Loading block index...` (as in OP above) within 120 seconds and to that the proper b 

It could be that the interval between RPC batches and other factors introduce additional uncertainty in this behavior. For example if it takes me 200 seconds to process transactions, then in some cases failures can happen even after a very short restart and in others even `(200 + (poll interval - 1))` seconds can be tolerated.

**Comment by adamkrellenstein** [comment]
solved by https://github.com/CounterpartyXCP/counterparty-core/pull/1789
